### ISSUE TITLE
Add / Change Cmdlet to use MgGraph Module, instead of AdzueAD Module

### ISSUE THREAD

**Issue by rbnkng** [MicrosoftDocs/SupportArticles-docs#1000]
As the AzureAD PS Module will be deprecated soon, it'd be useful to change the Cmdlets to support the alternative Module (MgGraph) 

COUNT: 
`(Get-MgDevice -all:$true | where{($_.TrustType -eq "ServerAd") -and ($_.ProfileType -ne"RegisteredDevice") -and (-not $_.AlternativeSecurityIds)}).count`

CSV:
`Get-MgDevice -all:$true | where{($_.TrustType -eq "ServerAd") -and ($_.ProfileType -ne"RegisteredDevice") -and (-not $_.AlternativeSecurityIds)} | select-object -Property AccountEnabled, Id, DeviceId, DisplayName, OperatingSystem, OperatingSystemVersion, TrustType | export-csv pendingdevicelist-summary.csv -NoTypeInformation`

**Comment by genlin** [comment]
@rbnkng  Thanks for the feedback, Could you provide me with the URL of the article you're referring to?

**Comment by rbnkng** [comment]
Hi @genlin, 

I must have missed that. 

https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/pending-devices

**Comment by ChristySu** [comment]
@rbnkng , feel free to submit your feedback via clicking **Feedback** button on the page https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/pending-devices.
