### ISSUE TITLE
Incorrect token location in 'Rebuild tokens article'

### ISSUE THREAD

**Issue by WindowsAddict** [MicrosoftDocs/SupportArticles-docs#102]
Hi, 

https://docs.microsoft.com/en-us/troubleshoot/windows-server/deployment/rebuild-tokens-dotdat-file

Windows Server 2012 and Windows Server 2012 R2 locations are incorrect,

Correct ones are,

Windows Server 2012,
`"%Systemdrive%\Windows\System32\spp\store\tokens.dat"`

Windows Server 2012 R2,
`"%Systemdrive%\Windows\System32\spp\store\2.0\tokens.dat"`

![Screenshot 2021-04-16 213612](https://user-images.githubusercontent.com/40813939/115057419-aa8bbb80-9f01-11eb-9557-7a87d448166a.png)
![Screenshot 2021-04-16 221330](https://user-images.githubusercontent.com/40813939/115057435-ae1f4280-9f01-11eb-87c3-51a795f5de01.png)

Please fix it. Thanks.

**Comment by Deland-Han** [comment]
@WindowsAddict We are still investigating this. Thank you for your feedback.

**Comment by Deland-Han** [comment]
It is now updated. Thanks for the feedback.
