### ISSUE TITLE
Are only 1709 and 1803 supportable?

### ISSUE THREAD

**Issue by akozeki** [MicrosoftDocs/SupportArticles-docs#104]
I think other Win10 versions are also supported in-place upgrade. Why are only 1709 and 1803 listed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@akozeki, Here the full list of windows 10 versions that support in-place upgrade:

- Windows 10
- Windows 10, version 1709, all editions
- Windows 10, version 1803, all editions
- Windows 10 Enterprise multi-session, all editions

**Comment by akozeki** [comment]
So, does version after 1803 (1909 or 2004) not support in-place upgrade?

**Comment by genlin** [comment]
@akozeki, Thanks for your question.  I will check it with our engineers.

**Comment by genlin** [comment]
@akozeki, I have updated the article with all the supported versions.

**Comment by genlin** [comment]
#please-closed
