### ISSUE TITLE
This is not following security best practice

### ISSUE THREAD

**Issue by lusteel** [MicrosoftDocs/SupportArticles-docs#106]
In Online mitigation 2 it is recommending to set the firewall to allowinbound and allowoutbound by default.
This is allowing all traffic to the machine regardless if it matches a firewall rule or not.
**_netsh advfirewall set allprofiles firewallpolicy allowinbound,allowoutbound_**
The correct command to run should be as follows, which is to deny all traffic by default.
**_netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ff8485-7f5b-150e-1780-e4e2aba8c14e
* Version Independent ID: a72f60cb-69ef-52bf-e2af-bbb754595594
* Content: [Azure VM Guest OS firewall is blocking inbound traffic - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic#mitigation-2)
* Content Source: [support/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by genlin** [comment]
@lusteel  Thanks for the suggestion. I will update that command.

**Comment by genlin** [comment]
Close the issue since the problem has been fixed.
