### ISSUE TITLE
Activation Failed in Force Tunneling and Nat to Azure IP scenario

### ISSUE THREAD

**Issue by Andriy-dev** [MicrosoftDocs/SupportArticles-docs#107]
We are trying to activate ~200 WVD instances behind one NAT ip in Azure ( not on-prem, but in Azure ) . 

We managed to activate Windows10 successfully but on day 2 kms.core.windows.net starts rejects ( tcp.rst ) connections from the clients. 

"Test-NetConnection -ComputerName kms.core.windows.net -Port 1688" failed. 

When I applied a workaround, proposed in the article (UDR in RT) , activation succeeded and Test-NetConnection is succeeded as well.  

Is there any rate-limit on kms.core.windows.net frontend that might block my ip in case of too many simultaneous connection ?

**Comment by genlin** [comment]
@Andriy-dev For this activation issue, I would suggest you contact [Azure support](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for help.
