### ISSUE TITLE
ACS stated as supported in the document

### ISSUE THREAD

**Issue by ManasaDevadas** [MicrosoftDocs/SupportArticles-docs#109]
Is ACS still supported? 
As per the doc it states this  - 
"_Azure Container Service
Many customers use the Azure Container Service (ACS) to quickly deploy a preferred container configuration in Azure. ACS deploys the Docker Engine on either a Linux or Windows system. Full support for issues in deploying Windows Containers in ACS is provided by Microsoft, as was described earlier. Microsoft provides commercially reasonable support for Linux issues. For container engine issues on Linux (Docker), customers should contact Docker support.

The deployment and scaling of the container infrastructure in Azure by using ACS is fully supported by Microsoft._"

But ACS is already retired and while the existing clusters and the applications running on them should continue to work after 31st January 2020, there will be no technical support available or feature improvements.

Please make this clear in the support document since its confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6298d3e6-ded9-614d-b4fb-03148e8ce57f
* Version Independent ID: 8d7923ac-0b69-14ae-2e11-4de49a419992
* Content: [Support policy for containers and related services on Azure - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/support-policy-containers)
* Content Source: [support/azure/general/support-policy-containers.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/support-policy-containers.md)
* Service: **container-service**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ManasaDevadas, thanks for the feedback, Yes, the information in this article is out of date. I will update it.

**Comment by genlin** [comment]
@ManasaDevadas, The article was updated.  I will process to close this issue. Thanks
