### ISSUE TITLE
Clarification with Git Credential Manager (GCM)

### ISSUE THREAD

**Issue by syntaxartisan** [MicrosoftDocs/SupportArticles-docs#1092]
On the page [Troubleshoot issues with Git](https://learn.microsoft.com/en-us/troubleshoot/azure/devops/git-clone-push-operation-failing-devops-repo#cause-3-authentication-error-or-credential-cache-issues), it says  

> If the credential.helper is set to **manager**, then GCM is in use.

I believe GCM is also in use if credential.helper is set to **manager-core**. If that's the case, we may want to specify that both indicate that GCM is in use.

**Comment by ChristySu** [comment]
@syntaxartisan , feel free to submit your feedback via clicking **Feedback** button on the page https://learn.microsoft.com/en-us/troubleshoot/azure/devops/git-clone-push-operation-failing-devops-repo#cause-3-authentication-error-or-credential-cache-issues. Thanks.

**Comment by syntaxartisan** [comment]
I think you're suggesting to use the feedback link at the top of the page, and not the feedback link at the bottom of the page. This is done. Thanks.

**Comment by HaiyingYu** [comment]
@syntaxartisan Sorry for the late update. Thanks for your suggestion. And we're updating the article. The Issues tab here will be disabled soon. In the future, if you have more suggestions, feel free to use the Feedback button.
