### ISSUE TITLE
install-vm-agent-offline  |  Is Step 6 necessary? 

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#1095]
Learn  Troubleshoot  Azure  Virtual Machines 
Here is the public page reference.  
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/install-vm-agent-offline 

I noticed step 6 under the section "Step 2: Modify the OS disk to install the Azure VM Agent" asks to mount "BROKENSOFTWARE", but then it doesn't look like this is ever used/modified.  Why does "BROKENSOFTWARE" need to be mounted?  Thanks.

**Comment by mbiver** [comment]
Here is the github article.

https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/install-vm-agent-offline.md

**Comment by ChristySu** [comment]
@mbiver , could you propose the required changes to this article via a pull request?
