### ISSUE TITLE
Group Policy - Password Policy changes, documentation update

### ISSUE THREAD

**Issue by kristapsesterlins** [MicrosoftDocs/SupportArticles-docs#1099]
Reference - https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/password-policy-changes-not-applied

The issue also occurs if a password policy has been applied at the Default Domain Policy, afterwards removed and then created a separate group policy which is applied either to a OU or Default Domain Controllers Policy.

The documentation is only for Windows Server 2012R2, On later versions the "Block Inheritance" setting is moved to Group Policy Management. Please update it accordingly

Tested on Windows Server 2019 Standard (Domain Controller), Windows 10 workstations.

**Comment by ChristySu** [comment]
@kristapsesterlins, feel free to submit your feedback via clicking **Feedback** button on the page https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/password-policy-changes-not-applied,
