### ISSUE TITLE
Is Firefox supported?

### ISSUE THREAD

**Issue by asurace-swissre** [MicrosoftDocs/SupportArticles-docs#110]
I am having trouble using the console on Firefox.
Please can you add a compatibility matrix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4dfc75-25a4-ae83-8d6a-00f267bf85b9
* Version Independent ID: faa41c37-7b66-671b-09ca-3fb076f701e3
* Content: [Azure Serial Console - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-overview)
* Content Source: [support/azure/virtual-machines/serial-console-overview.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-overview.md)
* Service: **virtual-machines**
* GitHub Login: @asinn826
* Microsoft Alias: **alsin**

**Comment by genlin** [comment]
@asurace-swissre Thanks for the feedback. The Azure portal also supports the Firefox.  If there is a problem on Firefox with Azure serial console, please submit a issue in https://github.com/microsoft/azserialconsole.
