### ISSUE TITLE
Steps missing in force-authoritative-non-authoritative-synchronization

### ISSUE THREAD

**Issue by michelangelobottura** [MicrosoftDocs/SupportArticles-docs#1107]
Once finished, the  DFSR service startup type needs to be back to Automatic, this is not explained in the below web page. 
https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/force-authoritative-non-authoritative-synchronization

**Comment by ChristySu** [comment]
@michelangelobottura, feel free to submit your feedback via **Feedback** button on the page https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/force-authoritative-non-authoritative-synchronization.
