### ISSUE TITLE
Missing download for VB6 Mouse Wheel.exe

### ISSUE THREAD

**Issue by deanwiles** [MicrosoftDocs/SupportArticles-docs#112]
Article [Mouse wheel events do not work in the Visual Basic 6.0 IDE](https://docs.microsoft.com/en-us/troubleshoot/dotnet/visual-basic/mouse-wheel-events-do-not-work) references this downloadable fix:

[Download the VB6MouseWheel.EXE package now.](https://download.microsoft.com/download/e/f/b/efb39198-7c59-4ace-a5c4-8f0f88e00d34/vb6mousewheel.exe)

Unfortunately the download link gives a 404 error. 

Please provide an updated link for vb6mousewheel.exe. 
Thanks.

**Comment by HaiyingYu** [comment]
@deanwiles Thanks for pointing out this issue. We will fix the link in the article.

**Comment by HaiyingYu** [comment]
I'm sorry that the package is not available in the download center now. Removed the broken link.
