### ISSUE TITLE
Need clarity on Microsoft Exchange Server software support for Azure virtual machines

### ISSUE THREAD

**Issue by dburlinson** [MicrosoftDocs/SupportArticles-docs#1124]
On the "Microsoft server software support for Azure virtual machines" page available at link https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/server-software-support.md and under the Microsoft Exchange section it is mentioned:

_"[!NOTE] The only supported way to send email to external domains from Azure compute resources is through an SMTP relay (otherwise known as an SMTP smart host). The Azure compute resource sends the email message to the SMTP relay, and then the SMTP relay provider delivers the message to the external domain. Microsoft Exchange Online Protection is one provider of a SMTP relay, but a number of third-party providers also offer this service."_

But what about sending SMTP directly to the internet from externally facing Azure hosted VMs running Exchange Edge **using BYO IPs** WITHOUT the use of a third party SMTP relay service (such as Sendgrid etc)? Would that be supported?

**Comment by genlin** [comment]
@dburlinson, I think we have to use a reply service unless you are using an Enterprise Agreement subscription that supports SMTP connection on the 25 port.  For more information, see [Troubleshoot outbound SMTP connectivity problems in Azure](https://learn.microsoft.com/en-us/azure/virtual-network/troubleshoot-outbound-smtp-connectivity).
