### ISSUE TITLE
Application Insights Auto Implementation with EF Core 2.1

### ISSUE THREAD

**Issue by ttaylor29** [MicrosoftDocs/SupportArticles-docs#1149]
Hello,

Will application insights auto-implementation ever work with EF Core? 

https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-monitor/app-insights/auto-instrumentation-troubleshoot.md

We tried to enable it using our ef core 2.1 setup, and we keep having this error. 

![image](https://github.com/MicrosoftDocs/SupportArticles-docs/assets/23564255/d4eaabb7-4c7b-4b34-9231-c18d9a47cc42)

So is there a way around this?

We have customers that use azure and are on-prem, and we would like to not release application insights functionality to the on-prem customers

**Comment by ChristySu** [comment]
@ttaylor29 , thanks for your comments. You can submit the feedback via clicking **Feedback** on the page https://learn.microsoft.com/en-us/troubleshoot/azure/azure-monitor/app-insights/auto-instrumentation-troubleshoot.
