### ISSUE TITLE
Generate the report from an existing collection base

### ISSUE THREAD

**Issue by patrickrcdm** [MicrosoftDocs/SupportArticles-docs#1166]
Hey guys,
I'm using PerfInsights to monitor sudden 100% CPU usage.
I created a simple script that runs the tool every 10 minutes and generates the report.
My problem: the server crashes completely with 100% CPU usage, and when that happens, PerfInsights doesn't finish generating the report.
I have the .ETL and .BLG files, and I would like to generate the report based on this information.
It's possible ?
Thank you for any help.
![print](https://github.com/MicrosoftDocs/SupportArticles-docs/assets/25817274/5bf345d9-e30b-4c2d-a7e1-c8e49802ab88)

**Comment by ChristySu** [comment]
Thanks for your comments. You can submit your feedback by clicking **Feedback** on the page that you have questions with.
