### ISSUE TITLE
Friendly Name for "RMSBASIC"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/SupportArticles-docs#117]
Hello, I'd like to know what is the nicer name for this skuPartNumber?  It is isn't listed here: https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference.  Nothing shows up in Azure AD Portal under Licenses > All Products either.

Is it just "Rights Management Service (Basic)"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 661247c2-7469-7a00-add2-8f70468fb940
* Version Independent ID: 197d49ad-c1cc-f2aa-c4bc-5570eb42c9bb
* Content: [Error (This user can't sign in because this account is currently disabled) when syncing settings of Windows 10 - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/event-id-6065-user-cant-sign)
* Content Source: [support/azure/active-directory/event-id-6065-user-cant-sign.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/event-id-6065-user-cant-sign.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@JeremyTBradshaw  Thanks for the interesting question. You are right.  It is related to Basic Rights Management service plan.
