### ISSUE TITLE
Logs validity for SCCM branch 2010

### ISSUE THREAD

**Issue by MilanKrocek** [MicrosoftDocs/SupportArticles-docs#119]
Hello,

I have been testing "Deployment evaluation and update installation on clients" process.

https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/mem/configmgr/track-software-update-deployment-process.md#deployment-evaluation-and-update-installation-on-clients

PolicyAgent.log and PolicyEvaluator.log dont seem to be valid for SCCM branch 2010 as there is no row starting with word "Initializing" as described. Is there any plan to update the post so it will be valid for the branch 2010?
 
Thanks.

MK

**Comment by helenclu** [comment]
@MilanKrocek , thanks for your comment. The log entries were generated in a ConfigMgr 2012/2012R2 environment as an illustrative example. We'll check with the PMs to decide if an update is needed.

**Comment by helenclu** [comment]
Update was rejected. Add a note about versions in the article.
