### ISSUE TITLE
Update public doc with FAQ section

### ISSUE THREAD

**Issue by rjmccallumbigl** [MicrosoftDocs/SupportArticles-docs#137]
Can we add the following within an FAQ for the ALAR scripts:

**What are the compatible Linux distros?**
According to the code [here](https://github.com/Azure/repair-script-library/blob/a1de3460bb2c8b749049e3f0994797109cbb36a4/src/linux/common/helpers/alar/base.sh):
- CentOS/Redhat 6.8 - 8.2
- Ubuntu 16.4 LTS and Ubuntu 18.4 LTS
- Suse 12 and 15
- Debian 9 and 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a16efa-1d65-daa2-3add-12e0314ae900
* Version Independent ID: 440a1711-03a8-f50c-1aba-049168ebffa7
* Content: [Repair a Linux VM automatically with the help of ALAR - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-linux-vm-using-alar)
* Content Source: [support/azure/virtual-machines/repair-linux-vm-using-ALAR.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-linux-vm-using-ALAR.md)
* Service: **virtual-machines**
* GitHub Login: @malachma
* Microsoft Alias: **malachma**

**Comment by malachma** [comment]
Hi Ryan,

that for this suggestion. I have created a new PR to get this info added to the docu.

Regards

From: Ryan McCallum ***@***.***>
Sent: 13 May 2021 21:05
To: MicrosoftDocs/SupportArticles-docs ***@***.***>
Cc: Marcus Lachmanez ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/SupportArticles-docs] Update public doc with FAQ section (#137)


Can we add the following within an FAQ for the ALAR scripts:

What are the compatible Linux distros?
According to the code here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Frepair-script-library%2Fblob%2Fa1de3460bb2c8b749049e3f0994797109cbb36a4%2Fsrc%2Flinux%2Fcommon%2Fhelpers%2Falar%2Fbase.sh&data=04%7C01%7CMarcus.Lachmanez%40microsoft.com%7C98a39b835344418c08a608d9164209a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637565295200752228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nIQQ8lYkDQ7%2FazHPa%2BITe9cvGdjIOk3M43qEFtGtAto%3D&reserved=0>:

  *   CentOS/Redhat 6.8 - 8.2
  *   Ubuntu 16.4 LTS and Ubuntu 18.4 LTS
  *   Suse 12 and 15
  *   Debian 9 and 10

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: c4a16efa-1d65-daa2-3add-12e0314ae900
  *   Version Independent ID: 440a1711-03a8-f50c-1aba-049168ebffa7
  *   Content: Repair a Linux VM automatically with the help of ALAR - Virtual Machines<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Ftroubleshoot%2Fazure%2Fvirtual-machines%2Frepair-linux-vm-using-alar&data=04%7C01%7CMarcus.Lachmanez%40microsoft.com%7C98a39b835344418c08a608d9164209a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637565295200757226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0dX%2BmI9LT4b35TQzEj3KHwbpsl7fWhI1sjVVuug%2FARs%3D&reserved=0>
  *   Content Source: support/azure/virtual-machines/repair-linux-vm-using-ALAR.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FSupportArticles-docs%2Fblob%2Fmain%2Fsupport%2Fazure%2Fvirtual-machines%2Frepair-linux-vm-using-ALAR.md&data=04%7C01%7CMarcus.Lachmanez%40microsoft.com%7C98a39b835344418c08a608d9164209a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637565295200767224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tWYKHJCKtn0mb7QyZmkPyJMPzOxQAyTSCVvbHfueKzA%3D&reserved=0>
  *   Service: virtual-machines
  *   GitHub Login: @malachma<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmalachma&data=04%7C01%7CMarcus.Lachmanez%40microsoft.com%7C98a39b835344418c08a608d9164209a9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637565295200772224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x7qB0pwx9RIK%2BxxdegzOKgRzsMSNFqrczXBQqyQH52U%3D&reserved=0>
  *   Microsoft Alias: malachma

**Comment by rjmccallumbigl** [comment]
@malachma thank you!

**Comment by genlin** [comment]
@malachma @rjmccallumbigl  A pull request has been submitted to update the article. So I will close this issue. Thanks for your feedback.
