### ISSUE TITLE
use PowerShell to get schema version

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/SupportArticles-docs#144]
for...
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/find-current-schema-version

...you can do this using PowerShell;

`Get-ItemProperty  'AD:\CN=Schema,CN=Configuration,DC=corp,DC=contoso,DC=com' -Name objectVersion`

**Comment by Deland-Han** [comment]
@anwarmahmood1 Thank you for your feedback. I am working on this.

**Comment by Deland-Han** [comment]
Hi, I have updated the article as suggested. Thank you for the feedback.
