### ISSUE TITLE
Looks suspicious.

### ISSUE THREAD

**Issue by jopowel** [MicrosoftDocs/SupportArticles-docs#147]
This doesn't look official.
I am highly suspicious of this content.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa57e45a-8225-9181-2a5d-f74e093f9cc8
* Version Independent ID: 9f240f7f-7af6-4066-caf7-e4cd6bb54ebf
* Content: [Email address domains used by Microsoft support professionals - Azure](https://docs.microsoft.com/en-gb/troubleshoot/azure/general/email-domains-support-agent?source=docs)
* Content Source: [support/azure/general/email-domains-support-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/email-domains-support-agent.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@jopowel Thanks the question . The support email addresses descried in this article  are correct.

**Comment by genlin** [comment]
#please-close
