### ISSUE TITLE
failover cluster server OS requirements

### ISSUE THREAD

**Issue by Trundlore** [MicrosoftDocs/SupportArticles-docs#148]
Hi,

the requirements listed here for creating a failover cluster state:

> Must Run Windows Server 2012 R2, Windows Server 2012, Windows Server 2008 R2

Is this supported on Server 2016, 2019, and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b703446-c838-fd33-09fe-1df826399931
* Version Independent ID: ff85d0c9-ecb0-987b-7b4c-fa252a93c55b
* Content: [Microsoft server software support for Microsoft Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/server-software-support)
* Content Source: [support/azure/virtual-machines/server-software-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/server-software-support.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Trundlore, Windows Server 2016 and Windows Server  2019 are supported. The article is out of date. I will update it to include the latest versions of windows server. Thanks

**Comment by genlin** [comment]
@Trundlore, A pull request has been submiited to update the article. I will close this issue. Thanks again,
