### ISSUE TITLE
Please provide some examples 

### ISSUE THREAD

**Issue by cltj** [MicrosoftDocs/SupportArticles-docs#150]
This is only a documentation for users that 
1) know about what "AssertionConsumerServiceURL" is
2 ) know how to fix it 

I don't understand that this can be official Microsoft documentation, when its basically saying "<variable> is missing, you have to add it". 
Why even assume that customers know what this is? 

Extra nice touch with the circular docs ( refers to this document, https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes, 
that in turn refers back to 
https://docs.microsoft.com/nb-no/troubleshoot/azure/active-directory/error-code-aadsts50011-reply-url-mismatch ) 

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: b5d2d805-50e5-3494-6388-2497d973a080
* Version Independent ID: 63166523-8137-7d97-045f-811f884bb991
* Content: [Error AADSTS50011 - The reply URL specified in the request does not match the reply URLs configured for the application. - Active Directory](https://docs.microsoft.com/nb-no/troubleshoot/azure/active-directory/error-code-aadsts50011-reply-url-mismatch)
* Content Source: [support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@cltj Thanks for the feedback. We will investigate and improve the document.

**Comment by genlin** [comment]
@cltj  For detailed steps about how to configure the values in Azure AD, you can refer to https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/salesforce-tutorial. Also there is [a video](https://www.youtube.com/watch?v=a_abaB7494s) about how to troubleshoot the AADSTS50011 error. I will also add these resources into the article. Thanks again for your suggestions.
