### ISSUE TITLE
Needs updated for 32-bit application running on 64-bit registry keys

### ISSUE THREAD

**Issue by theguru0** [MicrosoftDocs/SupportArticles-docs#151]
Missing the WOW6443Node reference as well as the slash after "Microsoft".

•	HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727
o	"SystemDefaultTlsVersions": 00000001
o	"SchUseStrongCrypto": 00000001
•	HKEY_LOCAL_MACHINE\SOFTWARE\ WOW6432Node \Microsoft\.NETFramework\v4.0.30319
o	"SystemDefaultTlsVersions": 00000001
o	"SchUseStrongCrypto": 00000001

So all eight are really needed.  For a report builder all that I found was 32-bit, I had to add the v4 keys before it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable support for TLS 1.2 in your environment, in preparation for upcoming Azure AD TLS 1.0/1.1 deprecation - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@theguru0 Thanks for the feedback. You are right. The correct key path should be:

- HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v2.0.50727

- HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319

**Comment by genlin** [comment]
@theguru0  A pull request has been submitted to update the article. I will close this issue. Thanks
