### ISSUE TITLE
Object

### ISSUE THREAD

**Issue by timmedina** [MicrosoftDocs/SupportArticles-docs#167]
[Enter feedback here]
This article fails to define what is or is not an object. This reference should be explicit to aid the customer and technical resources to understand what makes up the count explicitly. Secondary searches on object yield docs using unaligned language for resource or objectID based resources. To an outside reader this is confusing and provides no focused understand of what an object is and how it adds to the object count issue above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 201e070f-b494-437a-2a44-945ea17928fd
* Version Independent ID: 6625800d-f778-2c57-d5b0-31e27c8703ba
* Content: [Error (This company has exceeded the number of objects that can be synchronized) displays in a directory synchronization report - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/exceed-number-objects-synced)
* Content Source: [support/azure/active-directory/exceed-number-objects-synced.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/exceed-number-objects-synced.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@timmedina， Thanks for the feedbacks. We will investigate and improve the article.

**Comment by timmedina** [comment]
I see this was closed but I am not seeing a relevant statement of what an object is. This reads like a user or group are the few targets that are categorized as an object in Azure. This is not the case on a base technical level. Can this be reopened and modified to bring the language inline to the actual definition of Object to Azure?
