### ISSUE TITLE
Spelling Mistake - in article (linked in comment)

### ISSUE THREAD

**Issue by YorkieFl** [MicrosoftDocs/SupportArticles-docs#172]
Apologies, didn't really want to submit a whole issue for this but noticed a slight mistake in part of this Doc 
-
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/replication-error-2146893022
-
Specifically mid way down the page it says to use REPADIN where it should be REPADMIN

![image](https://user-images.githubusercontent.com/44997756/121661033-b330e600-ca9b-11eb-8f53-b7ac36267371.png)

**Comment by YorkieFl** [comment]
It wouldn't let me edit the page to change it

**Comment by Deland-Han** [comment]
Thank you. @YorkieFl. I have fixed it.
