### ISSUE TITLE
Article on Disk Cleanup `/sageset:n` switch lacks specificity as to the Registry key path that is created by it

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/SupportArticles-docs#174]
RE: https://github.com/MicrosoftDocs/SupportArticles-docs/blob/0d2c584020c1a77a351569c2cadaa7e444bb2fa7/support/windows-server/backup-and-storage/automating-disk-cleanup-tool.md

RE: https://docs.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/automating-disk-cleanup-tool

Hi,

Please see the figure below  --- this issue has to do with the following text:

![image](https://user-images.githubusercontent.com/8261875/121778462-fe62fb80-cb64-11eb-9189-d307f1fe01b0.png)
**Figure 1.**  Documentation that specifies that `/sageset:n` creates a Registry key to which it saves the settings.

The issue is --- _WHICH_ Registry key is that?  The article does not provide the path to the specific Registry key.   It would save time and trouble when I am configuring my Technician PC to have this article explain where _exactly_ in the Registry I need to go, as opposed to having to do a tedious "F3 Find" in `RegEdit.exe.`

I would highly suggest updating the article to add the full path (with, obviously, an `n` in it since we do not know for which `/sageset:n` this is) to the specific Registry key saved by the command.

I really appreciate any help you can provide.

**Comment by Deland-Han** [comment]
Hi @astrohart, thank you for the feedback.

The registry keys are used to save the settings, which will be used by the `/sagerun:n` switch. Therefore generally we do not need to manually access the registry keys - we just need to call the `/sagerun:n` switch.

Do you encounter any specific scenario in which manually accessing the registry keys is necessary?

**Comment by astrohart** [comment]
Yes. Such as in moving in settings to a different computer to apply them, say, when configuring multiple images as part of an IT operation.

Regards,
 
Brian C. Hart, Ph.D.

**Comment by Deland-Han** [comment]
I see. I have added a section introducing the registry key changes. Thank you for the feedback.

**Comment by astrohart** [comment]
Thank you! ☺️

Regards,
 
Brian C. Hart, Ph.D.
