### ISSUE TITLE
Unable to copy the reply URL from an application Sign-in Pop-up menu 

### ISSUE THREAD

**Issue by JADEXCIO** [MicrosoftDocs/SupportArticles-docs#175]
I am attempting to resolve this error related to the Microsoft Dynamics 365 Project Service Automation Add-in for Microsoft Project.  First, I am not sure why a Microsoft created add-in doesn't intuitively make the proper authentication connections for end-users. Secondly, the instructions provided in this video do not account for popup menus related to sign-in's.  Specifically,  I am unable to access the associated URL to resolve this issue due to having access to the address bar in the pop-up menu.

Any advise on resolving this issue would be appricated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d2d805-50e5-3494-6388-2497d973a080
* Version Independent ID: 63166523-8137-7d97-045f-811f884bb991
* Content: [Error AADSTS50011 - The reply URL specified in the request does not match the reply URLs configured for the application. - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-reply-url-mismatch)
* Content Source: [support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@JADEXCIO To troubleshoot the issue, please contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
