### ISSUE TITLE
Constrained delegation for CIFS missing info on how to not have SMB check for /IPC$

### ISSUE THREAD

**Issue by PeterHalsted** [MicrosoftDocs/SupportArticles-docs#176]
The article "Constrained delegation for CIFS fails with ACCESS_DENIED error" (https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/constrained-delegation-access-denied) is great for solving the initial Kerberos issue, but it does not provide either input or links for solving the issues coming after. 

E.g. how to solve the /IPC$ folder check on the network share, which ends return an HTTP 500 and there are probably other similar issues, for which there already exists known ways to solve.

**Comment by Deland-Han** [comment]
Thanks. @PeterHalsted.

We will discuss it and see if we can add further troubleshooting information to the article.

**Comment by PeterHalsted** [comment]
Hi @Deland-Han,
My issues were related to DFS and the SMB client using time on resolving the location (maybe a link to DFS would be good?) and with ASP.NET Handler, which seems to have disappeared after changing app pool to Classic from Integrated.
