### ISSUE TITLE
Solution provided is not valid as you are not extending the OS disk any where in the steps

### ISSUE THREAD

**Issue by ThiruthamSivaram** [MicrosoftDocs/SupportArticles-docs#181]
[Enter feedback here]
Which disk is referred in this document to resize to 1 TB. Is it a typo for GB. If it is not typo how much free disk space is required to apply the patch on OS drive. From the steps provided you are not extending the OS disk. Please have a look at the solution provided.

Azure VM is unresponsive with C01A001D error when applying Windows Update - Virtual Machines
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f27b89-2298-4df0-27c5-19360e0a557c
* Version Independent ID: 83e5144f-60c4-cd82-417e-62fdec52db89
* Content: [Azure VM is unresponsive with C01A001D error when applying Windows Update - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unresponsive-vm-apply-windows-update?source=docs)
* Content Source: [support/azure/virtual-machines/unresponsive-vm-apply-windows-update.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/unresponsive-vm-apply-windows-update.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **v-mibufo**

**Comment by genlin** [comment]
@ThiruthamSivaram  Thanks for the feedback. Yes, you are right. It does not make sense to require 1 TB space for system upgrade. I will check with our engineers about this solution.

**Comment by genlin** [comment]
Close the issue since the problem has been fixed,.
