### ISSUE TITLE
Incorrect Registry Subkey

### ISSUE THREAD

**Issue by coop333** [MicrosoftDocs/SupportArticles-docs#182]
On this page - https://docs.microsoft.com/en-us/troubleshoot/sql/general/determine-version-edition-update-level
At this section - sql-server-native-client
There is an error with the subkey listed for native client 11. It should be as follows:

|SQL version /</br>SQL Server Native Client version|Registry subkeys|
  |---|---|
  |SQL Server 2012, SQL Server 2014 and SQL Server 2016/ SQL Server Native Client 11.0 |HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\SQLNCLI11\CurrentVersion|
  |SQL Server 2008 & SQL Server 2008 R2/</br> SQL Server Native Client 10 |HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\SQLNCLI10\CurrentVersion|
  |SQL Server 2005/</br>SQL Server Native Client 9|HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Native Client\CurrentVersion|
  |||

**Comment by HaiyingYu** [comment]
@coop333 Thanks for pointing out this issue. I will fix it in the article.

**Comment by HaiyingYu** [comment]
The article was updated. I will close the issue. Thanks!
