### ISSUE TITLE
WHAT HAPPENS TO THE DEVICE IF OTHER USERS IN THE DOMAIN NEED TO USE IT

### ISSUE THREAD

**Issue by EvilSlacker08** [MicrosoftDocs/SupportArticles-docs#184]
Why can't you state what happens to the device after you delete it from a user's device list.  In our domain, multiple people use different workstations every day.  In my case, I am constantly rebuilding workstations, rejoining them to the domain and installing Office 365.  So what happens should one of the devices be removed from my user account under devices.  

Hopefully, it is still functional.  Otherwise, who thought up this crazy concept of capping the number of devices.  It's just frustrating as hell when we are already paying for the O365 subscriptions to utilize the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cffa8f2-c2e5-34f1-6b62-0b4d37a43120
* Version Independent ID: 07d66fc0-3f76-b505-baca-3df0b0dab279
* Content: [Error (The maximum number of devices that can be joined to the workplace by the user has been reached) during a Workplace Join - Active Directory](https://docs.microsoft.com/en-US/troubleshoot/azure/active-directory/maximum-number-of-devices-joined-workplace)
* Content Source: [support/azure/active-directory/maximum-number-of-devices-joined-workplace.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/maximum-number-of-devices-joined-workplace.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@EvilSlacker08, I am not sure if your issue is caused by the maximum number of devices is reached. I would suggest you contact [Microsoft support](https://support.microsoft.com/) to troubleshoot the issue.
