### ISSUE TITLE
Enable support for TLS 1.2 in your environment for Azure AD TLS 1.1 and 1.0 deprecation

### ISSUE THREAD

**Issue by RyanBHernandez** [MicrosoftDocs/SupportArticles-docs#187]
Hello Team,

Can you please confirm the actual date of the deprecation?  

https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment
Why this change is being made
These protocols and ciphers are being deprecated for the following reasons:

To comply with the latest compliance standards for the Federal Risk and Authorization Management Program (FedRAMP).
To improve security when users interact with our cloud services.
The services are being deprecated on the following dates:

TLS 1.0, 1.1 and 3DES Cipher suite in U.S. government instances starting on March 31, 2021.
TLS 1.0, 1.1 and 3DES Cipher suite in public instances starting January 31, 2022.

Customer is saying (not sure where they got the information)  that this will be deprecated end of June 2021.

Probably from this page: https://techcommunity.microsoft.com/t5/azure/azure-active-directory-tls-1-0-tls-1-1-and-3des-deprecation/m-p/2148244

Also this page for AD updates: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#azure-active-directory-tls-10-tls-11-and-3des-deprecation [see March 2021]

Best regards,
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable support for TLS 1.2 in your environment, in preparation for upcoming Azure AD TLS 1.0/1.1 deprecation - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?WT.mc_id=Portal-Microsoft_Azure_Health)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@RyanBHernandez I will close this issue since it is resolved offline.
