### ISSUE TITLE
Max File Size

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/SupportArticles-docs#189]
Add details on max file size supported
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2957a41-0ebd-4f1e-6f9c-d4f9173d4630
* Version Independent ID: e92921f7-9899-6a70-412f-f6094e772271
* Content: [How to use Secure File Exchange to exchange files with Microsoft Support - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/secure-file-exchange-transfer-files)
* Content Source: [support/azure/general/secure-file-exchange-transfer-files.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/secure-file-exchange-transfer-files.md)
* Service: **storage**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@danmyhre, Thanks for the question. I will check it with our engineers team.

**Comment by genlin** [comment]
@danmyhre The file size limit in Secure File Exchange is 100Gb per file. I will also add this information to the article.
