### ISSUE TITLE
Misunderstanding due to wrong automated translation

### ISSUE THREAD

**Issue by RegConHahn** [MicrosoftDocs/SupportArticles-docs#190]
Hello,

I noticed some issue in the relation between the english article and other languages. 
There are more and more misunderstandings because of the automated Translation. 

For example. If you look at this doc page:

https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows

You can see the Code examples be like:

![image](https://user-images.githubusercontent.com/86781347/124121974-d08f1980-da75-11eb-995e-08d2a3009cd7.png)

If you switch the language (in this case "Deutsch") you get the following:

![image](https://user-images.githubusercontent.com/86781347/124122077-f4525f80-da75-11eb-9b71-fb193bfbe88d.png)

It translates "dec" with the german Word for December.  And thats not the first time i saw something like that.

Sometimes this issue can lead to completely different articles, which will lead the user into trouble or misconfigurations.

For myself it is no problem, because I learned English as an second language. But there is an amount of users, that can't understand English good enough. So the translation is realy usefull, but not if its creating wrong settings etc.

**Comment by Deland-Han** [comment]
@RegConHahn Thank you for the feedback. I am working on it.

**Comment by Deland-Han** [comment]
I have modified this article to fix the issue. Dec is not a valid abbreviation for the machine translation service so I change them to Decimal, Hexadecimal and Binary.
