### ISSUE TITLE
The problem of a small C drive

### ISSUE THREAD

**Issue by mgrazebrook** [MicrosoftDocs/SupportArticles-docs#191]
Reading this:

https://docs.microsoft.com/en-US/troubleshoot/windows-server/user-profiles-and-logon/relocation-of-users-and-programdata-directories

My laptop was shipped with 100MB of SSD on C: with Windows 10 Home installed and 1TB on D:.

I installed as many programmes as possible on D: but even so, C: rapidly filled to 100% and software failed.

WinDirStat shows that the main non-OS objects remaining exist in ProgramData and AppData. I'm a professional programmer and finding this hard and time-consuming to fix (albeit this is my home PC not my work one).

Suggestions:

(1) The article should recognise 'run out of space on C:' as one of the "most common reasons".

(2) The pink "Caution" states that moving these will "will block your ability to upgrade" - a scary thought. Many people won't read to the end and learn "Beginning with Windows 10, OS upgrades are supported". 

(3) The second Caution block doesn't note that upgrades are supported so I'm now unclear if this is safe in Windows 10

(4) The article doesn't actually tell you _how_ to make the change, does it? The title is 'Relocation' but I'm unsure from reading this whether or not I can _relocate_ existing folders.

(5) For those who can't solve an 'out of disk capacity' problem by following this page, it would be helpful to provide links.

**Comment by Deland-Han** [comment]
Hi @mgrazebrook,

Instead of introducing how to change the folders, this article is actually about the blocked upgrade due the using of the unattend settings. 

The current content is a bit misleading. I have modified the article.   Thank you for the feedback.

**Comment by mgrazebrook** [comment]
I appreciate your fast response. 

Would it be correct to re-word the first 'caution' to begin:

_Prior to Windows 10,_ using the ProgramData setting to redirect folders to a drive other than the system volume will block your ability to upgrade to future versions of Windows.
