### ISSUE TITLE
Well-known SIDs missing from Documentation

### ISSUE THREAD

**Issue by omry99** [MicrosoftDocs/SupportArticles-docs#193]
Hello,

I've noticed that there are two well-known SIDs that are missing from the relevant documentation pages.
The documentation pages I am referring to are:
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows
https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers
https://docs.microsoft.com/en-us/windows/win32/secauthz/well-known-sids

The two well-known SIDs and their respective accounts are:
DefaultAccount           S-1-5-21domain-503
WDAGUtilityAccount   S-1-5-21domain-504

**Comment by Deland-Han** [comment]
@omry99 Thank you for the feedback. I will check with our engineers team on this change.

**Comment by Deland-Han** [comment]
Hi, we have added the information, and merge the information from https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows to https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers.

Thank you for your feedback.
