### ISSUE TITLE
Verify a first-party Microsoft Service Principal in your AAD tenant

### ISSUE THREAD

**Issue by stevelsd** [MicrosoftDocs/SupportArticles-docs#196]
Using the Microsoft PowerShell command to determine if "support@support.onmicrosoft.us" is indeed a first party MS service principal I get nothing. 
Customer is seeing this account in his audit logs performing what it appears to be bulk MFA modification on the user accounts in his tenant.

No one nor article has any reference to that account.  Can someone advise?
Thank you
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33be97f8-2846-f5d1-a196-7019d44327b2
* Version Independent ID: 5f0bb5e3-dbc5-f004-fe9d-8a814bfd654c
* Content: [Unknown Actors in Audit Reports - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/unknown-actors-in-audit-reports)
* Content Source: [support/azure/active-directory/unknown-actors-in-audit-reports.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/unknown-actors-in-audit-reports.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@stevelsd, This email address support@support.onmicrosoft.us is **not** from Microsoft support team.  

[Click here to learn how to identify whether an email is from Microsoft support]( https://docs.microsoft.com/troubleshoot/azure/general/email-domains-support-agent?source=docs)

**Comment by stevelsd** [comment]
Thank you for your time to make a response but an email is not the issue.
Support@support.onmicrosoft.us is the account that is listed in the audit logs.

I am looking for an MS expert or MS FTE team member to advise that this is indeed a first-party Microsoft Service Principal in an AAD tenant.

Please someone else assist?
Thank you

**Comment by genlin** [comment]
@stevelsd, I would suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request)to verity this Service Principal.
