### ISSUE TITLE
Alternatively, if SAC : CMD is not working.

### ISSUE THREAD

**Issue by VGSandz** [MicrosoftDocs/SupportArticles-docs#199]
[Enter feedback here]
1.Create a New NIC from Network Interfaces Blade, with free ip in the subnet.
2.Stop/deallocate the VM.
3.Attach the new NIC created in step 1.
4.Boot up the VM , connect with the new IP.
5.Enable the 'disabled' network interface.
6.Validate reachability.
7.Then,stop/deallocate the VM.
8.Delete the temporary NIC created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d5b9b6-087b-7b1a-76f4-62147295519e
* Version Independent ID: a97ab17c-33f2-c8c6-5467-f00491f354da
* Content: [Cannot connect remotely to Azure Virtual Machines because the NIC is disabled - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-nic-disabled?source=docs)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-nic-disabled.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-nic-disabled.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@VGSandz, Thank you for the feedback, If the SAC does not work, user can reset the NIC by using the steps in https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-network-interface
