### ISSUE TITLE
FCIV page points to missing download

### ISSUE THREAD

**Issue by walbourn** [MicrosoftDocs/SupportArticles-docs#2]
https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/fciv-availability-and-description

This page links to the FCIV tool, but it was removed from the Microsoft Downloads site per the removal of SHA-1 content.

**Comment by walbourn** [comment]
A better solution is to point to the built-in Windows command [certfile](https://www.shellhacks.com/windows-md5-sha256-checksum-built-in-utility/)

**Comment by Deland-Han** [comment]
Hi @walbourn, thank you for the feedback! as the FCIV tool is no longer available, the article is already outdated. Therefore, we have removed the page.
