### ISSUE TITLE
Powershell script missing from repository?

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/SupportArticles-docs#202]
@helenclu 
Hi Helen, 
On this [document](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/mem/configmgr/wsus-maintenance-guide.md)
The section > the PowerShell script is not available to be downloaded: 
_If you are using standalone WSUS servers or an older version of configuration Manager, you can manually decline superseded updates by using the WSUS console. Or you can run this **PowerShell script.** To download the script, right-click the link, and then select Save target as.... Download the script, remove the .txt file extension, and save the file with a .PS1 extension._

Please check and let me know?
Thanks, M

**Comment by simonxjx** [comment]
Script is available via https://docs.microsoft.com/troubleshoot/mem/configmgr/decline-superseded-updates.
