### ISSUE TITLE
Spelling Mistake 'SHH'

### ISSUE THREAD

**Issue by Viajaz** [MicrosoftDocs/SupportArticles-docs#206]
> ... to use Ed25519 **SHH** keys ...

SHH should be SSH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc17b52-0b92-3afb-bdb3-e2e2c226dcae
* Version Independent ID: 2f237d65-0e67-429c-16c3-fe7573e05c44
* Content: [Can't use Ed25519 SSH keys for Azure Linux VMs - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/ed25519-ssh-keys)
* Content Source: [support/azure/virtual-machines/ed25519-ssh-keys.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/ed25519-ssh-keys.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Viajaz  Thanks for pointing out the typo. It was fixed now.
