### ISSUE TITLE
az vm repair doesnt work for Gen2 Vm's

### ISSUE THREAD

**Issue by htallur** [MicrosoftDocs/SupportArticles-docs#214]
[
Disk-name not given. Defaulting to the first data disk attached to the repair VM: heprodireach-h1-DiskCopy-20210720220518.667386
Detaching repaired data disk from repair VM...
Attaching repaired data disk to source VM as an OS disk...
ERROR: (PropertyChangeNotAllowed) Swapping OS Disk is not supported since HyperVisor property on the OSDisk and VM do not match. Please make sure the HyperVisor property on the OSDisk is HyperVisor Generation 'V2'

Repair restore failed. If the restore command fails at retry, please rerun the repair process from 'az vm repair create'.
{
  "error_message": "ERROR: (PropertyChangeNotAllowed) Swapping OS Disk is not supported since HyperVisor property on the OSDisk and VM do not match. Please make sure the HyperVisor property on the OSDisk is HyperVisor Generation 'V2'\n",
  "message": "Repair restore failed. If the restore command fails at retry, please rerun the repair process from 'az vm repair create'.",
  "status": "ERROR"
}e]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa79b852-287a-5320-a69a-78b4c8549ebf
* Version Independent ID: 5df6b2a4-c938-392e-b980-29d270827b35
* Content: [Repair a Linux VM by using the Azure Virtual Machine repair commands - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-linux-vm-using-azure-virtual-machine-repair-commands)
* Content Source: [support/azure/virtual-machines/repair-linux-vm-using-azure-virtual-machine-repair-commands.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-linux-vm-using-azure-virtual-machine-repair-commands.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by genlin** [comment]
Thank you for your feedback . We will investigate and update the thread.

**Comment by genlin** [comment]
@htallur To resolve this issue quickly, I suggest you contact [Azure support](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).
