### ISSUE TITLE
Could we add an FAQ section?

### ISSUE THREAD

**Issue by rjmccallumbigl** [MicrosoftDocs/SupportArticles-docs#221]
**What generations are currently supported?**

- Generation 1. Gen2 VMs are not fully supported at this time but we are working to improve the experience.
  - If you run the script on a Gen2 Azure VM, it will create a Gen1 Repair VM.
  - If you use the script on a Gen2 Azure VM to create a Nested VM (as in, an internal Hyper-V VM on the Repair VM), the Nested VM will be a Gen1 and thus will have to be recreated as a Gen2 if troubleshooting in the Hyper-V environment.

**What is the purpose of the Rescue VM's Tags?**

- The repair VM will have tags generated as part of the script. The cmdlet uses these tags to identify the source VM and Resource Group for the "restore" functionality that swaps the corrected OS disk with the original OS disk in the problem VM. This is by design, so please do not modify these tags. 
  - Also note that these Tags are case sensitive. When restoring the OS disk, please use the same case used when creating the resources (indicated by the Tags) as the script will fail to find them if the Tags have a different case. 
    - For example,  if you use `az vm repair create -g MyResourceGroup -n MyVM` to create a Repair VM, your restoration command must be `az vm repair restore -g MyResourceGroup -n MyVM`. 
    - If the case is different, e.g. `az vm repair restore -g myresourcegroup -n myvm`, the script will fail with the error `Repair VM not found for myvm. Run ‘az vm repair create -n myvm -g myresourcegroup --verbose’ to create repair vm and rerun the command`.

**Why did my Repair VM creation fail?**

- The operation will fail if you have Azure Policies blocking the creation of VMs, VMs with a Public IP address, or VMs with Resource Tags outside of allowed Tags. If you are unable to lift these restrictions, you may have to manually create your Repair VM, or utilize an already existing non-production VM within your environment to act as a temporary Rescue VM.
- If you used the wrong casing for your restore command (see above), the command will fail to find the source VM. Please retry the command with the correct casing.
- Please run with the --debug or --verbose parameters for more information on why the operation failed.

**Should I run via the Azure Cloud Shell or locally?**

- It depends. The Cloud Shell is normally the perfect vehicle to run the script, but for some longer script operations (e.g. the `win-sfc-sf-corruption` script), the Cloud Shell can time out after ~20 minutes. This prevents us from seeing the results from the Cloud Shell and it may be hard to recover the session. Rerunning the script can give the error `Run command extension execution is in progress. Please wait for completion before invoking a run command.”`
- If you have [Az PowerShell](https://docs.microsoft.com/en-us/powershell/azure/?view=azps-6.2.1) or [CLI](https://docs.microsoft.com/en-us/cli/azure/) locally installed, you can run these commands without a time limit, so please consider these for longer scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c86f8d-4f70-e909-6b8f-321cb018532e
* Version Independent ID: 32044cf7-cf37-b4e9-0ebf-47df90de7cda
* Content: [Repair a Windows VM by using the Azure Virtual Machine repair commands - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands)
* Content Source: [support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by genlin** [comment]
@rjmccallumbigl  Thanks for your contribution! I will notify the author to review your proposed FAQ.
