### ISSUE TITLE
This refers to changing the user's "home directory" but does not specify how to do that. I cannot find that anywhere in any documentation of how to change an Azure AD user's "home directory".

### ISSUE THREAD

**Issue by jdenicola-pa** [MicrosoftDocs/SupportArticles-docs#225]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638c8b9c-257d-b718-4c60-6e57117efa4e
* Version Independent ID: 48ca91b1-953a-b0c9-d788-9bb83005667a
* Content: [A user is displayed as disabled or enabled for Microsoft Azure Multi-Factor Authentication but behaves as the opposite - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/user-displayed-disabled-or-enabled-mfa)
* Content Source: [support/azure/active-directory/user-displayed-disabled-or-enabled-mfa.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/user-displayed-disabled-or-enabled-mfa.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@jdenicola-pa,If your Azure subscription hosts multiple directories, we can change the home direction in the Azure portal by the following steps:

1. In the Azure portal, go to Subscription page. 
2.  Click "Switch directories", and then change to directory that host the users..

If you need further assitance, please contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
