### ISSUE TITLE
"Known Issue Rollback 062521 01.msi" location

### ISSUE THREAD

**Issue by Shaboogity** [MicrosoftDocs/SupportArticles-docs#234]
Step 3 of the Resolution section advises to download and install the "Known Issue Rollback 062521 01.msi" with a link to https://support.microsoft.com/topic/may-11-2021-kb5003197-os-build-14393-4402-672e4557-b496-4ec7-bf26-3268aaf16697

That msi file is not in the linked page, so either reported page or the linked page may be out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f27b89-2298-4df0-27c5-19360e0a557c
* Version Independent ID: 83e5144f-60c4-cd82-417e-62fdec52db89
* Content: [Azure VM is unresponsive with C01A001D error when applying Windows Update - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unresponsive-vm-apply-windows-update)
* Content Source: [support/azure/virtual-machines/unresponsive-vm-apply-windows-update.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/unresponsive-vm-apply-windows-update.md)
* Service: **virtual-machines**
* GitHub Login: @jc-mackin
* Microsoft Alias: **v-jcmackin**

**Comment by genlin** [comment]
@Shaboogity, Thanks for the feedback. I will check if there is a replacement link for this package.

**Comment by genlin** [comment]
@Shaboogity, the link to "062521 01.msi" is: 

https://download.microsoft.com/download/e/c/6/ec684975-1ad7-4d6f-a228-2da17b0a72b3/Windows%2010%20(1607)%20Known%20Issue%20Rollback%20062521%2001.msi

I will also update the article with this new link.
