### ISSUE TITLE
Note about black screen, use consoleblank to disable screensaver

### ISSUE THREAD

**Issue by Klaas-** [MicrosoftDocs/SupportArticles-docs#235]
Hi,
while reading up on the serial console I came across the following note:
"If you are not seeing anything in the serial console, make sure that boot diagnostics is enabled on your VM. Hitting **Enter** will often fix issues where nothing is showing up in the serial console."
Source: https://github.com/MicrosoftDocs/SupportArticles-docs/blame/main/support/azure/virtual-machines/serial-console-linux.md#L57

This is most likely because of the screensaver the kernel is enabled, you can use consoleblank as kernel parameter to disable it:
https://www.kernel.org/doc/html/v5.13/admin-guide/kernel-parameters.html?highlight=consoleblank

check /sys/module/kernel/parameters/consoleblank if it's enabled in the VMs. For RHEL, it seems RHEL7 does not set it automatically, RHEL8 seems to detect that it's a VM and automatically sets consoleblank=0 which disables the screensaver

Greetings
Klaas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027253ab-b1d6-6707-a608-ff71c5c7f712
* Version Independent ID: 377cb416-6cad-436a-df96-68a7513c7acc
* Content: [Azure Serial Console for Linux - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-linux#serial-console-linux-distribution-availability)
* Content Source: [support/azure/virtual-machines/serial-console-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-linux.md)
* Service: **virtual-machines**
* GitHub Login: @asinn826
* Microsoft Alias: **alsin**

**Comment by Klaas-** [comment]
Ah I see why the default of the kernel changed in 4.15 -- so older linuxes will need this set manually, newer ones have it automatically

**Comment by genlin** [comment]
@Klaas Thanks for the feedback. I will investigate and update this thread.
