### ISSUE TITLE
Command looks and acts incomplete

### ISSUE THREAD

**Issue by ToddMaxey** [MicrosoftDocs/SupportArticles-docs#237]
support/windows-server/identity/adfs-error-180-endpoints-missing.md

Regarding... https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/adfs-error-180-endpoints-missing

Step 1: Verify the problem
Determine whether the openid-configuration endpoint can be reached by running the following command at a PowerShell command prompt:

PS:> **Get-AdfsEndpoint -AddressPath "/adfs/.well-known/openid-"**

The above command looks and acts incomplete.

I believe it should be Get-AdfsEndpoint -AddressPath "/adfs/.well-known/openid-configuration

**Comment by Deland-Han** [comment]
@ToddMaxey Thank you for the feedback. I have fixed the issue and re-publish the article.

**Comment by ToddMaxey** [comment]
Anytime!


Sent from a mobile device.
Expect typographical errors and inevitable miscommunications.

My apologies in advance.

No trees were utilized in the posting of this message. However a enormous number of electrons were terribly inconvenienced.

________________________________
