### ISSUE TITLE
The "method" provided on the document will create an invalid password on /rescue/etc/shadow, thus locking out the user from the server.

### ISSUE THREAD

**Issue by carlosporter** [MicrosoftDocs/SupportArticles-docs#238]
The instructions provided at the documentation page linked below will generate an incorrect user password hash on /rescue/etc/shadow
  
  [How to reset local Linux password on Azure VMs](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-password)

Quote:
`"This article introduces several methods to reset local Linux Virtual Machine (VM) passwords."`

Actually, the article explains **ONLY ONE METHOD** with several steps, so this is not a good start.

The main problem are the steps 7, 8 and 9 because they require to copy the files used for user authentication, between the rescue VM and the root file system on the data disk,  to update /rescue/etc/shadow

**This is a bad method to change/reset a user password on a Linux VM, because it works only if the both virtual machines meet these requirements:**

So, it's more likely you will end up with an invalid hash on /rescue/etc/shadow and the user will still be locked out from the server.

Below I'm describing better/safer alternatives to change a user password on a Linux server running on Azure.

### Steps to reset the password from a user account on Linux ( without a rescue VM, requires WALinuxAgent )

1. Make sure that WA Linux Agent service is running on the affected virtual machine 

2. Setup the environment variables and use the Azure CLI or Azure Cloud Shell ( Bash ) to perform the password reset

```
  AZ_RESOURCE_GROUP=""
  AZ_VM_NAME=""
  AZ_ADMIN_USER=""
  AZ_MSADMIN_PASS=""

  az vm user update -u $AZ_ADMIN_USER -p $AZ_MSADMIN_PASS -g $AZ_RESOURCE_GROUP -n $AZ_VM_NAME
```

3. Try to access the virtual machine using ssh

Note that you can also do a password reset from the Azure Portal going to "Reset Password" on the virtual machine dashboard and you also have the option to change the public keys for user authentication.

Please refer to the this document for further details: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest#az_vm_user_update)

### Steps to remove the password from a user account on Linux ( requires a rescue VM, no WALinuxAgent Required )

1. Setup a rescue vm and attach a copy of the Cx OS disk to it as a data disk.

```
  AZ_RESOURCE_GROUP=""
  AZ_VM_NAME=""
  AZ_ADMIN_USER=""
  AZ_MSADMIN_PASS=""

  az vm repair create -g $AZ_RESOURCE_GROUP -n $AZ_VM_NAME --repair-username $AZ_ADMIN_USER --repair-password "$AZ_MSADMIN_PASS" --verbose
```

Check [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest) for further details

2. Mount the root file system on the data disk on /rescue

```
  # You need to execute the commands below as the root user
  sudo -i

  # Identify the device name of the data disk attached to the VM using lsblk
  lsblk

  # Mount the OS disk attached as a data disk to the rescue VM
  mkdir /rescue
  mount /dev/sdc1 /rescue

  # [OPTIONAL] if the output from lsblk shows that the root file system is located on a logical volume, then you need to mount that logical volume instead
  mount /dev/rootvg/rootlv /rescue

  # Make sure password authentication is enabled on the OpenSSH server if you will attempt to login to the server using ssh and password authentication.
  egrep "^PasswordAuthentication" /rescue/etc/ssh/sshd_config

  # Enter the user name, it can be the name of the admin user or "root"
  USER_NAME="root"

  # Make a backup of the current /rescue/etc/shadow
  cp -av /rescue/etc/shadow /rescue/etc/shadow.$( date '+%Y.%m.%d_%H.%M.%S' )

  # Remove the root password from the file /rescue/etc/shadow
  sed -r -i.azbackup "s/${USER_NAME}\:[^\:]*/${USER_NAME}\:/g" /rescue/etc/shadow

  # Compare the differences between the password files
  diff /rescue/etc/shadow /rescue/etc/shadow.azbackup

  # Make sure to sync any pending I/O operations on the file system
  sync 

  # And umount the root files system before removing the disk
  umount /rescue

```

3. Unmount the root file system and de-attach the OS disk copy from the rescue VM.

`umount /rescue`

4. Swap the OS disks on the customer virtual machine.

`az vm repair restore -g $AZ_RESOURCE_GROUP -n $AZ_VM_NAME --verbose
`

5. Enter the server from the serial console ( preferable ) or using ssh with the user account where we removed the password, the new password is "empty", so all you have to do is hit enter when the system asks for user password.

5.1 If the serial console is not enabled on the virtual machine you will have to attach a storage account to it to enable boot diagnostics.

6. Use the "`passwd`" command to setup a new password for the user account intermediately.

7. Try to access the server using ssh and enter the new password you setup from the serial console.

Please take into consideration that these methods have been tested using Linux distributions officially endorsed by Azure on the link below:

  [Endorsed Linux distributions on Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros)
  
If a customer is experiencing problems with a network appliance then it's necessary to reach out to the appliance vendor first to get instructions about how to perform a password reset safely, since changing a marketplace appliance's user account settings from a rescue VM might fail or break-up the setup of the appliance.

When the customer is using a customized virtual machine image based on one of the endorsed OS distribution you might proceed.

An **ALWAYS** make sure to create an snapshot of the OS disk before attempting to reset any user password on an OS disk.

**Comment by carlosporter** [comment]
**Other advanced techniques to reset a user password on Linux ( don't attempt any of them unless you know what you're doing ):**

- Try to boot the OS on single user mode to access the rescue shell and reset the admin password to enter the server using the serial console from the Azure Portal.

- Update /rescue/etc/shadow using crypt(3) libc function to reset a user password.

- Use the command "chroot" to change root password on a root file system on a data disk.

- Use systemd-containerd to create a container and boot the OS disk in rescue mode.

- Setup QEMU on the rescue VM to start a nested virtual machine on Linux using  the data disk attached as OS disk.

- Use Hyper-V to create a virtual machine that boots from a Live Rescue CD to boot and update the OS configuration on the data disk attached to the nested VM.

**Comment by genlin** [comment]
@carlosporter, I will forward your feedback to your engineers and investigate the problem.
