### ISSUE TITLE
Command fail to detect the new resources created

### ISSUE THREAD

**Issue by rubenz91** [MicrosoftDocs/SupportArticles-docs#240]
I went to try it on a VM that failed but it fails to detect the VM on the new resource group with the random named generated even the last step give me the same error of not being able to found the VM.

Do Im missing anything from steps?

Note: I went ahead and run it locally from the VM it finalized now the last part is the one Im looking to implement.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c86f8d-4f70-e909-6b8f-321cb018532e
* Version Independent ID: 32044cf7-cf37-b4e9-0ebf-47df90de7cda
* Content: [Repair a Windows VM by using the Azure Virtual Machine repair commands - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands)
* Content Source: [support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by genlin** [comment]
Run "az vm list" to double check the VM's resource group and name. If the repair command still not work, I would suggest you contact Azure support for assistance.
