### ISSUE TITLE
Missing Letter in Table of Contents link

### ISSUE THREAD

**Issue by dipstar** [MicrosoftDocs/SupportArticles-docs#243]
The Table of Contents has the letter 'e' missing for the following:

https://docs.microsoft.com/en-us/troubleshoot/windows-server/deployment/use-recovery-console-not-start

![image](https://user-images.githubusercontent.com/26741152/129365389-824ffd1e-c885-4ea7-bfce-e243b4051fef.png)

**Comment by dipstar** [comment]
I have submitted a Pull request
https://github.com/MicrosoftDocs/SupportArticles-docs/pull/244

**Comment by Deland-Han** [comment]
Thank you. @dipstar, I have merged the pull request.
