### ISSUE TITLE
Resource group not found

### ISSUE THREAD

**Issue by prafulbusa** [MicrosoftDocs/SupportArticles-docs#251]
[We tried to run a command in cloudshell/powershell to create a rescueVM but it didn't find the resource group]

az vm repair create -g brokenvmRG -n brokenVMname --repair-username username --repair-password 'mypassword' --enable-nested --verbose

Tried to create a VM with Nested enabled but it throws different errors lately. 
First resource group not found, and then "error_message": "'NoneType' object has no attribute 'uri'", 
asking to try with --debug flag but no use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c86f8d-4f70-e909-6b8f-321cb018532e
* Version Independent ID: 32044cf7-cf37-b4e9-0ebf-47df90de7cda
* Content: [Repair a Windows VM by using the Azure Virtual Machine repair commands - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands)
* Content Source: [support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-miegge**

**Comment by v-miegge** [comment]
The content originator has been alerted and will research a solution to this issue. Thanks.

**Comment by JarrettRenshaw** [comment]
Hi Praful, the content example is correct, so our engineers have filed an issue to look into the azure vm repair CLI for a possible issue. Since the example command is correct, we will not make any changes to the article. Thanks for bringing this to our attention.
