### ISSUE TITLE
What if...

### ISSUE THREAD

**Issue by rst170114** [MicrosoftDocs/SupportArticles-docs#252]
What will happen if you do an inplace update on e.g. Windows Server 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@rst170114, It may possibly cause the VM stops working or stuck in the upgrade process. If you are planning to upgrade your VM, I suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for assistance.

**Comment by genlin** [comment]
#please-close
