### ISSUE TITLE
Process Not Supported

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/SupportArticles-docs#256]
On step 1 it says to go to https://docs.microsoft.com/en-us/previous-versions/azure/jj151815(v=azure.100)?redirectedfrom=MSDN for powershell AD connect steps, but the link says it is no long maintained, and the Microsoft download site mentioned in the site says the file has been removed.  Is there a different process now for doing the steps in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf613b2-8672-1466-5012-fbda47f01b52
* Version Independent ID: 0a937f6e-2c06-cfd1-8285-1a3bede9a510
* Content: [Can't manage or remove objects that were synchronized through the Azure Active Directory Sync tool - Active Directory](https://docs.microsoft.com/en-US/troubleshoot/azure/active-directory/cannot-manage-objects)
* Content Source: [support/azure/active-directory/cannot-manage-objects.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/cannot-manage-objects.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ rconiv, Thanks for the feedback, I will check and update the steps.

**Comment by genlin** [comment]
@rconiv. You can use method to install MSOnline module:

1. If you're not running Windows 10, install the 64-bit version of the Microsoft Online Services Sign-in Assistant: [Microsoft Online Services Sign-in Assistant for IT Professionals RTW](https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_32bit.msi).
1. Install the Microsoft Azure Active Directory Module for Windows PowerShell:

    1. Open an elevated Windows PowerShell command prompt (run Windows PowerShell as an administrator).
   1. Run the `Install-Module MSOnline` command.

I also updated the article with the next steps.

**Comment by rconiv** [comment]
Thank you, just to ask, is this expected?  It is giving an untrusted repository message when doing step 2.

![image](https://user-images.githubusercontent.com/72881999/131363429-d41cb637-e455-49df-af2c-7ca63af6edc4.png)
