### ISSUE TITLE
duplicate-keys-sys-syscommittab-table.md 

### ISSUE THREAD

**Issue by alimdogan** [MicrosoftDocs/SupportArticles-docs#266]
Hi, 
I think we can add 2 more items.  
1. In SQL Server Configuration Manager, in the left pane, click SQL Server Services.
2 . In the results pane, right-click SQL Server (MSSQLServer) or a named instance, and then click Restart.

**Comment by HaiyingYu** [comment]
Hi @alimdogan , thanks for your suggestion. We will update the content to make it more clear to understand.
