### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by CzMcClane** [MicrosoftDocs/SupportArticles-docs#269]
[Enter feedback here]
Please note there is an error on the page, this;
# Get ID of the OS disk that is repaired.
$myNewOSDiskid=(az vm show -g $resourceGroup -n $osDisk --query id -o tsv)

should be:
# Get ID of the OS disk that is repaired.
$myNewOSDiskid=(az disk show -g $resourceGroup -n $osDisk --query id -o tsv)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d51ddb7-1902-608e-fb1d-fc4857a626f4
* Version Independent ID: 3d68ede8-e8c3-9a1a-3050-0a3c80d6ee32
* Content: [Use a Linux troubleshooting VM with the Azure CLI - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-recovery-disks-linux)
* Content Source: [support/azure/virtual-machines/troubleshoot-recovery-disks-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-recovery-disks-linux.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@CzMcClane Thanks for pointing out the problem. I will fix it.
