### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by CMC-Spilman** [MicrosoftDocs/SupportArticles-docs#271]
http://aka.ms/hrcsync - link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a610f434-e238-d32a-9589-e2b9cbe184c3
* Version Independent ID: e9a881b7-8fa2-1574-391d-7be1a6e74443
* Content: [How to troubleshoot password synchronization when using an Azure AD sync appliance - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/troubleshoot-pwd-sync)
* Content Source: [support/azure/active-directory/troubleshoot-pwd-sync.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/troubleshoot-pwd-sync.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@CMC-Spilman  Thanks for the feedback. I will removed the link. The troubleshoot tool is integrated with Azure AD Connect. For more information, see 

https://docs.microsoft.com/en-us/azure/active-directory/hybrid/tshoot-connect-objectsync
