### ISSUE TITLE
Step 2: Set correct permissions on the RDP self-signed certificate

### ISSUE THREAD

**Issue by melvinduc** [MicrosoftDocs/SupportArticles-docs#272]
[Enter feedback here]
Please change 

$RdpCertThumbprint = 'Cert:\LocalMachine\Remote Desktop\'+((Get-ChildItem -Path 'Cert:\LocalMachine\Remote Desktop\').thumbprint)

To

$RdpCertThumbprint = 'Cert:\LocalMachine\Remote Desktop\'+(Get-ChildItem -Path 'Cert:\LocalMachine\Remote Desktop\').thumbprint

For some reason the original code snippet does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa9f4d1f-94a7-2b7a-50f6-585fce5a322b
* Version Independent ID: c2a771cd-399e-c940-bc6e-422f0546ec7c
* Content: [An internal error occurs when you make an RDP connection to Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-internal-error#symptoms)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-internal-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-internal-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@melvinduc, Thanks for the feedback. I just did a test. Both commands work in Azure Serial Console.
