### ISSUE TITLE
c-runtime-packages-desktop-bridge is linking to AppX packages rather than MSIX packages.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [MicrosoftDocs/SupportArticles-docs#275]
http://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge (http://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/cpp/c-runtime-packages-desktop-bridge.md) is containing multiple links to AppX packages. These should be re-packaged as MSIX packages.

**Comment by HaiyingYu** [comment]
@BEEDELLROKEJULIANLOCKHART Thanks for the suggestion! From the [Supported platforms](https://docs.microsoft.com/windows/msix/supported-platforms), we can see that there're more limitations for MSIX packages. So we will keep the current download links.
Will close the issue. Thanks!

**Comment by HaiyingYu** [comment]
Thank you for sharing your thoughts, @BEEDELLROKEJULIANLOCKHART ! We may need further investigations and will discuss with the team. Will keep you posted.

**Comment by HaiyingYu** [comment]
Hi @BEEDELLROKEJULIANLOCKHART, thanks for waiting. Here're some words from our engineer:

> We don’t have plans to switch to MSIX. We will keep the appx ones, as long as they’re supported, to avoid disrupting anyone depending on them.
> Vclibs packages are primarily distributed via the store. We’ve made them available for download for very limited use cases, specifically offline scenarios, and Windows Sandbox. However, most developers don’t need to download them. Instead, they reference the vclibs packages in their manifest as noted in the linked doc page.

Hope this can explain why we keep the appx packages in the article.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/MicrosoftDocs/SupportArticles-docs/issues/275#issuecomment-922167307

Although your rationale has been communicated well, and is reasonable, I am not able to agree that this decision is ideal, because one of the reasons that Microsoft's new technologies are so slowly converted to comparatively to competitors such as Apple's is because Microsoft does not use them often. Therefore, although compatibility is helpful short-term, it always does become detrimental quickly.

Regardless, my opinion is not your policy, so I shall close this. I am thankful for your assistance.
