### ISSUE TITLE
Intune app installation error reference - two errors have no possible causes listed

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/SupportArticles-docs#278]
Errors 0x80073CF0 and 0x80073CF3 in page [Intune app installation error reference](https://docs.microsoft.com/en-us/troubleshoot/mem/intune/app-install-error-codes?source=docs) both have text saying "possible causes:" but then list nothing. Can this please be filled in?
![image](https://user-images.githubusercontent.com/6205899/132544748-cdd082af-82fa-4878-b3ea-d8d5cdf77fa7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* Content: [Intune app installation error reference](https://docs.microsoft.com/en-us/troubleshoot/mem/intune/app-install-error-codes?source=docs)
* Content Source: [docs/support/mem/intune/app-install-error-codes.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/mem/intune/app-install-error-codes.md)
* GitHub Login: @helenclu @rogersoMS

**Comment by helenclu** [comment]
Confirmed with the original author that "Possible causes" was entered by mistake. The error messages are detailed enough.
