### ISSUE TITLE
the person who initiated the action is the user of the device

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/SupportArticles-docs#290]
**If you don't see an entry, it means the person who initiated the action is the user of the device. They used the Company Portal app or portal.manage.microsoft.com to perform the action.**

Is this because of privacy laws? No information as to *why* the user is not listed if they are the user of the device.

**Comment by helenclu** [comment]
Per response from our PM: This is the current design of the product. Please feel free to work with your Microsoft account team if you would like to submit a design change request.
