### ISSUE TITLE
Undisclosed limitation: Same region required for storage account.

### ISSUE THREAD

**Issue by timpeyton** [MicrosoftDocs/SupportArticles-docs#292]
Through some experimentation, I realized that you cannot use a storage account in a different region for Boot Diagnostics, and by proxy, the serial console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4dfc75-25a4-ae83-8d6a-00f267bf85b9
* Version Independent ID: faa41c37-7b66-671b-09ca-3fb076f701e3
* Content: [Azure Serial Console - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-overview)
* Content Source: [support/azure/virtual-machines/serial-console-overview.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-overview.md)
* Service: **virtual-machines**
* GitHub Login: @asinn826
* Microsoft Alias: **alsin**

**Comment by genlin** [comment]
@timpeyton You are right. The custom storage account that is in the same region as your VM and accessible from all networks. I will add this info into the article.
