### ISSUE TITLE
What if the OS is 2019? will it support the Chef extension.

### ISSUE THREAD

**Issue by prafulbusa** [MicrosoftDocs/SupportArticles-docs#306]
[ What if the OS is 2019? will it support ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d60bc290-92c2-da24-fe4c-dac3801dfe10
* Version Independent ID: 0c3ce3ef-d9c9-e5ff-3c61-121f8178baeb
* Content: [Azure Extension Supported Operating Systems - Virtual Machines](https://docs.microsoft.com/en-US/troubleshoot/azure/virtual-machines/extension-supported-os)
* Content Source: [support/azure/virtual-machines/extension-supported-os.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/extension-supported-os.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@prafulbusa, Thanks for the question. Windows server 2019 should support most of the Azure extensions.
