### ISSUE TITLE
Azure VM Inspector Tool and the Role

### ISSUE THREAD

**Issue by techiechap** [MicrosoftDocs/SupportArticles-docs#326]
[The document explains a lot about the VM Inspector tool, but it does not give the steps to enable VM inspector role nor it gives any details about the registering the preview, The author says "Get access to VM Inspector
A user with Owner-level access must grant access to VM Inspector before diagnostics can be run on the VM. The VM Inspector needs the Disk Backup Reader role at minimum to perform disk inspection against the managed OS disk on your VM"
the question comes Is this built in Role, Do i need to create custom role ? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc7981e-7751-d5c5-ce64-915d0cd63db7
* Version Independent ID: 2d6748a7-2224-a886-d7c0-775aad2b7344
* Content: [VM Inspector for Azure Virtual Machines (Preview) - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/vm-inspector-azure-virtual-machines)
* Content Source: [support/azure/virtual-machines/vm-inspector-azure-virtual-machines.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/vm-inspector-azure-virtual-machines.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **chelche**

**Comment by genlin** [comment]
@techiechap, If the VM is in the [supported regions](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/vm-inspector-azure-virtual-machines#supported-regions), there will be an" VM inspector" button under the **support + troubleshoot** section of the VM page. If the button is not available, please contact vminspector@microsoft.com.
