### ISSUE TITLE
Dynamics 365 CE support

### ISSUE THREAD

**Issue by ToshiakiKa** [MicrosoftDocs/SupportArticles-docs#330]
[Enter feedback here]
Please add Dynamics CRM / 365 CE server support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b703446-c838-fd33-09fe-1df826399931
* Version Independent ID: ff85d0c9-ecb0-987b-7b4c-fa252a93c55b
* Content: [Microsoft server software support for Microsoft Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/server-software-support)
* Content Source: [support/azure/virtual-machines/server-software-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/server-software-support.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by ToshiakiKa** [comment]
Any update?

**Comment by genlin** [comment]
@ToshiakiKa,  The following products are supported in Azure VMs. I will update the article to add this information. Thank you.

- CRM 2015
- CRM 2016
- Dynamics 365 Server Version 9.1 and later versions.
