### ISSUE TITLE
Syncing User Object when msExchHideFromAddressLists is True

### ISSUE THREAD

**Issue by SelfRando** [MicrosoftDocs/SupportArticles-docs#331]
The article states the following AD Sync exclusion:

     Condition of attribute when synchronization fails = msExchHideFromAddressLists = Is set to "True"

This implies that if I set msExchHideFromAddressLists for a user to True then the user object will not replicate and therefore the change will not be visible in Exchange Online.

However this is not the case - setting msExchHideFromAddressLists  for a user generally does result in the "Hide from Address Lists" flag for the user mailbox in the Exchange Admin Centre being set to True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cce2b95-ed72-3a30-22b0-b1df507e41da
* Version Independent ID: 943a0f77-1fda-18f8-2dc4-a47b82d3db59
* Content: [One or more objects don't sync when the Azure Active Directory Sync tool is used - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/objects-dont-sync-ad-sync-tool?source=docs)
* Content Source: [support/azure/active-directory/objects-dont-sync-ad-sync-tool.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/objects-dont-sync-ad-sync-tool.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@SelfRando, Thanks for the comment. I think you are right. The msExchHideFromAddressLists value cannot be used to exclude the user object during replication.  I will double check with our engineers.
