### ISSUE TITLE
Incorrect definition of the SFC /offbootdir parameters

### ISSUE THREAD

**Issue by ringoc** [MicrosoftDocs/SupportArticles-docs#335]
Under heading Fix any OS Corruption, it is not accurate to say /offbootdir is the boot volume of the Repair VM. 
https://docs.microsoft.com/en-au/troubleshoot/azure/virtual-machines/troubleshoot-guide-critical-process-died#fix-any-os-corruption

  ```
Run the following System File Checker (SFC) command:
  
sfc /scannow /offbootdir=<BOOT DISK DRIVE>:\ /offwindir=<BROKEN DISK DRIVE>:\windows
  
Where < BOOT DISK DRIVE > is the boot volume of the Repair VM (typically "C:") and < BROKEN DISK DRIVE > will be the drive letter for the attached disk from the broken VM. Replace the greater than / less than symbols as well as the text contained within them, e.g. "< text here >", with the appropriate letter.
```

According to this specification page, it refer to boot volume of the offline disk. 
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sfc#parameters

![image](https://user-images.githubusercontent.com/202669/138819988-37c6e171-84e4-49f3-98d2-7ee2e1fb325c.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700fbd58-cd7c-ba2a-f740-6b5d23560c31
* Version Independent ID: e8f342cb-fb15-1317-9f97-4e28cfe2a3cc
* Content: [Windows stop error - - Virtual Machines](https://docs.microsoft.com/en-au/troubleshoot/azure/virtual-machines/troubleshoot-guide-critical-process-died#fix-any-os-corruption)
* Content Source: [support/azure/virtual-machines/troubleshoot-guide-critical-process-died.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-guide-critical-process-died.md)
* Service: **virtual-machines**
* GitHub Login: @v-miegge
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ringoc Thanks for the feedback. You are right. It should be the boot volume of the broken VM that we attached to the repair VM. I will update the article.
