### ISSUE TITLE
Command Verification

### ISSUE THREAD

**Issue by camaier** [MicrosoftDocs/SupportArticles-docs#336]
[Enter feedback here]
I was working with Sebastian from the Windows team and the Cx and we were following this document, Troubleshooting Windows Azure Guest Agent. We came to step 8, where you run the command, msiexec.exe /i c:\VMAgentMSI\WindowsAzureVmAgent.2.7.<version>.fre.msi /quiet /L*v c:\VMAgentMSI\msiexec.log, and found that it did not work on the Cx’s VM,  Windows Server 2012 R2 Standard, or my own personal VM Windows Server 2016 Datacenter.

We need the validity of that command checked and corrected if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95825442-ec08-fcdd-76bd-cc0694b6b913
* Version Independent ID: 11a97acc-d077-3bac-9411-8199bd98b255
* Content: [Troubleshooting Windows Azure Guest Agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent)
* Content Source: [support/azure/virtual-machines/windows-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/windows-azure-guest-agent.md)
* Service: **virtual-machines**
* GitHub Login: @dkdiksha
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@camaier, The command usually fails because the specified path or file name that were specified for the WindowsAzureVmAgent file is incorrect.  Please double check it. For the future assistance, you can contact [Azure Support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
