### ISSUE TITLE
Generation V2 virtual machine OS Disk changes to generation V1 when repair command is executed.

### ISSUE THREAD

**Issue by adeayo21** [MicrosoftDocs/SupportArticles-docs#338]
When you have a problematic VM and want to use the repair command to troubleshoot. After running the repair command and accessing the repair VM to fix the Disk with the issue. You get the below error message when you want to restore and you're unable to successfully swap the fixed OS Disk. As it turns out that the Disk has been converted automatically to generation V1 and the VM itself is generation V2.

NB: Manually swapping the disk after it has been fixed does not work as well, the disk is greyed in the "Swap OS" pane.
"_swapping os disk is not supported since HyperVisor property on the OSDISK and the VM do not match. please make sure the Hypervisor property on the OSDisk is HyperVisor Generation V2_"
![image](https://user-images.githubusercontent.com/81052718/139135495-ee09c98a-1914-4e7e-9856-f2460c935165.png)

Also to note, the repair VM that is created comes up in generation V1 instead of mirroring the source VM which is generation V2.

![image](https://user-images.githubusercontent.com/81052718/139138403-e4e85a7d-1166-4e02-8fec-c8bcda3c1dba.png)

**Source VM is shown below**

![image](https://user-images.githubusercontent.com/81052718/139138539-bbbd9555-6f7e-4fd2-852a-545c8088231d.png)

**Fixed OS Disk**
![image](https://user-images.githubusercontent.com/81052718/139138666-5d4087bf-3643-4f7f-bd29-a47f23d8918e.png)

Looks like the Repair command doesnt take into consideration the Hypervisor Generation of the VM.

The workaround to this issue is to manually create the Repair/Rescue VM, take a copy of the problematic VM and attach it manually. This definitely defeats the purpose of having a repair command to make it easier in the first place.

**Comment by genlin** [comment]
@adeayo21 Thanks for  reporting the issue. I will forward this issue to the engineer team who created the Repair command.

**Comment by genlin** [comment]
@adeayo21 I was told that this is a known issue and will be addressed in a future release of tool. Thanks.
