### ISSUE TITLE
Issue running listed PS script

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/SupportArticles-docs#344]
When I run the following, I get this.  Wondering if there is a task that needs to be run first, that needs to be mentioned to get this to run?

PS C:\Windows\system32> (Get-AzureADDevice -all $true |  Where-Object{($_.DeviceTrustType -eq"ServerAd") -and ($_.ProfileType -ne"RegisteredDevice") -and (-not $_.AlternativeSecurityIds)}).count

Get the following error
Get-AzureADDevice : You must call the Connect-AzureAD cmdlet before calling any other cmdlets.
At line:1 char:2
+ (Get-AzureADDevice -all $true |  Where-Object{($_.DeviceTrustType -eq ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADDevice], AadNeedAuthenticationException
    + FullyQualifiedErrorId : Microsoft.Open.Azure.AD.CommonLibrary.AadNeedAuthenticationException,Microsoft.Open.Azur
   eAD16.PowerShell.GetDevice

If I then run connect-azuread and put in my M365 info, it shows my info, then if I run the above script again, it then gives me the number of accounts that are stuck in Pending.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ff0dbf3-bd19-6943-5660-55ce5244eea8
* Version Independent ID: 9d995b49-a7eb-cdc8-de3e-ba1b68c1a1d1
* Content: [Pending devices in Azure Active Directory - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/pending-devices)
* Content Source: [support/azure/active-directory/pending-devices.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/pending-devices.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
Yes, we need to connect to AzureAD before run the command. 

If the devices are stuck in pending that means the devices didn't complete the register process. Please try the resolution provided in this article. If the problem still happen, I would suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for further assistance.

**Comment by rconiv** [comment]
For the second part, turned out, that they needed to do a reboot, or at least sign out and sign back in, so that the authentication and policies could push to finish the linking.  For the remote people, they had to make sure to be connected to the VPN.
