### ISSUE TITLE
Replace "Support + troubleshooting" with "Help" (Azure VM portal)

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/SupportArticles-docs#346]
The page says "If Azure Agent is installed and working correctly on the VM, you can use the "Reset configuration only" option under Support + troubleshooting > Reset password on the VM menu.".

I don't have a "Support + troublshooting" in my Azure portal. I do have "Help". I think the text should be updated to "Help"

Darren
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ff8485-7f5b-150e-1780-e4e2aba8c14e
* Version Independent ID: a72f60cb-69ef-52bf-e2af-bbb754595594
* Content: [Azure VM Guest OS firewall is blocking inbound traffic - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic)
* Content Source: [support/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/guest-os-firewall-blocking-inbound-traffic.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by genlin** [comment]
@dargilco Thanks for the feedback. Yes, the UI was changed recently. We will update the article.

**Comment by dargilco** [comment]
Thank you @genlin !

**Comment by genlin** [comment]
Close the issue since the articles were updated.
