### ISSUE TITLE
Please add this page to the TOC under AAD/Sign-in and Multi-factor authentication

### ISSUE THREAD

**Issue by JarrettRenshaw** [MicrosoftDocs/SupportArticles-docs#347]
This page belongs under Sign-in and Multi-factor authentication but is orphaned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ac0ee80-3164-15dc-d5e6-8fa23e6f4e91
* Version Independent ID: db5a2134-ac18-f044-cbae-d3310527f60d
* Content: [You don't receive a text or voice call that contains the verification code for Azure Active Directory Multi-Factor Authentication - Active Directory](https://review.docs.microsoft.com/en-us/troubleshoot/azure/active-directory/text-voice-call-verification-code-mfa-not-send?branch=main)
* Content Source: [support/azure/active-directory/text-voice-call-verification-code-mfa-not-send.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/text-voice-call-verification-code-mfa-not-send.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@JarrettRenshaw, I will update the TOC for this article.

**Comment by genlin** [comment]
@JarrettRenshaw, A PR has been submitted to update the TOC. I will close the issue. Thanks.
