### ISSUE TITLE
This should be a landing page

### ISSUE THREAD

**Issue by JarrettRenshaw** [MicrosoftDocs/SupportArticles-docs#348]
This page is orphaned in the TOC, should be under Active Directory (Hybrid)/Azure AD Hybrid Sync Agent Installation Issues. Or can we make it a landing page instead so as to disable the Feedback feature? This is getting 0% HRR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d015c548-a2e8-ba97-d9fb-6cbda6094ec0
* Version Independent ID: 1ff9928b-ae0a-daf5-3d3e-28eae1192f16
* Content: [Azure AD Hybrid Sync Agent Installation Issues - Welcome page - Active Directory](https://review.docs.microsoft.com/en-us/troubleshoot/azure/active-directory/azure-ad-hybrid-sync-agent-install-welcome?branch=main)
* Content Source: [support/azure/active-directory/azure-ad-hybrid-sync-agent-install-welcome.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/azure-ad-hybrid-sync-agent-install-welcome.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@JarrettRenshaw,  A PR has been submitted to update the TOC. If you have any additional comment, let's discuss it offline. Thanks.
