### ISSUE TITLE
Please add v4 to this chart

### ISSUE THREAD

**Issue by pgbfnf** [MicrosoftDocs/SupportArticles-docs#350]
[Enter feedback here]
Can you please add v4 to this chart? It's not clear if you can mix v3 and v4 in the same availability set.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c853c1-2d43-1694-08e5-5e1f16a0510f
* Version Independent ID: 9e54cc6e-a87b-64bb-96f3-9ce20290136f
* Content: [Supportability of adding Azure VMs to an existing availability set - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/virtual-machines-availability-set-supportability)
* Content Source: [support/azure/virtual-machines/virtual-machines-availability-set-supportability.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/virtual-machines-availability-set-supportability.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by genlin** [comment]
@pgbfnf  Thanks for the commend. We will update the article.

**Comment by genlin** [comment]
@pgbfnf You can use folowing service/tool to query all the supported VM for the existing availability set:

Availability Sets - List Available Sizes - REST API (Azure Compute) | Microsoft Docs

**Comment by pgbfnf** [comment]
Understood.
But if you have a chart/matrix that includes some, but not all possible options, it can be misleading.

Peter Bollwerk
Azure Cloud Engineer
Fidelity National Financial
***@***.******@***.***>
Mobile: 714-439-7128

**Comment by genlin** [comment]
@pgbfnf, I aggreed with you. I have moved the chart to a r"eference" section, and call it out that this chart just lists some commom scenarios.
