### ISSUE TITLE
Wrong Group Name Provided in KB article?

### ISSUE THREAD

**Issue by luisgiraldo** [MicrosoftDocs/SupportArticles-docs#351]
It appears the group that should be listed in this article is "ADSyncAdmins", and _**not**_ AADSyncAdmins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b43cdba1-f8cc-4577-920a-e7ed1451280f
* Version Independent ID: 0c9e52af-1b51-a91d-b767-c6de5540313d
* Content: [Error 80070005 when you run the Azure Active Directory Sync Services config wizard - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/aad-sync-services-config-wizard-error)
* Content Source: [support/azure/active-directory/aad-sync-services-config-wizard-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/aad-sync-services-config-wizard-error.md)
* Service: **active-directory**
* Technology: ****
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@luisgiraldo, Thanks for the comment. I correct the group name in the article.

**Comment by genlin** [comment]
@@luisgiraldo, A PR has been submitted to update the articles. Meantime, I will close this issue. Thanks again for your contribution.
