### ISSUE TITLE
Update Article with latest sizes that support nested Virtualization.

### ISSUE THREAD

**Issue by vinay230890** [MicrosoftDocs/SupportArticles-docs#355]
As per the article https://docs.microsoft.com/en-us/azure/virtual-machines/dv4-dsv4-series V4 sizes support nested Virtualization. However, in this article, we only see that Dv3 and Ev3 are supported. Please update the article with all the sizes that supports nested Virtualization.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3291be6-35b7-26a5-512c-9d98feff8b42
* Version Independent ID: c3849404-2043-363c-1187-fdfc41cb2594
* Content: [Troubleshoot a faulty Azure VM by using nested virtualization in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization)
* Content Source: [support/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization.md)
* Service: **virtual-machines**
* GitHub Login: @glimoli
* Microsoft Alias: **genli**

**Comment by glimoli** [comment]
@genlin Can you please update this article to include the Dv4 and Dsv4 Series?

**Comment by genlin** [comment]
@glimoli, Sure. I will create a PR to update the article.

**Comment by genlin** [comment]
@vinay230890 @@glimoli, I have updated the description. The change will be live soon. Meantime I will process to close this issue. feel free to let me know if there is are any comment or feedback.
