### ISSUE TITLE
Powershell command to change rdp port doesn't work

### ISSUE THREAD

**Issue by onmelodo** [MicrosoftDocs/SupportArticles-docs#356]
PS C:\Windows\system32> Set-ItemProperty -Path 'HKLM\SYSTEM\CurrrentControlSet\C
ontrol\Terminal Server\WinStations\RDP-Tcp' -name PortNumber -value 0xD47
Set-ItemProperty : Cannot find path
'C:\Windows\system32\HKLM\SYSTEM\CurrrentControlSet\Control\Terminal
Server\WinStations\RDP-Tcp' because it does not exist.
At line:1 char:1
+ Set-ItemProperty -Path 'HKLM\SYSTEM\CurrrentControlSet\Control\Termin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...tations\RDP-T
   cp:String) [Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetIt
   emPropertyCommand

PS C:\Windows\system32> Set-ItemProperty -Path 'HKLM\SYSTEM\CurrrentControlSet\C
ontrol\Terminal Server\WinStations\RDP-Tcp' -name PortNumber -value 3399
Set-ItemProperty : Cannot find path
'C:\Windows\system32\HKLM\SYSTEM\CurrrentControlSet\Control\Terminal
Server\WinStations\RDP-Tcp' because it does not exist.
At line:1 char:1
+ Set-ItemProperty -Path 'HKLM\SYSTEM\CurrrentControlSet\Control\Termin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...tations\RDP-T
   cp:String) [Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetIt
   emPropertyCommand

![image](https://user-images.githubusercontent.com/94621741/142426289-c7b7f566-0ba2-481a-bdef-6fda9c2ab297.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa9f4d1f-94a7-2b7a-50f6-585fce5a322b
* Version Independent ID: c2a771cd-399e-c940-bc6e-422f0546ec7c
* Content: [An internal error occurs when you make an RDP connection to Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-internal-error?WT.mc_id=Portal-Microsoft_Azure_Support)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-internal-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-internal-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@onmelodo Thanks for the feedback. I will fix the problem in this article. 

The correct command should be:

`set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name PortNumber -value 3399`
