### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by unknowndpi** [MicrosoftDocs/SupportArticles-docs#363]
[Enter feedback here]

1. Feedback now requires a github account for a Microsoft page, waste of time.
2. Script on the below page does not work, simply says 'Welcome to Microsoft Graph!' then does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=powershell)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by genlin** [comment]
@unknowndpi  Thanks for the feedbacks. You can also send the feedback by clicking the "Is this page helpful?" button in the page. It will not require a github account.

@DennisLee-DennisLee, Can you check the script issue?

**Comment by DennisLee-DennisLee** [comment]
@unknowndpi Does the script generate the following 2 files?

- "Interactive_lowTls_$tId.csv"
- "NonInteractive_lowTls_$tId.csv”

**Comment by genlin** [comment]
@unknowndpi  As we haven't heard back from you for a while, I will process to close this issue. Feel free to reopen it if the problem still exists.
