### ISSUE TITLE
Caps Lock key unexpectedly inverts characters in a remote desktop session to a Windows Server 2019 R2- based computer

### ISSUE THREAD

**Issue by nmt5878** [MicrosoftDocs/SupportArticles-docs#367]
For example, in a remote desktop session, when you open Microsoft Word, type h, turn on Caps Lock by pressing the keyboard, and then type ELLO, the word is hELLO. Then, you press the Enter key. In this situation, the hELLO in Word will be corrected to Hello automatically, and Caps Lock is turned off in the remote desktop session. However, on the client's physical keyboard, the Caps Lock light is still on, and it is still in Caps Lock On status. It is not synced with the remote desktop session Caps Lock key status.

**Comment by Deland-Han** [comment]
Hi @nmt5878, 

Thank you for your feedback. This Issue tab is for feedback about our Docs articles. For feedbacks on our products, or you need support, please post it in [Windows Server Community - IT Pros (microsoft.com)](https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/bd-p/WindowsServer) or contact our support.
