### ISSUE TITLE
Update to include reference to SQL Server 2019

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SupportArticles-docs#368]
Could this article clarify if it is still relevant for version 2019 please?

https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/mem/configmgr/sql-query-times-out-or-console-slow-performance.md

**Comment by helenclu** [comment]
So far we haven't determined whether SQL Server 2019 encounters the same issue. We'll update the article when more information becomes available.

**Comment by codaamok** [comment]
Is it reasonable to close the issue? Perhaps it's best to keep it open, as an open work item, until you've qualified whether 2019 experiences the same issue or not - that way it's not forgotten about 😄
