### ISSUE TITLE
What is the actual date of deprecation?

### ISSUE THREAD

**Issue by rockysam619** [MicrosoftDocs/SupportArticles-docs#369]
Hi, 

We have few customers who still use older TLS versions. Please let me know if some exception can be provided.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=azure-monitor)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
@rockysam619 The deprecation date was on June 30, 2021.

https://web.archive.org/web/20210331140249/https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#azure-active-directory-tls-10-tls-11-and-3des-deprecation

**Comment by DennisLee-DennisLee** [comment]
@rockysam619 Support for TLS 1.0 and 1.1 will be dropped on January 31, 2022.

[Act fast to secure your infrastructure by moving to TLS 1.2!](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/act-fast-to-secure-your-infrastructure-by-moving-to-tls-1-2/ba-p/2967457)

> Most Microsoft services, such as Microsoft 365, provide guidance on how to deprecate TLS 1.0 and 1.1. While many customers using Azure AD have already moved to TLS 1.2, we are sharing further guidance to accelerate this transition. Starting Jan. 31 2022, Azure AD will no longer support these deprecated TLS versions 1.0 and 1.1. Customers who have not moved to TLS 1.2 will be impacted since requests to Azure AD will fail.

**Comment by rockysam619** [comment]
@DennisLee-DennisLee  Thanks for the response!
One further question, does this change impact only AAD or the entire Azure Fabric?
Consider Azure VMs as IIS servers and users connect with them using login IDs(non AAD)? Would such users be impacted as well?

**Comment by Abizerh** [comment]
Azure AD based login to Azure VM is supported on "Windows Server 2019 Datacenter", "Windows 10 1809" and later. These OS platform support the use of TLS 1.2 unless disabled via registry. Azure AD login VM extension plays a role when you are using AAD creds to sign-into a windows VM on Azure, and the connections from the Azure VM to the Azure AD endpoint https://login.microsoftonline.com should be on TLS 1.2. Simply put, Azure AD login to Azure AD VM should not break based on default configuration of the VM.

**Comment by DennisLee-DennisLee** [comment]
@rockysam619 The January 31, 2022 deadline only applies to Azure AD.
