### ISSUE TITLE
Powershell commands to Reset the Remote Desktop Services configuration

### ISSUE THREAD

**Issue by joteromontes** [MicrosoftDocs/SupportArticles-docs#374]
Article: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-rdp#reset-the-remote-desktop-services-configuration-1

The command will not work on any VM if the Microsoft.Compute.VMAccessAgent is not installed on the VM.

By default this agent is not installed on any windows VM, so the documentation should make clear that you will need the extension installed before.

Furthermore even with the extension installed if you run the command it will result on one error:

COMMAND:
Set-AzVMAccessExtension -ResourceGroupName "myResoureGroup" -VMName "myVM" -Name "myVMAccess" -Location WestUS -typeHandlerVersion "2.0" -ForceRerun

ERROR:
Set-AzVMAccessExtension: Missing an argument for parameter 'ForceRerun'. Specify a parameter of type 'System.String' and try again.

So the documentation is not correct for this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcca963-7ced-fe06-6b20-51984aa31ea1
* Version Independent ID: c2c4516a-5f37-4dc3-71a9-f93abfb0465a
* Content: [Reset Remote Desktop Services or its administrator password in a Windows VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-rdp#reset-the-remote-desktop-services-configuration-1)
* Content Source: [support/azure/virtual-machines/reset-rdp.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/reset-rdp.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@joteromontes, Thanks for the comments. I agreed with you. We should add the information about the prerequisite for running the command. Will update the article,.

**Comment by genlin** [comment]
@joteromontes The [Azure VM agent](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/agent-windows) is required to run the command. When you run the `Set-AzVMAccessExtension` command that provided in the article, the Microsoft.Compute.VMAccessAgent will be install automatically. 

We need to specify $true for parameter 'ForceRerun'.

Set-AzVMAccessExtension -ResourceGroupName "myResoureGroup" -VMName "myVM" -Name "myVMAccess" -Location WestUS -typeHandlerVersion "2.0" -ForceRerun $true
