### ISSUE TITLE
The Azure Site Recovery Provider is already registered with the following identity: under the same site. Please purge the provider from Azure Site Recovery and attempt registration again

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/SupportArticles-docs#379]
Error message:
The Azure Site Recovery Provider is already registered with the following identity: under the same site. Please purge the provider from Azure Site Recovery and attempt registration again.

How to respond to this error message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9435a25d-9264-748f-abfe-f4b71db0f929
* Version Independent ID: 29edc32d-7f31-73a2-524d-e934631a6635
* Content: [Vault registration fails in Azure Site Recovery with error - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/site-recovery/vault-registration-fails)
* Content Source: [support/azure/site-recovery/vault-registration-fails.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/site-recovery/vault-registration-fails.md)
* Service: **site-recovery**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@richard-artes, I didn't see this error before. To resolve the issue quickly, I suggest you contact [Azure support](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for help.
