### ISSUE TITLE
update to your article 

### ISSUE THREAD

**Issue by MichaelHall001** [MicrosoftDocs/SupportArticles-docs#381]
I work at Microsoft in CSS customer service and support.  My customer had this issue.  We put the intermediate certs into the trusted root store on all the WAPs, then rebooted the WAPs, it made the Qualys SSL lab report come back with no errors and fixed the issue on the Android cell phones.  v-michall@microsoft.com -I work at Microsoft boii. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34544200-5b57-5aed-679a-c6d278110653
* Version Independent ID: f0b6dd83-c7ff-ef6a-6637-049e52e71e5f
* Content: [Using ADAL to authenticate from Android devices fails if additional certificate downloads are required - Active Directory](https://docs.microsoft.com/en-US/troubleshoot/azure/active-directory/adal-authenticate-android-devices-fail)
* Content Source: [support/azure/active-directory/adal-authenticate-android-devices-fail.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/adal-authenticate-android-devices-fail.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@MichaelHall001 Thanks for the feedback. I will reach you offline for improving the current solution in the article.
