### ISSUE TITLE
Please add a section regarding 32bit support for Linux

### ISSUE THREAD

**Issue by PNW-BRZ** [MicrosoftDocs/SupportArticles-docs#386]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aaf964f-63b8-c007-9724-4ab800df54a6
* Version Independent ID: 6cbdb843-b282-0cf3-ea99-153dab004ac1
* Content: [Support for 32-bit operating systems in Azure virtual machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines)
* Content Source: [support/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@PNW-BRZ, Thanks for the comment. For the supported Linux versions, please see the following article:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros
