### ISSUE TITLE
Does the proxyAddress attribute in AAD always contain the UPN as a secondary email address?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/SupportArticles-docs#387]
Is there a way for an AAD user object to NOT have the on-premises UPN as a primary OR secondary SMTP address in the proxyAddresses attribute?

I created an outbound to AAD sync rule that sets the mail and proxyAddresses attribute, but when querying AAD, the UPN is always present as the secondary SMTP address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab715116-6bb3-5328-e3d7-c19b00359cdf
* Version Independent ID: c1c5d84e-ab3c-2cda-2b7f-d9f494c5481d
* Content: [How the proxyAddresses attribute is populated in Azure AD - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/proxyaddresses-attribute-populate)
* Content Source: [support/azure/active-directory/proxyaddresses-attribute-populate.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/proxyaddresses-attribute-populate.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@LijuV-MSFT For your question, I would suggest you contact [Azure support](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for help.
