### ISSUE TITLE
Renaming a user account instructions breaks system functionality

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/SupportArticles-docs#396]
The instructions for renaming a user account provided here:

https://docs.microsoft.com/en-us/troubleshoot/windows-client/user-profiles-and-logon/renaming-user-account-not-change-profile-path

breaks system functionality - specifically, the 'winget' command (part of App Installer included with Win 10/11) no longer works. Tried running 'where winget' after renaming the user profile folder and updating profile registry key path, and it cannot be found.

There should be built-in functionality in Windows for changing the file system path to the user's profile folder.

At an absolute minimum, we should not be providing documentation/guidance that "appears" to work but results in strange breakages in other parts of the operating system. If I hadn't happened to try using winget the day after making the profile path change (i.e. if it had been a month or more before using winget), it would have taken a lot longer to identify that following the instructions in this documentation is what caused winget to no longer work / be found.

**Comment by Deland-Han** [comment]
@skeeler This article is an old article which only applies to Windows 7 Service Pack 1 and Windows Server 2008 R2 Service Pack 1.

I will add a note to the beginning of the article to warn users not to applies the solution on Windows 10 and Windows 11. Thank you for the feedback.
