### ISSUE TITLE
Bash variables declaration should not use "$"

### ISSUE THREAD

**Issue by rtorresa** [MicrosoftDocs/SupportArticles-docs#397]
Hello, 
 there is a mistake in the az-cli examples:

$subscriptionId=$(az account show --output=json | jq -r .id)

should look 
subscriptionId=$(az account show --output=json | jq -r .id)

Thank you
Regards
Roberto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cff5bf-cbe3-0a0b-f972-f0dca4c39258
* Version Independent ID: 801b467a-898d-d4d2-82d0-636aa7678752
* Content: [Enable and disable the Azure Serial Console - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-enable-disable)
* Content Source: [support/azure/virtual-machines/serial-console-enable-disable.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-enable-disable.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@rtorresa, Thanks for the feedback, I will fix the issue.

**Comment by genlin** [comment]
@rtorresa If you have any issue with the Azure Serial Console, you can also contact Azure support for assistance.

**Comment by genlin** [comment]
@rtorresa If you have any issue with seeraio cont
