### ISSUE TITLE
SSH permissions

### ISSUE THREAD

**Issue by CarlSota** [MicrosoftDocs/SupportArticles-docs#400]
Hi Team,

We have been getting some SR regarding the folder and file permissions not being set correctly:

		/home/username
		/home/username/.ssh
		/home/username/.ssh/authorized_keys

In some cases the owner of the /home/username is not even the right one.

		chmod 755 /home/username
		chmod 700 /home/username/.ssh
		chmod 600 /home/username/.ssh/authorized_keys
		cd /home
		chown username username

Related errors:

From ssh -vv:

		debug2: service_accept: ssh-userauth
		debug1: SSH2_MSG_SERVICE_ACCEPT received
		debug1: Authentications that can continue: publickey
		debug1: Next authentication method: publickey
		debug1: Trying private key: ./privateKey.pem
		debug2: we sent a publickey packet, wait for reply
		debug1: Authentications that can continue: publickey
		debug2: we did not send a packet, disable method
		debug1: No more authentication methods to try.

/var/log/auth.log

		Authentication refused: bad ownership or modes for directory /home/username

I contacted a Linux Escalation Engineer and he suggested me to share feedback on this page. I believe this can help our customers.

I am a Microsoft Support Engineer, you can contact me internally if required.

Thank you team!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72902f52-ed00-8106-dda7-a437271ccd48
* Version Independent ID: 11b2d8c9-4b3a-344a-b795-e979d3d4f31b
* Content: [Can’t SSH to Azure Linux VM because permissions are too open - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-ssh-permissions-too-open)
* Content Source: [support/azure/virtual-machines/troubleshoot-ssh-permissions-too-open.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-ssh-permissions-too-open.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@CarlSota Thanks for the feedback, I will ping you offline for this issue.
