### ISSUE TITLE
Virtual Machine resource Help section has been renamed

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/SupportArticles-docs#401]
**Troubleshoot using the Azure portal** section step 1 references the **Help** section for a VM resource, but the header text currently shown for that section in Azure (and the accompanying screenshot) is **Support + troubleshooting**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c77c28b-b389-ca75-216f-401aa52888b9
* Version Independent ID: ba147bfd-0755-b812-1d2a-4c7e12488d05
* Content: [Cannot connect with RDP to a Windows VM in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-connection)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-connection.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-connection.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@rrhkpmg Thanks for the feedback.  The heading "Support + troubleshooting" in Azure portal (https://portal.azure.com) were changed to **Help**. I will update the screenshot.
