### ISSUE TITLE
Exception calling "SecureStringToBSTR" with "1" argument(s): "Value cannot be null.

### ISSUE THREAD

**Issue by diegodct** [MicrosoftDocs/SupportArticles-docs#402]
Getting the below error when trying to run script for KEK scenarios

Exception calling "SecureStringToBSTR" with "1" argument(s): "Value cannot be null.
Parameter name: s"
At C:\Users\azureadmin\Desktop\Untitled1.ps1:62 char:1
+ $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyVau ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Cannot find an overload for "PtrToStringAuto" and the argument count: "1".
At C:\Users\azureadmin\Desktop\Untitled1.ps1:63 char:1
+ $wrappedBekSecretBase64 = [Runtime.InteropServices.Marshal]::PtrToStr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72043177-4ad8-7261-ba13-3d7b14c76a14
* Version Independent ID: a9ee0e02-325d-256e-4f20-18df23962002
* Content: [Troubleshooting BitLocker boot errors on an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-bitlocker-boot-error)
* Content Source: [support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@diegodct, The error occurs because the $keyVaultSecret is null. Please check if the -VaultName and  -Name you specified in the following command is correct. 

$keyVaultSecret = Get-AzKeyVaultSecret -VaultName $keyVaultName -Name $secretName

If there is still a problem with the script, please  contact with [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for help.

**Comment by diegodct** [comment]
Hi @genlin thank you for your answer. Then, the documentation should be corrected. In this step:

"If the Content Type value is Wrapped BEK, go to the Key Encryption Key (KEK) scenarios."  --> there is no definition of variable $keyVaultSecret
