### ISSUE TITLE
Request to add a note 

### ISSUE THREAD

**Issue by Mangaleshwar** [MicrosoftDocs/SupportArticles-docs#410]
[Enter feedback here]

The steps detailed in this document are applicable for both SLES 12 SP4/5 and SLES for SAP 12 SP4/5 VMs migration to SLES 15. But the document just mentions about SLES VMs and SLES for SAP VMs are not called out in the document. This leads to confusion among customers and our support engineers.

Hence requesting to add a note mentioned that the steps are applicable for both SLES 12 SP4/5 and SLES for SAP 12 SP4/5 VMs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: effae8d1-ac3e-6693-5cbc-e1159227e995
* Version Independent ID: febdafa4-0992-0cd5-3f8c-322ced5fc42c
* Content: [Upgrade an Azure VM with SUSE Linux Enterprise Server to SUSE 15 SP1 - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-upgrade-suse-15sp1)
* Content Source: [support/azure/virtual-machines/linux-upgrade-suse-15sp1.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-upgrade-suse-15sp1.md)
* Service: **virtual-machines**
* GitHub Login: @amkarmak
* Microsoft Alias: **arremana**

**Comment by genlin** [comment]
@Mangaleshwar Thanks for the feedback, I will confirm with the author of this article, and get back to you.

**Comment by Mangaleshwar** [comment]
@genlin Thank you for the update. I had a word with the author (arremana) as well, as we both work in the same team.

**Comment by genlin** [comment]
@Mangaleshwar Let's talk offline. I will close this issue.

**Comment by genlin** [comment]
@Mangaleshwar  The note as been added. Thanks.

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-upgrade-suse-15sp1
