### ISSUE TITLE
Single MOERA per user

### ISSUE THREAD

**Issue by ermacia91** [MicrosoftDocs/SupportArticles-docs#415]
Please, specify that there can only be 1 moera per user ProxyAddresses - this is a cx requirement.

Reach out internally if further details are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab715116-6bb3-5328-e3d7-c19b00359cdf
* Version Independent ID: c1c5d84e-ab3c-2cda-2b7f-d9f494c5481d
* Content: [How the proxyAddresses attribute is populated in Azure AD - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/proxyaddresses-attribute-populate)
* Content Source: [support/azure/active-directory/proxyaddresses-attribute-populate.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/proxyaddresses-attribute-populate.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ermacia91 Thanks for the feedback, I will reach you offline for this issue.
