### ISSUE TITLE
TLS 1.2 SSPR 

### ISSUE THREAD

**Issue by desmphil** [MicrosoftDocs/SupportArticles-docs#421]
Can you also add to this article to update the TLS 1.2
https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/unable-configure-pwd-writeback-error

TLS 1.2 for Azure AD Connect
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-tls-enforcement

**Comment by genlin** [comment]
@desmphil  Thanks for the comment. Do you mean that TLS setting will also cause password writeback error that  mentioned in https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/unable-configure-pwd-writeback-error?

**Comment by genlin** [comment]
Updated and closed the issue.
