### ISSUE TITLE
Please add mention to reboot VM after making suggested registry changes, to make them take effect.

### ISSUE THREAD

**Issue by RalphSmorra** [MicrosoftDocs/SupportArticles-docs#424]
This page showing registry changes to fix VM "access is denied" RDP error, should mention the need to restart the VM for the changes it suggests to take effect. As you know, not all registry changes require a reboot, so it shouldn't be presumed the users would know to reboot the VM to make the changes take effect. Before an unrelated reboot, I was left thinking this was yet another thing I had tried that hadn't worked even though it had. Please add a final "Restart VM to make registry changes take effect." step to the instructions. Thank you, Ralph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e8d908-7e37-7fa0-d195-c64ea061a4f3
* Version Independent ID: 47a1bcf0-cf22-36ec-ebfc-481ec78adaa3
* Content: [Access is denied error when you connect to an Azure Windows VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-access-denied)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-access-denied.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-access-denied.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@RalphSmorra, Sorry for the inconvenience had caused. I will add the statement about reboot.

**Comment by genlin** [comment]
@@RalphSmorra A PR has been submitted to add the step. Feel free to reopen this issue if you have any other comment or suggestion. Thanks for helping to improve the document.

**Comment by RalphSmorra** [comment]
@genlin Thanks for submitting the PR for that step be added. I think it will help people.
