### ISSUE TITLE
Creating swap should not rely upon fallocate

### ISSUE THREAD

**Issue by thiruma0203** [MicrosoftDocs/SupportArticles-docs#427]
Sample script in the documentation for creating swap calls fallocate to create a file for swap. However, it appears that there are several occasions fallocate does not create a file properly in purpose of using for swap.

 #!/bin/sh
if [ ! -f '/mnt/swapfile' ]; then
**fallocate --length 2GiB /mnt/swapfile**
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile
swapon -a
else
swapon /mnt/swapfile; fi

https://unix.stackexchange.com/questions/599949/swapfile-swapon-invalid-argument

I wonder method like `dd if=/dev/zero of=/mnt/swapfile bs=1M count=2048` should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01ee0e4f-fb6a-2a3f-b30e-e2bf4c0b383c
* Version Independent ID: 6f0185df-55bd-c07b-8380-93b9e9428638
* Content: [Swap file is not re-created after a Linux VM restarts - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart)
* Content Source: [support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md)
* Service: **virtual-machines**
* GitHub Login: @srijang
* Microsoft Alias: **srijangupta**

**Comment by genlin** [comment]
@thiruma0203, Thanks for the feedback. I will check with our engineer and get back to you.

**Comment by genlin** [comment]
@thiruma0203, The article was updated based on your comments. Thanks for the contribution.

**Comment by genlin** [comment]
@thiruma0203, The article was updated based on your comments. Thanks for the contribution.
