### ISSUE TITLE
Restrict AD RPC traffic to specific port still supported for Windows Server 2016 and higher?

### ISSUE THREAD

**Issue by TaekeK** [MicrosoftDocs/SupportArticles-docs#428]
Is the method to restrict Active Directory RPC traffic to a specific port still supported for Windows Server 2016 and higher? The article (SupportArticles-docs/support/windows-server/identity/restrict-ad-rpc-traffic-to-specific-port.md ) only mentions Windows Server 2012 R2.

**Comment by Deland-Han** [comment]
Thanks. @TaekeK. I am investigating this and will reply later.

**Comment by Deland-Han** [comment]
I confirmed that this article applies to later versions of Windows Server. I have edited the article. Thank you for the feedback.
