### ISSUE TITLE
Amazingly simple video explanation

### ISSUE THREAD

**Issue by agwtahoe** [MicrosoftDocs/SupportArticles-docs#439]
Thank you, Microsoft!

Super easy fix and the explainer video was fantastic. I am very impressed. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d2d805-50e5-3494-6388-2497d973a080
* Version Independent ID: 63166523-8137-7d97-045f-811f884bb991
* Content: [Error AADSTS50011 - The reply URL specified in the request does not match the reply URLs configured for the application. - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-reply-url-mismatch)
* Content Source: [support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS50011-reply-url-mismatch.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@agwtahoe Thanks for your feedback. I am very glad that you like our works.
