### ISSUE TITLE
clarify default ports for WinRM

### ISSUE THREAD

**Issue by JustinWebDev** [MicrosoftDocs/SupportArticles-docs#440]
It says:
`By default WinRM HTTP uses port 80. On Windows 7 and higher, the default port is 5985.

By default WinRM HTTPS uses port 443. On Windows 7 and higher, the default port is 5986.`

This is double-talk.  If older OS versions had a diff port, then specify it.

**Comment by Deland-Han** [comment]
@JustinWebDev For older OS, it uses port 80 and 443. I have edited the article to make it more clear. Thank you for your feedback.

**Comment by JustinWebDev** [comment]
This is somewhat better but still not proper.  Still a 'default' is given w/o context.  Since default is OS-dependent, you should simply say:
For Windows Vista (??or whatever??), WinRM HTTP uses port 80, and WinRM HTTPS uses port 443. On Windows 7 and later versions, WinRM HTTP uses **_pot_** 5985, WinRM HTTPS uses port 5986.


For the record of the page being referenced:  https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/configure-winrm-for-https

**Comment by Deland-Han** [comment]
@JustinWebDev Thank you. I agree. I would modify this sentence to the following.

> By default, on Windows 7 and later versions, WinRM HTTP uses pot 5985 and WinRM HTTPS uses port 5986. On earlier versions of Windows, WinRM HTTP uses port 80 and WinRM HTTPS uses port 443.

**Comment by JustinWebDev** [comment]
@Deland-Han , fix the "pot" typo and you'll be good.

**Comment by Deland-Han** [comment]
Great. I have corrected the typo and updated the article. Thank you for your feedback.

**Comment by JustinWebDev** [comment]
Thank you.
