### ISSUE TITLE
VM boot diagnostics settings does not have details about managed boot diagnostics storage account

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/SupportArticles-docs#441]
This documentation does not mention new managed storage account option at all.

Compare with: https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#enable-managed-boot-diagnostics

TBG this documentation probably should contain only windows-specific settings and other settings should be documented in the linked article only to decrease update burden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e04cf5d-6a98-6c34-f7bf-cfb67678f860
* Version Independent ID: e0fc8961-ac60-37d9-3ec5-8288a203f17b
* Content: [Boot diagnostics for VMs in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-diagnostics)
* Content Source: [support/azure/virtual-machines/boot-diagnostics.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/boot-diagnostics.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by genlin** [comment]
@jikuja  Thanks for the feedback. We will update the article to reflect new option.

**Comment by jikuja** [comment]
The ARM template section is still kind of outdated: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-diagnostics#deploying-from-an-azure-resource-manager-template

E.g. `The latest version is "2018-10-01".` and no mentions how to enable managed storage with ARM and no link to other documentation.
