### ISSUE TITLE
The output generated by this report does not match what we see in Service Trust Portal TLS DeprecationReport

### ISSUE THREAD

**Issue by ivratche** [MicrosoftDocs/SupportArticles-docs#442]
[Enter feedback here]
We thought we had a pretty good handle on hunting down legacy TLS based on the instructions from this article (going after the sign-in logs). However, when we compared where we stand today to the report generated by https://servicetrust.microsoft.com/AdminPage/TlsDeprecationReport/Download, we see a SIGNIFICANT DIFFERENCE. Can someone please comment on this and how holistic of a few are we really getting from hunting down legacy TLS in the sign-in logs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=azure-monitor#overview-of-new-telemetry-in-the-sign-in-logs)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Will handle this issue offline...
