### ISSUE TITLE
Two questions need to be answered

### ISSUE THREAD

**Issue by HudsonWan** [MicrosoftDocs/SupportArticles-docs#443]
Hi,
1. Always ON VPN (the RRAS component) is officially not supported on Azure VMs.  Has this guidance changed, or can Microsoft advise what specific component of RRAS is not supported (https://docs.microsoft.com/en-US/troubleshoot/azure/virtual-machines/server-software-support)

2.  If we instead use Azure P2S VPN gateway:
a. Can we generate/issue on premise Certificate Authority certificates to machine and have that work so they can be revokved
b. Can the P2S VPN be configured for prelogin (i.e. before user login)
c. Can it be configured AlwaysOn-like capability i.e. auto connect based on DNS or hostname dependencies

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b703446-c838-fd33-09fe-1df826399931
* Version Independent ID: ff85d0c9-ecb0-987b-7b4c-fa252a93c55b
* Content: [Microsoft server software support for Microsoft Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-US/troubleshoot/azure/virtual-machines/server-software-support)
* Content Source: [support/azure/virtual-machines/server-software-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/server-software-support.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@HudsonWan,  All features in RRAS like Remote Access are not supported in Azure VMs. To resolve your problem more quickly, I suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for help.
