### ISSUE TITLE
Add file limitations and review permissions documentation

### ISSUE THREAD

**Issue by fborschneck** [MicrosoftDocs/SupportArticles-docs#444]
Can you review this article and add more precise information regarding : 
- file size limit
- file number limit
- file name restrictions (error if you try to upload a file when one with the same name already exists on the workspace)
- how permissions are applied (seems upload is allowed without sign in and other actions are disabled by default even when user signed in)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2957a41-0ebd-4f1e-6f9c-d4f9173d4630
* Version Independent ID: e92921f7-9899-6a70-412f-f6094e772271
* Content: [How to use Secure File Exchange to exchange files with Microsoft Support - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/secure-file-exchange-transfer-files)
* Content Source: [support/azure/general/secure-file-exchange-transfer-files.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/secure-file-exchange-transfer-files.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@fborschneck Thanks for the comments. I will check with the our engineers, and get back to you.

**Comment by genlin** [comment]
@fborschneck  Here are some questions to your answers:

- file size limit
The file size limit in Secure File Exchange is 100Gb per file. 
- file number limit
Each workspace (that linked to your support ticket) can host 1000 files.
- file name restrictions (error if you try to upload a file when one with the same name already exists on the workspace)
There is no name restriction. If the name already exist, numbers will be appended to the filename like: text.doc; text_2.doc etc
- how permissions are applied (seems upload is allowed without sign in and other actions are disabled by default even when user signed in)
- Anyone with a direct link can upload files. Other actions are only permitted if both of the following conditions are true:

   - The customer is logged in 
   - The customer is listed as a contact on the support ticket

I will also add this information to the article. Thanks for helping to improve the article.
