### ISSUE TITLE
Recommend changing the nested host to 2019 Datacenter

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#445]
Hello, team.  Wondering if we want to change the recommended nested VM host to Windows Server 2019 Datacenter?  Windows Server 2016 is now in Extended Support, so will have to change it at some point.  Also, I've seen 2016 behave strangely when trying to enable Network Address Translation (NAT) networking when working with nested VM's.  To make sure I don't run into any of those issues, I only use Windows Server 2019 as nested hosts now.  The web page below is what I've used to enable NAT and the New-NetNat and New-VMSwitch commands are usually the ones that have issues on 2016.   Thanks.  

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization#network-address-translation-nat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3291be6-35b7-26a5-512c-9d98feff8b42
* Version Independent ID: c3849404-2043-363c-1187-fdfc41cb2594
* Content: [Troubleshoot a faulty Azure VM by using nested virtualization in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization)
* Content Source: [support/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-vm-by-use-nested-virtualization.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **glimoli**

**Comment by genlin** [comment]
@mbiver Thanks for the comment. Let's discuss this problem offline.

**Comment by genlin** [comment]
@mbiver Thanks for the comment. Let's Discuss this problem offline.
