### ISSUE TITLE
AdSyncPrep.psm1 is no longer used

### ISSUE THREAD

**Issue by xcactusx** [MicrosoftDocs/SupportArticles-docs#446]
Trying to troubleshoot this exact issue (where the option is greyed out).  Following directions on this page and can't find AdSyncPrep.psm1 on my server.  Googled and found it has been removed from ADConnect because it is "no longer used".  https://dirteam.com/sander/2021/07/21/azure-ad-connect-version-2-0-3-0-is-here/   Not sure what the work around or suggested next steps are because well you don't have any.  I'm hoping I can enable from UI after installing AD admin tools, otherwise...I'm stuck.

**Comment by genlin** [comment]
@xcactusx, I suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) for assistance.

**Comment by xcactusx** [comment]
Thanks I was able to solve on my own.  However, this doesn't solve the issue that this documentation is completely out of date.  It references a fix/script that has been removed.
