### ISSUE TITLE
Contact to Han Liang

### ISSUE THREAD

**Issue by CaverGirl** [MicrosoftDocs/SupportArticles-docs#452]
Hello Han Liang!

I didn't find any way to contact you. Sorry if I do it here.
You wrote this article: https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v

Your suggestion however does not work for many as pointed out here: https://docs.microsoft.com/en-us/answers/questions/474470/disabling-hyper-v-on-windows-11.html

And here: https://stackoverflow.com/questions/70911043/hypervisor-detected-unable-to-uninstall-hyper-v-on-windows-11-windows-surface

On Microsoft Surface Pro+, Hyper-V is installed, and there seems to be no way to uninstall it.
Being able to uninstall it is crucial because some third party softwares do not allow running with Hyper-V active / installed.

Can you take a look and see if you can solve this problem? 

It should be easy to reproduce with a new Microsoft Surface Pro+.
It seems to be specific to this computer and is also pointed out in the product sheet:

<img width="960" alt="11111" src="https://user-images.githubusercontent.com/90475517/151682999-c886caae-d68b-4313-a400-869ea90685a2.png">

Thank you.

**Comment by Deland-Han** [comment]
Hi @CaverGirl, this article is an old article which applies to Windows 10 only. I have not tested it on Windows 11 so it may not work on your computer.

Basically, the article is about how to disable the Hyper-V feature. If the Hypervisor is still running when the Hyper-V feature is disabled, it could be a different issue and the solutions in this article won't help.

If you need support, please post it in [Windows Server Community - IT Pros (microsoft.com)](https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/bd-p/WindowsServer) or contact our support.
