### ISSUE TITLE
Feedback for common issue doc

### ISSUE THREAD

**Issue by eshelB** [MicrosoftDocs/SupportArticles-docs#460]
Great Resource! exactly what I was needing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f85d18c-3151-3d9c-cf93-7359cd80486f
* Version Independent ID: 1fdc5d8b-49e3-a22c-8eb8-516f96cb8473
* Content: [Out of memory error occurs in Linux Azure virtual machine - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/oom-swap-file-linux-vm)
* Content Source: [support/azure/virtual-machines/oom-swap-file-linux-vm.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/oom-swap-file-linux-vm.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@eshelB  Glad to hear that the article was helpful. Thanks for the feedback!
