### ISSUE TITLE
Active partitions are not a thing on GPT disks

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/SupportArticles-docs#464]
I made a Windows 10 20H2 gen 2 VM from an MS gallery image and it has GPT style partitions for the OS disk not MBR so when you use diskpart to try and make the partition active, diskpart displays this:

DISKPART> active

The selected disk is not a fixed MBR disk.
The ACTIVE command can only be used on fixed MBR disks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 354d0c16-52c6-5368-fe69-a481b423ddcd
* Version Independent ID: e5baecf6-a306-395c-6c6c-1496aea2b4ff
* Content: [Windows can't boot with (An operating system wasn't found) error - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/os-not-found)
* Content Source: [support/azure/virtual-machines/os-not-found.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/os-not-found.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@guyrleech, Thanks for the comments. I think if the OS partition is  mounted and accessible, we do not have to perform the step 1 that provided in the article.

**Comment by genlin** [comment]
@guyrleech, As I haven't heard back from you for a couple of weeks, I will process to close this issue. Feel free to reopen it if the problem still exists.
