### ISSUE TITLE
Additional context for other file systems

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#465]
Hello, team.  I was wondering if we might be able to add some additional context to this page relating to the other file systems and which repair tools work with those systems?  Also, we see in the examples that the file system is ext4 but then down below we see that the repair command switch to xfs_repair.   This could cause some confusion and might be helpful if we add some additional information.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b333f2b9-cc17-f9c5-3752-47bfd1085ce7
* Version Independent ID: 6c429142-399f-1d0a-6ad0-938201d6ff60
* Content: [Troubleshoot Linux VM starting issues due to file system errors - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors)
* Content Source: [support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **v-six**

**Comment by genlin** [comment]
@mbiver Thanks for the comments. You are right. The sample of the error message is confusing since the steps only apply to XFS filesystems.  I will update the article.

**Comment by genlin** [comment]
@mbiver  The article was updated. I will process to close this issue. Feel free to reopen it if there is any additional questions.
