### ISSUE TITLE
This extension is no longer deployable from the Azure Compute

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/SupportArticles-docs#468]
Specific to the installation steps.

This extension no longer exists for deployment from Azure Compute. It was replaced with Insights Performance Diagnostics. Which may install that same extension under the covers but the steps to use it are completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8562769-f387-9577-a1ce-7b003b054339
* Version Independent ID: 0ccdec3b-d6c3-1385-f77c-a7d898dd2e5e
* Content: [Azure Performance Diagnostics VM Extension for Windows - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics-vm-extension)
* Content Source: [support/azure/virtual-machines/performance-diagnostics-vm-extension.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/performance-diagnostics-vm-extension.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@wsmelton Thanks for the feedback. I will update the article to reflect the new extension.

**Comment by genlin** [comment]
@wsmelton You can still install the Azure Performance Diagnostics extension via the **Extensions + applications** blade as described in the [article](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics-vm-extension#install-the-extension).

**Comment by wsmelton** [comment]
Why close when the doc is still wrong?

![image](https://user-images.githubusercontent.com/11204251/157306646-d7b70bca-4b1d-4a4c-8242-ba1e8c45a4c2.png)

This does not exists.

**Comment by genlin** [comment]
@wsmelton  Thanks for pointing out the problem. I will update the article.

**Comment by genlin** [comment]
@wsmelton  The article is updated:

 https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics-vm-extension#install-the-extension

Thanks for helping to improve the document.
