### ISSUE TITLE
CentOS versions that support PerfInsights on Azure not up to date

### ISSUE THREAD

**Issue by MariusFlorea99** [MicrosoftDocs/SupportArticles-docs#473]
Hello, can you please update the article with newer CentOS versions that support Performance Diagnostics on Azure? The supported ones stop at 7.8, however CentOS 8.2 was released back in June 2020.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fa2432-67f8-688a-e58a-752b2cb0c2d2
* Version Independent ID: fe34017d-5f11-702f-a15c-9334294650da
* Content: [Performance diagnostics for Azure virtual machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics)
* Content Source: [support/azure/virtual-machines/performance-diagnostics.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/performance-diagnostics.md)
* Service: **virtual-machines**
* GitHub Login: @anandhms
* Microsoft Alias: **anandh**

**Comment by genlin** [comment]
@MariusFlorea99, Currently, the Azure Performance Diagnostics tool doesn't support the CentOS 7.9 and newer versions.
