### ISSUE TITLE
Why is the "OfficeHome" app (https://office.com) not listed?

### ISSUE THREAD

**Issue by mrecek** [MicrosoftDocs/SupportArticles-docs#475]
We see sign-in events in our Azure AD tenant with the Application name as "OfficeHome" and AppID as "4765445b-32c6-49b0-83e6-1d93765276ca". Apparently this is the app that shows-up when a user logs-into https://office.com. Why is this official Microsoft app not be listed on this "first-party Microsoft applications" article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e802fb-c215-598b-cf7d-b2536d3d6cfb
* Version Independent ID: 927037ea-324a-8ae5-c64e-1683d67d00b7
* Content: [Verify first-party Microsoft applications in sign-in reports - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#feedback)
* Content Source: [support/azure/active-directory/verify-first-party-apps-sign-in.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/verify-first-party-apps-sign-in.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mrecek  Thanks for the comments. The article just lists some  "first-party Microsoft applications".  To confirm if a application is from Microsoft, you can [check the AppOwnerTenantId of the application](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#verify-a-1st-party-microsoft-service-principal-through-powershell).
