### ISSUE TITLE
TLS 1.2.zip link is broken

### ISSUE THREAD

**Issue by Tovli** [MicrosoftDocs/SupportArticles-docs#484]
[Enter feedback here]
The [link](https://gallery.technet.microsoft.com/TLS-12-Support-Deployment-15c3a47b) is broken and it seems TLS 1.2 was removed from the gallery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1896cd-392e-e563-6a81-973077eabec8
* Version Independent ID: b012b7c0-82eb-720c-11f3-ff1d44b9e237
* Content: [TLS 1.2 Protocol Support Deployment Guide for Microsoft Azure Pack - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/tls-support-deployment-guide)
* Content Source: [support/azure/general/tls-support-deployment-guide.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/tls-support-deployment-guide.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Tovli  Thanks for the feedback. I will remove that method from the article.


Thomas
