### ISSUE TITLE
Build software inventory using Power BI is outdated

### ISSUE THREAD

**Issue by lemondave** [MicrosoftDocs/SupportArticles-docs#487]
https://docs.microsoft.com/en-us/troubleshoot/mem/intune/build-software-inventory-power-bi#build-the-report

The applicationInventories table referenced in this document no longer exists.  It has possibly been moved to Graph API?  

As per this change notification https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#export-underlying-discovered-apps-list-data and this message in the Intune portal. 
### MC333931
Previously communicated in MC317762 and [Intune Data Warehouse updates](https://aka.ms/app-inventory-data-warehouse), Application Inventory table in Data Warehouse is no longer supported or available in Data Warehouse.
### How this will affect your organization:
Our reporting indicates you are using the 'applicationInventory' entity in the Intune Data Warehouse. This data is no longer available in the Intune Data Warehouse.
### What you need to do to prepare:
To retrieve Application Inventory data, you will need to use the [new Application Inventory table](https://docs.microsoft.com/mem/intune/fundamentals/whats-new?WT.mc_id=Portal-Microsoft_Intune_DeviceSettings#export-underlying-discovered-apps-list-data) within the export API. Any existing code or script solutions will no longer work and will have to be re-written to download and import a file.

**Comment by helenclu** [comment]
Thank you for your feedback! The article has been archived.
