### ISSUE TITLE
nice page, please make one for memory in AKS.

### ISSUE THREAD

**Issue by porrascarlos802018** [MicrosoftDocs/SupportArticles-docs#488]
[Enter feedback here]nice page, please make one for memory in AKS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9a1c02e-775f-d7ce-1dd4-5db4fff746d0
* Version Independent ID: d488bf33-eeeb-8f7a-e8c7-689aa04e3847
* Content: [Identify the containers consuming high CPU in an AKS cluster - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/identify-high-cpu-consuming-containers-aks)
* Content Source: [support/azure/azure-kubernetes/identify-high-cpu-consuming-containers-aks.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/identify-high-cpu-consuming-containers-aks.md)
* Service: **container-service**
* GitHub Login: @ramakoni1
* Microsoft Alias: **ramakoni**

**Comment by genlin** [comment]
@porrascarlos802018, Thanks for the feedback. We will investigate and consider to add this topic to our roadmap.

**Comment by genlin** [comment]
@porrascarlos802018 We just published an article for memory in AKS:

 [Identify memory saturation in AKS clusters - Azure | Microsoft Docs](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/identify-memory-saturation-aks)
