### ISSUE TITLE
port 443 requirement for 168.63.129.16 (fabric controller)

### ISSUE THREAD

**Issue by benzbatman** [MicrosoftDocs/SupportArticles-docs#493]
This article talks about confirming that port 443 to 168.63.129.16 needs to be working as part of step 3. However, this page talks about only needing 80 and 32526 for VM agent: https://docs.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16#scope-of-ip-address-1686312916

I'm also doing some testing using test-netconnection from an Azure VM and it appears that only 80 and 32526 are working. When I inspect TransparentInstaller.log for example, I can see calls being made on https, but they are to .blob.core.windows.net instead.

Can this be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95825442-ec08-fcdd-76bd-cc0694b6b913
* Version Independent ID: 11a97acc-d077-3bac-9411-8199bd98b255
* Content: [Troubleshooting Windows Azure Guest Agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent)
* Content Source: [support/azure/virtual-machines/windows-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/windows-azure-guest-agent.md)
* Service: **virtual-machines**
* GitHub Login: @dkdiksha
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@benzbatman Thanks for the comment. It only use 80 and 32526 ports. I will correct the information in  this article.
