### ISSUE TITLE
Add operation returns "Unable to connect to the remote server"

### ISSUE THREAD

**Issue by gongarque** [MicrosoftDocs/SupportArticles-docs#496]
Dear AZURE Team, 
trying to execute the operation "Add", it replies that it is not able to connect to the remote server.
I set up the calculator API from the WSDL both in SOAP-UI and Postman and it works there perfectly. This is not happening in Azure.
Could you please indicate to me what could be wrong here? 
Thank you!

Headers are also Ok. 
SOAPAction: "http://tempuri.org/Add"

Response:

    "messages": [
        "[20220322_Add_sample.txt](https://github.com/MicrosoftDocs/SupportArticles-docs/files/8324317/20220322_Add_sample.txt)",
        "Error occured while calling backend service.",
        "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 50.62.168.5:80"
    ]
api-inspector (0.004 ms)
    {
    "configuration": {
        "api": {
            "from": "/calc",
            "to": {
                "scheme": "http",
                "host": "www.dneonline.com",
                "port": 80,
                "path": "/calculator.asmx",
                "queryString": "",
                "query": {},
                "isDefaultPort": true
            },
            "version": null,
            "revision": "1"
        },
        "operation": {
            "method": "POST",
            "uriTemplate": "/?soapAction=http://tempuri.org/Add"
        },
        "user": "-",
        "product": "-"
    }
}

**Comment by genlin** [comment]
@gongarqueIf, If your issue is specific to a use case, please contact the Azure experts on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). Alternatively, you can file an Azure support incident by going to the [Azure support](https://portal.azure.com) and select Help + support.”
