### ISSUE TITLE
Windows 10 newer versions supported. 

### ISSUE THREAD

**Issue by scstephens** [MicrosoftDocs/SupportArticles-docs#497]
Document states "Newer Windows Server images on Azure have [Special Administration Console](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc787940(v=ws.10)) (SAC) enabled by default. SAC is supported on server versions of Windows but isn't available on client versions (for example, Windows 10, Windows 8, or Windows 7"

I have verified it does now work on newer versions of Win 10. Quote from Serial Console support SME's. 
"Serial console is available for newer versions of Windows 10 that are 21h1, 20H2. It should also be available for 20h1 and 21h2, however try it out on lab."

Please update documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece99e50-9796-cbc9-23a7-421fa042e1ec
* Version Independent ID: dfc773bc-f682-c90d-f988-784cecf70a47
* Content: [Azure Serial Console for Windows - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-windows)
* Content Source: [support/azure/virtual-machines/serial-console-windows.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-windows.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@scstephens, Thanks for the feedback. We will update the article.

**Comment by genlin** [comment]
@scstephens The feature is not fully supported in Windows 10 currently. I will update this article when it is available.
