### ISSUE TITLE
Microsoft Applications: Add SharePoint Migration Tool ID

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/SupportArticles-docs#499]
Please add the [SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool) ID "fdd7719f-d61e-4592-b501-793734eb8a0e".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e802fb-c215-598b-cf7d-b2536d3d6cfb
* Version Independent ID: 927037ea-324a-8ae5-c64e-1683d67d00b7
* Content: [Verify first-party Microsoft applications in sign-in reports - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in)
* Content Source: [support/azure/active-directory/verify-first-party-apps-sign-in.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/verify-first-party-apps-sign-in.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by heinrich-ulbricht** [comment]
Source: Token generated by the SPMT
![image](https://user-images.githubusercontent.com/3469970/159926238-9fe0f320-5b96-4f33-9d64-23846bda0346.png)

**Comment by genlin** [comment]
@heinrich-ulbricht，Thanks for the feedback. The following table in this article just lists some first party Microsoft applications. We will consider to provide full list.
