### ISSUE TITLE
Unknown Device (VMBUS) in Device manager in Virtual Machine page needs update

### ISSUE THREAD

**Issue by GlenGengMicrosoft** [MicrosoftDocs/SupportArticles-docs#502]
Public document: [https://docs.microsoft.com/en-us/troubleshoot/windows-server/deployment/unknown-device-vmbus-virtual-machine#more-information](url)
Github page: [https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/deployment/unknown-device-vmbus-virtual-machine.md](url)

Issue: We have recently met cases where the customer has concerns about unknown devices shown in the device manager with more Hardware IDs than the provided ones in the public document.

The customer deployed Windows Server 2019, 2016 VM Azure VM, and recently deployed VM are having this issue.

The issued hardware IDs are: **VMBUS\{c376c1c3-d276-48d2-90a9-c04748072c60}**, and **VMBUS\{c4e5e7d1-d748-4afc-979d-683167910a55}**. 

We have consulted the product team and they are claiming that this issue is harmless and can be safely ignored.

**Comment by Deland-Han** [comment]
This issue will be addressed.
