### ISSUE TITLE
Uninstall and re-install on other (non-dc) server

### ISSUE THREAD

**Issue by rschouten97** [MicrosoftDocs/SupportArticles-docs#503]
We encountered the following issue today:
SSPR_0029: Your organization hasn't properly set up the on-premises configuration for password reset

After spending 2,5 hours with 2 guys on this issue, trying to set/correct permissions. We decided to uninstall the Azure AD Connect on our DC en install it on another member server.
Doing this had it fixed immediately, perhaps provide this as a possible solution, because it is way quicker than troubleshooting all permissions and such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad476cdc-6ee4-3472-a61d-716848959b4c
* Version Independent ID: ad476cdc-6ee4-3472-a61d-716848959b4c
* Content: [SSPR_0029 - Your organization hasn't properly set up the on-premises configuration for password reset - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/password-writeback-error-code-sspr-0029)
* Content Source: [support/azure/active-directory/password-writeback-error-code-sspr-0029.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/password-writeback-error-code-sspr-0029.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
@NuAlex What do you think about the suggestion from @rschouten97?

**Comment by DennisLee-DennisLee** [comment]
Actually you don't have to reinstall on another server. You can configure the Preferred Domain Controllers to point to another domain controller that isn't the local machine.

**Comment by DennisLee-DennisLee** [comment]
@rschouten97 We've updated the guidance in the article. Look at the [workaround](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/password-writeback-error-code-sspr-0029#workaround-target-a-different-active-directory-domain-controller) in the *AD DS Connector account doesn't have the right Active Directory permissions* section (which is now Cause 2).
