### ISSUE TITLE
Steps no longer accurage 

### ISSUE THREAD

**Issue by GiggaWatson** [MicrosoftDocs/SupportArticles-docs#510]
[Enter feedback here]
The steps to export logs may be confusing as there is no longer a "Protect" button but a "Sensitivity" button for the built in AIP client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7905b063-e543-ac6a-a84e-0ce2041176f7
* Version Independent ID: f45d959b-8cb3-9320-f862-00f4ba3fda9b
* Content: [How to troubleshoot Azure Information Protection policy issues - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/troubleshoot-aip-issues)
* Content Source: [support/azure/general/troubleshoot-aip-issues.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/troubleshoot-aip-issues.md)
* Service: **information-protection**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@GiggaWatson, Thanks for the feedback. I will update the article to reflect latest UI.
