### ISSUE TITLE
where do we run this SQL for link increase if on cloud version of Azure

### ISSUE THREAD

**Issue by dharrold3** [MicrosoftDocs/SupportArticles-docs#511]
I am needing to update the SQL in our 'collective database' so we don't keep getting the error of reached max. links for our test cases using shared steps.
Here is the resolution but I am not sure where to run this SQL when we are on the cloud version of Azure.
Thanks for your help

This is how to resolve my issue according to articles.
RESOLVE:
To fix this, run the following SQL Script on your collection database:

SQLCopy

exec prc_SetRegistryValue 1, '#\Service\WorkItemTracking\Settings\WorkItemLinksLimit\', <new link limit (eg. 2000)>
exec prc_QueryRegistry 1, '#\Service\WorkItemTracking\Settings\WorkItemLinksLimit\'
The script updates a setting that increases the maximum number of 'allowed' links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269e4080-1ea4-badd-9195-5373ea737510
* Version Independent ID: d806b15c-c99e-69c5-3d2c-48c45f293db9
* Content: [Error when you add link to work item - Azure DevOps](https://docs.microsoft.com/en-US/troubleshoot/azure/devops/error-add-link-work-item)
* Content Source: [support/azure/devops/error-add-link-work-item.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/devops/error-add-link-work-item.md)
* Service: **az-devops-project**
* GitHub Login: @ramakoni1
* Microsoft Alias: **ramakoni**

**Comment by HaiyingYu** [comment]
@dharrold3  The solution in this article only applies to on-premise TFS versions. It's not for Azure DevOps Services. Can you explain more about your question? What does the cloud version of Azure mean? Are you using Azure DevOps Services or just using Azure SQL Server?

**Comment by HaiyingYu** [comment]
This pull request has been inactive for 10 business days. Therefore, we are closing the PR. If you want to continue working on this, you can reopen it. Thank you for the contribution.
