### ISSUE TITLE
Please add steps for Linux

### ISSUE THREAD

**Issue by kegregoi** [MicrosoftDocs/SupportArticles-docs#512]
This page is great for when this issue happens for Windows, but this same symptom can happen for Linux where there are multiple IPs on a single NIC and the customer configures a secondary IP as the primary in the guestOS.

Can we please add a Linux section to this article that describes how to mitigate this for various Linux distros as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efc2e55c-a007-e1da-a0b6-00b4397e0f13
* Version Independent ID: edadbe52-9c3e-77c9-afaa-1ae9b6454f73
* Content: [No Internet access from Azure Windows VM that has multiple IP addresses - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/no-internet-access-multi-ip?source=docs)
* Content Source: [support/azure/virtual-machines/no-internet-access-multi-ip.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/no-internet-access-multi-ip.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@kegregoi  Thanks for the feedback. We will consider to add this topic into our work list.

**Comment by genlin** [comment]
@kegregoi  To resolve the problem in Linux VMs, you can follow the steps in [Add IP addresses to a Linux VM operating system](https://docs.microsoft.com/en-us/azure/virtual-network/ip-services/virtual-network-multiple-ip-addresses-portal#os-config}. I have also updated the article.
