### ISSUE TITLE
Cannot use verification options in Cause 7 on any new powershell version

### ISSUE THREAD

**Issue by rocketraman** [MicrosoftDocs/SupportArticles-docs#518]
The verification options in Cause 7 reference cmdlets that use the MsOnline service. These cmdlets do not appear to be compatible with any new Powershell versions, including those run by the cloud shell.

This is the section: https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist#cause-7-a-previously-deleted-user-name-was-re-created-by-the-home-tenant-administrator.

Attempting to connect the cmdlet results in:

```
Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

Please provide instructions that can actually be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cb4e7df-7e04-fbab-8ea6-f16e590a151d
* Version Independent ID: 6cb4e7df-7e04-fbab-8ea6-f16e590a151d
* Content: [Error AADSTS50020 - User account from identity provider does not exist in tenant - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist)
* Content Source: [support/azure/active-directory/error-code-AADSTS50020-user-account-identity-provider-does-not-exist.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS50020-user-account-identity-provider-does-not-exist.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Hi @rocketraman, thanks for providing this feedback. We're investigating the problem and will report back shortly.

**Comment by helshabini** [comment]
Document was updated with an [alternative verification option using MS Graph](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist#microsoft-graph). This issue can now be closed.
