### ISSUE TITLE
inconsistency about python support

### ISSUE THREAD

**Issue by Klaas-** [MicrosoftDocs/SupportArticles-docs#522]
Hi,
https://github.com/MicrosoftDocs/SupportArticles-docs/blame/c205ea4ef2bdfefdcb5303beddb7c359dbf75a09/support/azure/virtual-machines/how-to-use-perfInsights-linux.md#L183
states that python 3 or python 2 are supported
https://github.com/MicrosoftDocs/SupportArticles-docs/blame/c205ea4ef2bdfefdcb5303beddb7c359dbf75a09/support/azure/virtual-machines/how-to-use-perfInsights-linux.md#L206
states that python 2 is needed.

Greetings
Klaas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be09407-640a-9391-dfcf-2c508917caa7
* Version Independent ID: 0c3f9dfe-8eee-081e-8790-051871fd61c0
* Content: [How to use PerfInsights Linux in Microsoft Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/how-to-use-perfinsights-linux#known-issues)
* Content Source: [support/azure/virtual-machines/how-to-use-perfInsights-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/how-to-use-perfInsights-linux.md)
* Service: **virtual-machines**
* GitHub Login: @anandhms
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Klaas-  Thanks for the comment. I will check with our engineers, and get back to you.

**Comment by genlin** [comment]
@Klaas- Both Python 3 and Python 2 are supported. I will update the article. Thanks again for the feedback.
