### ISSUE TITLE
Rescue VM must be of the same generation as well

### ISSUE THREAD

**Issue by nicholasanderson00** [MicrosoftDocs/SupportArticles-docs#529]
Create a rescue VM of the same generation, same OS version, in same resource group (RSG) and location using managed disk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2214e4-40a3-06a3-f3d5-e306cdcd599b
* Version Independent ID: 85ae75c8-4b4e-0ddb-8654-6af59f1623fb
* Content: [Chroot environment in a Linux Rescue VM. - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/chroot-environment-linux)
* Content Source: [support/azure/virtual-machines/chroot-environment-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/chroot-environment-linux.md)
* Service: **virtual-machines**
* GitHub Login: @kailashmsft
* Microsoft Alias: **kaib**

**Comment by genlin** [comment]
@nicholasanderson00  Thanks for the feedback. We will also indicate this in the article.

**Comment by genlin** [comment]
@nicholasanderson00 The article was updated. Thanks for your contribution.@nicholasanderson00 The article was updated. Thanks for your contribution.
