### ISSUE TITLE
Scenario 4: Exchange Online license is removed

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/SupportArticles-docs#530]
"Scenario 4: Exchange Online license is removed" is not accurate. I have just made some tests in my test environment and after removing the EXO license changes are actually being made on AAD user attributes.

- created a regular on premises AD user that does not have proxyAddresses, mail and mailNickName attributes populated:

UPN: us2@contoso.com
mail: <not set>
mailNickName: <not set>
proxyAddresses: <not set>

- synced the account to AAD using AAD Connect and confirmed its creation in AAD
- assigned an Exchange Online license to the account
- confirmed with **Get-AzureADUser -SearchString "us2@contoso.com" | fl proxyaddresses,mailnickname,mail,userprinc*** that   get the following attribute values in AAD:

UPN: us2@contoso.com
mail: us2@contoso.com
mailNickName: us2
proxyAddresses: {smtp:us2@contoso.onmicrosoft.com,SMTP:us2@contoso.com}

- waited until the mailbox in Exchange Online got created (confirmed via Exchange Online Admin Center)
- removed the Exchange Online license from the user and waited for the mailbox to be disabled
- running the cmdlet **Get-AzureADUser -SearchString "us2@contoso.com" | fl proxyaddresses,mailnickname,mail,userprinc*** in PowerShell connected to Azure AD, got me these values this time around:

UPN: us2@contoso.com
mail: us2@contoso.onmicrosoft.com
mailNickName: us2
proxyAddresses: {SMTP:us2@contoso.onmicrosoft.com}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab715116-6bb3-5328-e3d7-c19b00359cdf
* Version Independent ID: c1c5d84e-ab3c-2cda-2b7f-d9f494c5481d
* Content: [How the proxyAddresses attribute is populated in Azure AD - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/proxyaddresses-attribute-populate?source=docs#scenario-4-exchange-online-license-is-removed)
* Content Source: [support/azure/active-directory/proxyaddresses-attribute-populate.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/proxyaddresses-attribute-populate.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by Alex-Catalin** [comment]
[PowerShell_transcript.LAPTOP-3PV1F37Q.dx7d8+_6.20220412181324.txt](https://github.com/MicrosoftDocs/SupportArticles-docs/files/8474399/PowerShell_transcript.LAPTOP-3PV1F37Q.dx7d8%2B_6.20220412181324.txt)

I have uploaded a transcript file that contains unified audit logs for the EXO license changes made to a synced user, that demonstrate what I was saying about the proxy addresses being modified when removing the EXO license.

RunspaceId   : fd9217d4-d1d4-4836-8857-e1ff0a137454
RecordType   : AzureActiveDirectory
CreationDate : 4/12/2022 2:33:19 PM
UserIds      : ServicePrincipal_84bf8be7-3603-43f2-b6a6-a0d0728cea11
Operations   : Update user.
AuditData    : {
                 "CreationTime": "2022-04-12T14:33:19",
                 "Id": "e5d0b17c-dcd4-4fab-834c-dcc9df9030ef",
                 "Operation": "Update user.",
                 "OrganizationId": "7bdc4cc7-1f8f-4e00-ba2d-57de12c93b4f",
                 "RecordType": "AzureActiveDirectory",
                 "ResultStatus": "Success",
                 "UserKey": "Not Available",
                 "UserType": "System",
                 "Version": 1,
                 "Workload": "AzureActiveDirectory",
                 "ObjectId": "proxy2@365rockstar.com",
                 "UserId": "ServicePrincipal_84bf8be7-3603-43f2-b6a6-a0d0728cea11",
                 "AzureActiveDirectoryEventType": 1,
                 "ExtendedProperties": [
                   {
                     "Name": "additionalDetails",
                     "Value": "{\"UserType\":\"Member\"}"
                   },
                   {
                     "Name": "extendedAuditEventCategory",
                     "Value": "User"
                   }
                 ],
                 "ModifiedProperties": [
                   {
                     **"Name": "ProxyAddresses",
                     "NewValue": "[\r\n  \"SMTP:proxy2@andu.onmicrosoft.com\"\r\n]",
                     "OldValue": "[\r\n  \"SMTP:proxy2@365rockstar.com\",\r\n
               \"smtp:proxy2@andu.onmicrosoft.com\"\r\n]"**
                   },
                   {
                     "Name": "Included Updated Properties",
                     "NewValue": "ProxyAddresses",
                     "OldValue": ""
                   },
                   {
                     "Name": "TargetId.UserType",
                     "NewValue": "Member",
                     "OldValue": ""
                   }
                 ],
                 **"Actor": [
                   {
                     "ID": "Microsoft Substrate Management",
                     "Type": 1**
                   },
                   {
                     "ID": "98db8bd6-0cc0-4e67-9de5-f187f1cd1b41",
                     "Type": 2
                   },
                   {
                     "ID": "ServicePrincipal_84bf8be7-3603-43f2-b6a6-a0d0728cea11",
                     "Type": 2
                   },
                   {
                     "ID": "84bf8be7-3603-43f2-b6a6-a0d0728cea11",
                     "Type": 2
                   },
                   {
                     "ID": "ServicePrincipal",
                     "Type": 2
                   }
                 ],
                 "ActorContextId": "7bdc4cc7-1f8f-4e00-ba2d-57de12c93b4f",
                 "InterSystemsId": "2799011d-951f-4974-afa1-e5269fe4cd0d",
                 "IntraSystemId": "581aea4c-79c2-4457-8d51-ea71903474a2",
                 "SupportTicketId": "",
                 "Target": [
                   {
                     "ID": "User_cc73fb02-882b-4111-b973-c6653379ada9",
                     "Type": 2
                   },
                   {
                     "ID": "cc73fb02-882b-4111-b973-c6653379ada9",
                     "Type": 2
                   },
                   {
                     "ID": "User",
                     "Type": 2
                   },
                   {
                     "ID": "proxy2@365rockstar.com",
                     "Type": 5
                   },
                   {
                     "ID": "10032001EF27B996",
                     "Type": 3
                   }
                 ],
                 "TargetContextId": "7bdc4cc7-1f8f-4e00-ba2d-57de12c93b4f"
               }
ResultIndex  : 1
ResultCount  : 10
Identity     : e5d0b17c-dcd4-4fab-834c-dcc9df9030ef
IsValid      : True
ObjectState  : Unchanged

**Comment by genlin** [comment]
@Alex-Catalin  Thanks for the feedback. I will confirm with our engineers. If the issue had been fixed, I will archive the article.

**Comment by genlin** [comment]
@Alex-Catalin As you said, the scenario 4 is not valid.  The article was updated to reflect current logic about how the proxyAddresses attribute is populated.
