### ISSUE TITLE
Directory synchronization to Azure Active Directory stops or you're warned that sync hasn't registered in more than a day

### ISSUE THREAD

**Issue by Chuksphil** [MicrosoftDocs/SupportArticles-docs#532]
In this article https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/directory-sync-stop-register

"Note- By default, directory synchronization runs every three hours".

In the article below
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-feature-scheduler#:~:text=The%20new%20default%20synchronization%20frequency,%2C%20sync%2C%20and%20export%20changes.

By default every 30 minutes a synchronization cycle is run

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ddc8be2-2530-318c-fa6b-a166f285773b
* Version Independent ID: 7c1b328a-5b12-cdb7-5d0e-4b04b0d85957
* Content: [Directory synchronization to Azure Active Directory stops or you're warned that sync hasn't registered in more than a day - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/directory-sync-stop-register#feedback)
* Content Source: [support/azure/active-directory/directory-sync-stop-register.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/directory-sync-stop-register.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Chuksphil, Thanks for the feedback. The default sync interval of  Azure AD Connect is 30 mins. This article is for the legacy AD sync tool.
