### ISSUE TITLE
Some Japanese sentences are broken.

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/SupportArticles-docs#534]
If I reach out wrong team, please let me know where I should contact.

Doc:
https://docs.microsoft.com/ja-jp/troubleshoot/power-platform/power-automate/common-errors-creating-and-assigning-flow-approvals

These are some of them.
- もし、連絡先を間違えてしまったら、どこに連絡すればいいのか教えてください。
- 複数のユーザーが指定されている場合 (セミコロンで区切られた) 場合は、すべてのエントリが Graph。
- 既定以外の Flow および Power Appsenvironments の場合、環境管理者だけが直接 (Flow 管理ポータルを介して) または間接的に (Flow 承認を通じて) Common Data Service データベースを作成できます。 管理者が必要な場合
- 管理者ポータルから手動でFlowします。
- [承認] を作成して実行Flow。

**Comment by lucciz01** [comment]
Hi @MiyukiAmino, this request is sent to the localization team. Will let you know when it is fixed. Thanks!

**Comment by lucciz01** [comment]
This issue is fixed.
