### ISSUE TITLE
Unable to  clear the Use managed disks check box when creating rescue VM

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#535]
Hello, team.  I'm not able to  clear the Use managed disks check box when trying to create the rescue VM.  Instead, it's greyed out and says "Gallery package requires managed disks".  I'm using the Windows Server 2019 image from the marketplace.  Not sure what's going on here.   Thanks.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89716d5f-ca8d-e689-42c1-b3a84d5f6925
* Version Independent ID: 0b17ba72-e832-2781-efb4-9457261ebc03
* Content: [Attach an unmanaged disk to a VM for offline repair - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair?source=docs)
* Content Source: [support/azure/virtual-machines/unmanaged-disk-offline-repair.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/unmanaged-disk-offline-repair.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver  Are you trying to repair a managed disk? If yes, we need to follow the steps in [Repair a Windows VM by using the Azure Virtual Machine repair commands](https://github.com/MicrosoftDocs/SupportArticles-docs/issues/535https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands).

**Comment by mbiver** [comment]
Hello, Thomas.  I'm trying to follow the steps here https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair?source=docs#create-a-repair-vm-with-an-unmanaged-os-disk 

but when I get to step 3

"On the Disks page, expand Advanced below Data Disks and then **_clear the Use managed disks check box_**. Select a storage account for the unmanaged OS disk. Do not select to attach an existing disk."

I'm not able to clear the check box.  The check box is greyed out and there's a message that says "Gallery package requires managed disks".  How can I follow those steps and clear the check box according to the documentation?  thanks

**Comment by DAFRAYAL** [comment]
> Hello, @genlin I'm trying to follow the steps here https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair?source=docs#create-a-repair-vm-with-an-unmanaged-os-disk
> 
> but when I get to step 3
> 
> "On the Disks page, expand Advanced below Data Disks and then **_clear the Use managed disks check box_**. Select a storage account for the unmanaged OS disk. Do not select to attach an existing disk."
> 
> I'm not able to clear the check box. The check box is greyed out and there's a message that says "Gallery package requires managed disks". How can I follow those steps and clear the check box according to the documentation? thanks

Have same issue, they add it to personalities, with mortal combinations. Or it is for most who do not classify as such, I guess. Or they have ran out of not provisioned support. This is recent issue, again! Same happened some years ago.

**Comment by DAFRAYAL** [comment]
> > Hello, @genlin I'm trying to follow the steps here https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair?source=docs#create-a-repair-vm-with-an-unmanaged-os-disk
> > but when I get to step 3
> > "On the Disks page, expand Advanced below Data Disks and then **_clear the Use managed disks check box_**. Select a storage account for the unmanaged OS disk. Do not select to attach an existing disk."
> > I'm not able to clear the check box. The check box is greyed out and there's a message that says "Gallery package requires managed disks". How can I follow those steps and clear the check box according to the documentation? thanks
> 
> Have same issue, they add it to personalities, with mortal combinations. Or it is for most who do not classify as such, I guess. Or they have ran out of not provisioned support. This is recent issue, again! Same happened some years ago. Money's good for news.

If you talk to their payed or unpayed support about it they will just keep trying to misdirect or keep you waiting.

**Comment by mbiver** [comment]
found this public statement that says not all images can be deployed with unmanaged disks.  https://docs.microsoft.com/en-us/azure/virtual-machines/faq-for-disks#can-i-deploy-a-vm-with-an-unmanaged-disk-in-the-azure-portal-

Came up with the steps below as workaround.  @genlin , perhaps we can integrate these into the article?

Here was the official guidance where it shows how to copy the disk using Storage Explorer, instead of taking a snapshot like managed disks, create a new unmanaged disk VM, and attach.  
 
Attach an unmanaged disk to a VM for offline repair
 
From < https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair#create-a-copy-of-the-unmanaged-os-disk-attached-to-the-source-failed-vm> 
 
 
When I got to the part about creating the new rescue VM with unmanaged disks, I was not able to clear the "Use managed disks" check box in the UI.  It was greyed out.
![image](https://user-images.githubusercontent.com/39092497/165127487-edd91a4b-c802-4c88-a582-5c78fb9b6f15.png)

Since I couldn’t create the rescue VM with the portal, I went to AZ CLI
 
#This first line is to get the resource ID for connecting the VM to an existing vnet. 

$SubnetID = az network vnet subnet show --resource-group VNET_RG_HERE --name SUBNET_NAME_HERE --vnet-name VNET_NAME_HERE --query id -o tsv
 
#This second command creates the VM using unmanaged disks and connects it to the existing vNet without a public IP and inheriting the NSG from the network
 
az vm create -g RG_NAME_HERE -n VM_NAME_HERE -l LOCATION_HERE --admin-username ADMIN_USER_HERE --subnet $SubnetID --size standard_d4s_v3 --use-unmanaged-disk  --image win2019datacenter --public-ip-address '""' --nsg '""' 
 
Once the Rescue VM was created, I used this link to attach the copied OS disk as a data disk.
 
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair#attach-a-copy-of-the-unmanaged-disk-to-the-repair-vm
 
 
Since I did want to use nested virtualization in the rescue VM, to avoid swapping the disk back and forth until I knew it was fixed, I used the command below to install Hyper-V and restart
 
Install-WindowsFeature Hyper-V -IncludeAllSubFeature -IncludeManagementTools -Restart
 
 
Once the VHD was all fixed, Iused the steps below to detach and swap with the broken OS VHD
 
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unmanaged-disk-offline-repair#replace-the-os-disk-on-the-source-vm

**Comment by DAFRAYAL** [comment]
I simply moved to G cloud much cheaper and a bit more secure except that they do not offer client windows systems which makes server a bit less secure, clients are of higher security environments with lack of domain host of course, cause of intel.
There's not much difference between microsoft and linux google. well microsoft managibility tried way harder than google though. and microsoft is not so free based, but as long as google which is quite the linux is on the cloud, its fine to host VM there.

**Comment by DAFRAYAL** [comment]
azure is dwelving into "caucau"" : ( like you were there.

**Comment by DAFRAYAL** [comment]
Its all cause of how deep is azure with security, google on other hand is not a microsoft so it cannot offer all the services that microsoft itself has to offer, only world based securities not integrating with windows much. Same for every other host, azure is heavy piece.

**Comment by genlin** [comment]
@DAFRAYAL  Sorry for the inconvenience had casued. 

@mbiver , I will work with you offline to update the article.
