### ISSUE TITLE
Azure AD Sync

### ISSUE THREAD

**Issue by onsite-insights** [MicrosoftDocs/SupportArticles-docs#537]
Users are not changing passwords in M365, only in on premise AD but passwords are not synching to the M365 accounts. AD Sync in Azure shows no issues. Access to M365 accounts is gained by using old passwords, sometimes months old.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b79a492-c80c-6e04-068e-299e07bb642b
* Version Independent ID: c55f8604-815f-5472-a83c-248af5d8350e
* Content: [Separate passwords required for the computer and work or school account when using password synchronization and the Azure Active Directory sync tool - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/separate-pwds-required-computer-work-account)
* Content Source: [support/azure/active-directory/separate-pwds-required-computer-work-account.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/separate-pwds-required-computer-work-account.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@onsite-insights, To resolve the issue quickly, I suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
