### ISSUE TITLE
incorrect path stated for editing fstab for option "root login"

### ISSUE THREAD

**Issue by bartoque** [MicrosoftDocs/SupportArticles-docs#540]
The instructions to edit the fstab in the "root login" part should not state:

`nano /mnt/troubleshootingdisk/etc/fstab`

As that is the way to edit the fstab for the next "offline" option (where the disk is mounted into /mnt on a other vm), hence it should state:

`nano /etc/fstab`

So it should be the same as for the previous option to edit fstab via serial console login in single user mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576725c0-f50a-d686-2213-7da506bc63c2
* Version Independent ID: aa284cac-7e07-c916-58fa-ac329b838803
* Content: [Troubleshoot Linux VM starting issues due to fstab errors - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors)
* Content Source: [support/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **v-six**

**Comment by genlin** [comment]
@bartoque，Thanks for the feedback. Yes, the command in serial console is incorrect. I will update the article.

**Comment by genlin** [comment]
@bartoque，I will close this issue since the article was updated. Thanks again for helping to imrpove the qaulity of the article.
