### ISSUE TITLE
A little correction on this page to make it read properly

### ISSUE THREAD

**Issue by toddhammer** [MicrosoftDocs/SupportArticles-docs#543]
On step 1. of this page, you need a "new line" before dracut.  
dracut and what follows needs to be on its own line. As it is, it runs in with the previous command. 

As a side note, it would be helpful to tell the user what these commands do. For example:  "Make backup of current .img" and then "Build Initramfs"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87923903-be07-d5a3-f555-4ef2a0a7173e
* Version Independent ID: c7191d9e-61dc-12cd-b16f-c7b2ca0df289
* Content: [How to recover Azure Linux VM from kernel-related boot issues - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/kernel-related-boot-issues#how-to-rebuild-the-initramfs-file)
* Content Source: [support/azure/virtual-machines/kernel-related-boot-issues.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/kernel-related-boot-issues.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@toddhammer, Thanks for the feedbacks and pointing out the issue in this article. I will update the article.

**Comment by genlin** [comment]
@toddhammer I will close this issue since the article was updated. Thanks again for helping to improve the quality of the article.
