### ISSUE TITLE
Need something like "bcdedit /store f:\boot\bcd /enum" to get the identifier, don't we?

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#546]
Hello, team.  I see that we have this line in the script to Enable dump log and Serial Console

bcdedit /store F:\boot\bcd /ems {<BOOT LOADER IDENTIFIER>} ON

but we don't tell them how to find the BOOT LOADER IDENTIFIER first?

Wouldn't we need to add something like "bcdedit /store f:\boot\bcd /enum" to get the identifier?  thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55985059-545a-99f0-0723-77370937205d
* Version Independent ID: f30fa1e5-aef7-a576-ebcf-445aef9c0ae0
* Content: [VM startup is stuck on 'Getting Windows ready. Don't turn off your computer' in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-vm-boot-configure-update)
* Content Source: [support/azure/virtual-machines/troubleshoot-vm-boot-configure-update.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-vm-boot-configure-update.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by mbiver** [comment]
Also, I was just running through this scenario, and this is assuming that both the boot\bcd and Windows partition are on the same drive letter.  if the system reserved partition and the windows partition are separate, like many scenarios in Azure, then these commands will fail.  in my test scenario, the System Reserved partition was assigned the F drive and the Windows partition was assigned the G drive.  

![image](https://user-images.githubusercontent.com/39092497/165845322-f9239f05-7aaa-4c86-8583-e687cd68a502.png)


first, I ran the command below to get the Windows Boot Loader identifier

bcdedit /store f:\boot\bcd /enum" 

![image](https://user-images.githubusercontent.com/39092497/165845947-25c5013c-22d2-40b0-bbfa-66ef71cc5d6e.png)

I then mounted the registry which is on the Windows partition, at the G drive


reg load HKLM\BROKENSYSTEM g:\windows\system32\config\SYSTEM

I updated the BCD settings, which are on the F drive and specified the value "default" for the Windows boot loader


REM Enable Serial Console
bcdedit /store F:\boot\bcd /set {bootmgr} displaybootmenu yes
bcdedit /store F:\boot\bcd /set {bootmgr} timeout 5
bcdedit /store F:\boot\bcd /set {bootmgr} bootems yes
bcdedit /store F:\boot\bcd /ems {default} ON
bcdedit /store F:\boot\bcd /emssettings EMSPORT:1 EMSBAUDRATE:115200

and then updated the registry settings and unloaded the hive.


REM Suggested configuration to enable OS Dump
REG ADD "HKLM\BROKENSYSTEM\ControlSet001\Control\CrashControl" /v CrashDumpEnabled /t REG_DWORD /d 1 /f
REG ADD "HKLM\BROKENSYSTEM\ControlSet001\Control\CrashControl" /v DumpFile /t REG_EXPAND_SZ /d "%SystemRoot%\MEMORY.DMP" /f
REG ADD "HKLM\BROKENSYSTEM\ControlSet001\Control\CrashControl" /v NMICrashDump /t REG_DWORD /d 1 /f

REG ADD "HKLM\BROKENSYSTEM\ControlSet002\Control\CrashControl" /v CrashDumpEnabled /t REG_DWORD /d 1 /f
REG ADD "HKLM\BROKENSYSTEM\ControlSet002\Control\CrashControl" /v DumpFile /t REG_EXPAND_SZ /d "%SystemRoot%\MEMORY.DMP" /f
REG ADD "HKLM\BROKENSYSTEM\ControlSet002\Control\CrashControl" /v NMICrashDump /t REG_DWORD /d 1 /f

reg unload HKLM\BROKENSYSTEM

**Comment by genlin** [comment]
@mbiver  Thanks for the feedback and providing the detail script. I will update the article.

**Comment by genlin** [comment]
@mbiver,  I will close this issue since the problem was fixed in the article. Thanks again for helping to improve the quality of the article.
