### ISSUE TITLE
DiscoveryMailbox mailnickname is not allowing more than 142 chars

### ISSUE THREAD

**Issue by rabbanisyed** [MicrosoftDocs/SupportArticles-docs#547]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8dcba0-fadb-5689-3b5b-18095e154ec8
* Version Independent ID: e2df1bbb-0ae4-d4ca-5aa4-5f78523c0745
* Content: [You can't sync the SystemMailbox or DiscoveryMailboxSearch accounts by using the Azure Active Directory Sync tool - Active Directory](https://docs.microsoft.com/en-US/troubleshoot/azure/active-directory/unable-sync-system-discovery-mailbox)
* Content Source: [support/azure/active-directory/unable-sync-system-discovery-mailbox.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/unable-sync-system-discovery-mailbox.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**
![discoverymailbox shortfall of space](https://user-images.githubusercontent.com/32798374/166150337-e42eb134-c952-410d-b59f-c132bb5e430b.png)

**Comment by genlin** [comment]
@rabbanisyed, To resolve this issue quickly, I suggest you contact [our support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview?DMC=troubleshoot).
