### ISSUE TITLE
Is there a way to find the memory usage percentage of a container using Kusto query?

### ISSUE THREAD

**Issue by Vijay-Nirmal** [MicrosoftDocs/SupportArticles-docs#548]
Is there a way to find the memory usage (and CPU usage) percentage of a container using Kusto query?

If possible then updated the documentation with the details

**Reasoning:** Currently, we can't pin any memory usages per container data to a dashboard. Also, I couldn't find a way to get the max allocated memory of a container. Which means, currently there is no way to display memory usages per container data to a dashboard.

![image](https://user-images.githubusercontent.com/24755596/166247132-b968f52c-35c8-4806-993c-169b7863cb47.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed86552-a97e-25cf-c72c-d5bb1ee61fb6
* Version Independent ID: bed86552-a97e-25cf-c72c-d5bb1ee61fb6
* Content: [Identify memory saturation in AKS clusters - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/identify-memory-saturation-aks)
* Content Source: [support/azure/azure-kubernetes/identify-memory-saturation-aks.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/identify-memory-saturation-aks.md)
* Service: **container-service**
* GitHub Login: @kelleyguiney22
* Microsoft Alias: **v-kegui**

**Comment by kelleyguiney22** [comment]
@Vijay-Nirmal my apologies for the much-delayed response. Our team appreciates your feedback. This isn't a way to do what you're requesting at this time. The team thinks this is a great item for a possible feature request in the future. It hasn't been addressed yet though and is probably low on the priority list. I did ping the team again to remind them about this. Thank you again for the suggestion.
