### ISSUE TITLE
Joining VM to domain after agent is installed produces same result

### ISSUE THREAD

**Issue by Xandven** [MicrosoftDocs/SupportArticles-docs#549]
I have found another scenario where this could happen. To reproduce the same result as described in this article create a new VM with the joindomain extension and Monitoring  Agent Auto provisioning enabled. In most cases the agent will install and activate before the VM is joined to the domain and it will fail in the same way as described in this article as the computer name is changed when it is joined to a domain.

Our current workaround is to disable auto provisioning before we create new VMs and then reenable once the VMs has been joined to the domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0302df46-046c-c8ad-4fcd-5caacac583f5
* Version Independent ID: 0302df46-046c-c8ad-4fcd-5caacac583f5
* Content: [Error code 0x80090016 Keyset does not exist in event viewer or agent logs - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/log-analytics/error-code-0x80090016-keyset-does-not-exist)
* Content Source: [support/azure/log-analytics/error-code-0x80090016-keyset-does-not-exist.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/log-analytics/error-code-0x80090016-keyset-does-not-exist.md)
* Service: **log-analytics**
* GitHub Login: @kelleyguiney22
* Microsoft Alias: **v-kegui**

**Comment by kelleyguiney22** [comment]
@Xandven thanks very much for the feedback! We're looking into this.

**Comment by kelleyguiney22** [comment]
@Xandven I have been in touch with our technical advisor on this issue. He isn't able to repro the issue and requested that I give you his email address and ask you to please email him so he can discuss this with you. His email is irfanr@microsoft.com. Thank you!

**Comment by kelleyguiney22** [comment]
@irabba2 I'm tagging you so you can discuss this issue with the person who initiated this discussion. Thanks!

**Comment by kelleyguiney22** [comment]
Irfan never heard from this commentor. Also, Thomas Lin asked me to have Irfan communicate with this commentor directly in the PR. Irfan didn't have Github set up, so I sent him the instructions to do so and explained the situation. I'm closing this as can't repro.

**Comment by kelleyguiney22** [comment]
Irfan never heard from this commentor. Also, Thomas Lin asked me to have Irfan communicate with this commentor directly in the PR. Irfan didn't have Github set up, so I sent him the instructions to do so and explained the situation. I'm closing this as can't repro.

**Comment by JarrettRenshaw** [comment]
Closing on behalf of Kelley
