### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by genlin** [MicrosoftDocs/SupportArticles-docs#55]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5112fde-b107-afe6-c7e7-be68e3fb3a1f
* Version Independent ID: d7d2e93c-3fdf-2e85-f47b-ee72166e53ed
* Content: [How to troubleshoot Azure Recovery Services - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/site-recovery/troubleshoot-azure-recovery-services)
* Content Source: [support/azure/site-recovery/troubleshoot-azure-recovery-services.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/site-recovery/troubleshoot-azure-recovery-services.md)
* Service: **backup**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by dcurwin** [comment]
@genlin  - Hello, can we please close this test issue?

**Comment by genlin** [comment]
@dcurwin, Closed. We just enable the issue feature in our repo, so I created this issue for testing the auto tag feature in PRmerge.
