### ISSUE TITLE
Fix the issue on step #8 instead of repeat the whole process

### ISSUE THREAD

**Issue by susej2** [MicrosoftDocs/SupportArticles-docs#550]
**### For FSTAB issues.** 

When you use this method: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-grub-single-user-mode#enter-single-user-mode-without-root-account-enabled-in-rhel there is no need on the step number 8 to go back and perform the "preceding instructions" 

Once you followed the steps below: 

- In the shell, enter mount -o remount,rw /sysroot to remount the root file system with read/write permissions.
- After you boot into single-user mode, enter chroot /sysroot to switch into the sysroot jail.

You are supposed to be root on the VM so any change you perform should be persistent. I did a lab on my end and while on root I fixed fstab file then rebooted the VM and it worked pretty well, VM was booting as expected. 

I think on that step number 2 instead of specifying "_You're now at root. You can reset your root password by entering passwd and then use the preceding instructions to enter single-user mode._" it would be better to have something like this: "**Fix FSTAB file by editing the file with the editor you feel more comfortable**" or "**Apply desired mitigation (if this is not fstab issue)**" 

My ask is just to make sure our customers have an easiest way to troubleshoot the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef37b5e1-f76f-6dce-8730-ff46d99fb985
* Version Independent ID: 4e15573e-f0f2-abe0-d919-8eb1ba96905f
* Content: [Azure Serial Console for GRUB and single-user mode - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-grub-single-user-mode#manually-enter-single-user-mode-in-rhel)
* Content Source: [support/azure/virtual-machines/serial-console-grub-single-user-mode.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-grub-single-user-mode.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@susej2  Thanks for the feedback. I am agree with you that the step 8 is confusing. I will update it to:
8. You're now at root, and you can start troubleshooting the system issues."

**Comment by genlin** [comment]
@susej2 The article was updated. Thanks again for helping to improve the document.
