### ISSUE TITLE
Local Security Policy Directions aren't correct

### ISSUE THREAD

**Issue by mrdenny** [MicrosoftDocs/SupportArticles-docs#551]
The directions in Solution 1 say that they are for the local security policy, but they are for a (sort of) group policy. 

Step 1 should be changed to open the group policy editor.

Expand Computer Configuration > Policies > Window Settings > Security Settings > Local policies, and then select User rights assignment.

A second option should be added to edit the local security policy, and these settings are under Security Settings > Local Policies > User Rights Assigment.

The user right isn't "Log on locally" it's "Allow log on locally"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e48d6a13-c7f7-20bc-c9da-69b256e8e6f5
* Version Independent ID: 436a4ad9-bca2-52bf-eb95-bd20214e7d4e
* Content: [Azure Active Directory Connect services don't start - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/services-sync-not-start)
* Content Source: [support/azure/active-directory/services-sync-not-start.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/services-sync-not-start.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for your feedback, @mrdenny. Responses are inline below:

> The directions in Solution 1 say that they are for the local security policy, but they are for a (sort of) group policy.
> 
> Step 1 should be changed to open the group policy editor.

Step 1 currently reads "Select **Start**, enter _gpedit.msc_ in the search box, and then press Enter to open the Local Group Policy Editor snap-in." How is that different from what you think it should be?

> Expand Computer Configuration > Policies > Window Settings > Security Settings > Local policies, and then select User rights assignment.
> 
> A second option should be added to edit the local security policy, and these settings are under Security Settings > Local Policies > User Rights Assigment.

When I open _gpedit.msc_ (Local Group Policy Editor), "Policies" is not a separate node between "Computer Configuration" and "Windows Settings". Also, the path to the local security options is the basically the same (aside from capitalization, which should match the initial-cap format used in the snap-in). Were there other rights besides the 3 listed that you think should be added?

> The user right isn't "Log on locally" it's "Allow log on locally"

You're correct. I'll make this change.

**Comment by mrdenny** [comment]
It appears that there are two different ways to open up the local policy editor. One is to run gpedit.msc. The other is to search for "Local Security Policy" and open the editor that way. These will give two different views apparently.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
***@***.******@***.***>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar ***@***.***/bookings/>
[Logo, company name  Description automatically generated]<http://www.dcac.co/>
***@***.***
[A picture containing text  Description automatically generated]
[A blue sign with white text  Description automatically generated with low confidence]

**Comment by DennisLee-DennisLee** [comment]
The policy name correction is now live at [One or more Azure Active Directory Connect services don't start](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/services-sync-not-start#solution-1-set-user-rights-assignment-permissions-within-group-policy). Note that Solution 1 has several changes that go beyond what's addressed here. For that reason we didn't add the local security policy alternate method, since that's just identical to what's done through the local group policy editor and would unnecessarily complicate the solution.
