### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Farrukh000** [MicrosoftDocs/SupportArticles-docs#554]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e8dba7-b480-fef3-9e45-534281be9aa3
* Version Independent ID: 5c80fe11-3a60-8738-1f8a-957d8439de50
* Content: [Azure region access request process - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process)
* Content Source: [support/azure/general/region-access-request-process.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/region-access-request-process.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Farrukh000, Did you have problems when submitting the request to enable region access? If the steps in this article don't work for you, you try to select the "quote type" as "Other requests" , then submit the ticket. After that, our engineer will contact you to resolve the issue.

**Comment by genlin** [comment]
@Farrukh000, As I haven't heard back from you a few days, I will process to close this issue. Feel free to reopen it if you still have a question.
