### ISSUE TITLE
We met a different scenario like the Doc, on step 4 (doc: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-extend-encrypted-os-volume)

### ISSUE THREAD

**Issue by jiqims** [MicrosoftDocs/SupportArticles-docs#555]
On this Doc: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-extend-encrypted-os-volume

We met a different scenario like the Doc, on step 4 
![image](https://user-images.githubusercontent.com/104980749/166902526-62451a63-5750-4bf1-8eeb-1de81f16e1aa.png)

we cannot copy the bcd file due to the specific file cannot be found. 

Customer tried to run this script to set BCD but still failed and what’s more, this will make the VM cannot reboot. 
bcdedit.exe /set "{bootmgr}" integrityservices enable
bcdedit.exe /set "{default}" device partition=C:
bcdedit.exe /set "{default}" integrityservices enable
bcdedit.exe /set "{default}" recoveryenabled Off
bcdedit.exe /set "{default}" osdevice partition=C:
bcdedit.exe /set "{default}" bootstatuspolicy IgnoreAllFailures
#Enable Serial Console Feature
bcdedit.exe /set "{bootmgr}" displaybootmenu yes
bcdedit.exe /set "{bootmgr}" timeout 5
bcdedit.exe /set "{bootmgr}" bootems yes
bcdedit.exe /ems "{current}" ON
bcdedit.exe /emssettings EMSPORT:1 EMSBAUDRATE:115200

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cf97f9-e909-79be-4cc9-c2417012a122
* Version Independent ID: 66fb5aa4-865d-77ef-3239-b4bddcbfd7a2
* Content: [Cannot extend an encrypted OS volume in Windows - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-extend-encrypted-os-volume)
* Content Source: [support/azure/virtual-machines/cannot-extend-encrypted-os-volume.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/cannot-extend-encrypted-os-volume.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@jiqims, Did you successfully create the boot files by running `bcdboot C:\Windows /s F:` ? If yes, you should see the boot files in the drive F (or the drive you specified). To resolve this issue quickly, I suggest you contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by genlin** [comment]
@jiqims, As I haven't heard back from you a few days, I will process to close this issue. Feel free to reopen it if you still have a question.
