### ISSUE TITLE
Request to add US Gov endpoints

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/SupportArticles-docs#556]
Requesting we add US Gov endpoints as well (for Azure Gov/M365 GCC High/M365 DoD). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2957a41-0ebd-4f1e-6f9c-d4f9173d4630
* Version Independent ID: e92921f7-9899-6a70-412f-f6094e772271
* Content: [How to securely transfer files to Microsoft Support - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/secure-file-exchange-transfer-files)
* Content Source: [support/azure/general/secure-file-exchange-transfer-files.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/secure-file-exchange-transfer-files.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@carlova, We only lists the end point of the public clouds/services. Let's chat offline for your request.

**Comment by genlin** [comment]
@carlova, As we disscused offline, I will add the endpoint to the article.
