### ISSUE TITLE
Add prerequisites to "Prerequisites to access the Azure Serial Console" section

### ISSUE THREAD

**Issue by lorenzomsft** [MicrosoftDocs/SupportArticles-docs#557]
Hi team,
please add few points in "Prerequisites to access the Azure Serial Console" section:
serial console is not supported when storage account has firewall enabled
serial console is not supported when storage account has "Allow storage account key access" disabled

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4dfc75-25a4-ae83-8d6a-00f267bf85b9
* Version Independent ID: faa41c37-7b66-671b-09ca-3fb076f701e3
* Content: [Azure Serial Console - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-overview#prerequisites-to-access-the-azure-serial-console)
* Content Source: [support/azure/virtual-machines/serial-console-overview.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-overview.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@lorenzomsft Thanks for the feedback. I will add this information into the article.

**Comment by genlin** [comment]
@lorenzomsf The article was updated. Thanks again for your contribution.
