### ISSUE TITLE
Further AV Exclusions

### ISSUE THREAD

**Issue by nutwiss** [MicrosoftDocs/SupportArticles-docs#56]
Could you please confirm that any of the following items (suggested against previous versions of TFS / VSTS / DevOps) are still valid and safe exclusions for Azure DevOps 2020:

Agent Folders
Application Tier File Cache
.NET Temp Files
TFS Version Control Cache Folder
Team System Web Access Cache Folder
TFS Build folder
TFS Drop location
SQL database folders
SQL backup folders

If these are still recommended, can they be added to this article, please?

Are there any other recommendations?

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2326a1-8ef6-1494-d0b1-8070a0e9c997
* Version Independent ID: 71e54123-55dc-8a39-81b7-4497dbbb7032
* Content: [Antivirus scanning exclusions - Active DevOps](https://docs.microsoft.com/en-US/troubleshoot/azure/devops/antivirus-scanning-exclusions)
* Content Source: [support/azure/devops/antivirus-scanning-exclusions.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/devops/antivirus-scanning-exclusions.md)
* Product: **devops**
* GitHub Login: @ramakoni1
* Microsoft Alias: **ramakoni**

**Comment by HaiyingYu** [comment]
@nutwiss Thank you for your feedback . We will have this reviewed and update the thread.

**Comment by HaiyingYu** [comment]
The article has been updated.
