### ISSUE TITLE
Doc Has Had Reserved Access Regions Guidance Removed

### ISSUE THREAD

**Issue by asciorilli** [MicrosoftDocs/SupportArticles-docs#560]
[Enter feedback here]
Hello, I am part of Field Insights Team, and noticed that this document has been updated, however now excludes the scenario where customers need to request access to a Reserved Access (hidden) Region that is not in the drop down. The version on prior to the April 12th edit addressed this, however this guidance has since been removed.

At Step 2, point 3, if a customer wants to request access to the 8 Reserved Access Regions (eg just to name a few AU Central 2, UAE Central, South Africa West) they do NOT appear in the drop down. The previous document guided customers to request this in the "Service and Subscription Limits (Quotas)" and then "Other Requests" and the document used to guide them to input the correct info into the free-form text box.

This previously was the only document that instructed customers as to how to request access to these Reserved Access Regions, and you have inadvertantly removed this guidance.

Are you able to update it to include this scenario ? I would be happy to discuss this further
Many thanks

Anthony Sciorilli
anscior@microsoft.com
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e8dba7-b480-fef3-9e45-534281be9aa3
* Version Independent ID: 5c80fe11-3a60-8738-1f8a-957d8439de50
* Content: [Azure region access request process - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process)
* Content Source: [support/azure/general/region-access-request-process.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/region-access-request-process.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@asciorilli, Thanks for the feedback. Let's chat offline for this issue. I will close this issue.
