### ISSUE TITLE
typo/information incorrect

### ISSUE THREAD

**Issue by mitchcr** [MicrosoftDocs/SupportArticles-docs#565]
In the very first parragraph of this document there is misinformation, it mentions in the tittle that ADE version 0 is dual-pass encryption and ADE version 1 is single-pass encryption but last line of the following text says ADE version 1 and between the parenthesis it says dual-pass encryption instead of single-pass encryption:

You can identify the ADE version in the Azure portal by opening the properties of the VM, and then selecting Extensions to open the Extensions blade. On the Extensions blade, view the version number of AzureDiskEncryptionForLinux.

If the version number is 0.*, the disk uses dual-pass encryption.
If the version number is 1.* or a later version, the disk uses single-pass encryption.
If your disk uses ADE version 1 (dual-pass encryption), use the [Method 3](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair#method3) to unlock the disk.

Under the "Select the method to unlock the encrypted disk" on step three there is the same mistake. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a6c7315-1188-4abd-2551-07dba21368de
* Version Independent ID: c9dddec0-09db-8d2c-6016-70f88f5ce4c0
* Content: [Unlocking an encrypted Linux disk for offline repair - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair#determine-whether-the-os-disk-uses-ade-version-0-dual-pass-encryption-or-ade-version-1-single-pass-encryption)
* Content Source: [support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **diambroi**

**Comment by genlin** [comment]
@mitchcr  Thanks for the feedback. Yes, the value 1 is  single-pass encryption. I will update the article.

**Comment by genlin** [comment]
@mitchcr The article was updated. Thanks again for your contribution.
