### ISSUE TITLE
Update scenario when its useful to use the 'offline' GA installation

### ISSUE THREAD

**Issue by kegregoi** [MicrosoftDocs/SupportArticles-docs#570]
Can we please update the scenarios under 'When to use the VM Agent in offline mode'

This should only be used when you can't RDP into a VM, so can we remove the existing scenarios and update to something along the lines of:
"The Guest Agent is not installed and you can't RDP into the VM. If you can RDP,  instead please just RDP into the VM and download and install the [latest .MSI of the Guest Agent](https://github.com/Azure/WindowsVMAgent/releases)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c294ae1d-9518-2f87-0cc8-320b0cc5ac02
* Version Independent ID: 7be72203-e1f0-e692-399f-4a618d0b126e
* Content: [Install the Azure VM Agent in offline mode - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/install-vm-agent-offline)
* Content Source: [support/azure/virtual-machines/install-vm-agent-offline.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/install-vm-agent-offline.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@kegregoi  Thanks for the suggestion. I will update the scenario.
