### ISSUE TITLE
This does not work - get redirected to "Manage Quotas" which has not GPU info

### ISSUE THREAD

**Issue by nathanieltagg** [MicrosoftDocs/SupportArticles-docs#571]
I got directed to this page from the DataBricks help. I want to set up an ML cluster on databricks.

I followed the instructions on this page, but get a message "You don’t need a support ticket to get more quota. Select Manage Quota to increase quota instantly."  This gives me a "Manage Quota" button, but in that page there is are no GPU options. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e8dba7-b480-fef3-9e45-534281be9aa3
* Version Independent ID: 5c80fe11-3a60-8738-1f8a-957d8439de50
* Content: [Azure region access request process - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process)
* Content Source: [support/azure/general/region-access-request-process.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/region-access-request-process.md)
* Service: **azure**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@nathanieltagg, Please try select "Other requests" in the case submission page. Then specify your request in the description. To submit "other requests" support ticket, you can refer to the steps in [Reserved access regions](https://docs.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process#reserved-access-regions).
