### ISSUE TITLE
Minimum Required Permissions to view VM Boot Diagnostics

### ISSUE THREAD

**Issue by mrchops1024** [MicrosoftDocs/SupportArticles-docs#583]
I have admins that would like to view the screenshots that are shown on the Boot Diagnostics section on VMs. This is in case a machine is taking a long time to reboot, they can "see" the current status of the VM via the screenshots. So far the least amount of permissions that has enabled viewing this info is similar to the serial console permissions:

- Virtual Machine Contributor on the VM
- Storage Account Contributor on the diagnostic storage account

We use a custom storage account instead of the managed one, in case that matters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e04cf5d-6a98-6c34-f7bf-cfb67678f860
* Version Independent ID: e0fc8961-ac60-37d9-3ec5-8288a203f17b
* Content: [Boot diagnostics for VMs in Azure - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-diagnostics)
* Content Source: [support/azure/virtual-machines/boot-diagnostics.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/boot-diagnostics.md)
* Service: **virtual-machines**
* GitHub Login: @GenLi
* Microsoft Alias: **genli**

**Comment by mrchops1024** [comment]
@genlin Any update on this?

**Comment by genlin** [comment]
@mrchops1024, Thanks for the feedback. We will consider to add this information to the article. I will process to close this issue. Feel free to let me know if there is any additional comment or question.
