### ISSUE TITLE
EXO Basic Auth is still used in this documentation

### ISSUE THREAD

**Issue by aanticamara2021** [MicrosoftDocs/SupportArticles-docs#586]
Hi,
Please replace EXO PSv1 (basic auth) with PSv2 in connecting to EXO Powershell module. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cce2b95-ed72-3a30-22b0-b1df507e41da
* Version Independent ID: 943a0f77-1fda-18f8-2dc4-a47b82d3db59
* Content: [One or more objects don't sync when the Azure Active Directory Sync tool is used - Active Directory](https://docs.microsoft.com/en-US/troubleshoot/azure/active-directory/objects-dont-sync-ad-sync-tool)
* Content Source: [support/azure/active-directory/objects-dont-sync-ad-sync-tool.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/objects-dont-sync-ad-sync-tool.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@aanticamara2021, Thanks for the feedback. We will review and update the commands in the article.

**Comment by genlin** [comment]
@aanticamara2021, The article was updated. So I will process to close this issue. Feel free to let me know if there is any additional comment or feedback.
