### ISSUE TITLE
Typo in OMS validation Python statement.

### ISSUE THREAD

**Issue by DevMan01** [MicrosoftDocs/SupportArticles-docs#594]
At [this URL](https://docs.microsoft.com/en-us/troubleshoot/azure/general/reinstall-oms-agent-linux#verify-the-agent-reinstallation), the validation python3 code segment, python directory, is quoted in upper case:

`sudo su omsagent -c 'python3 /opt/microsoft/omsconfig/Scripts/Python3/PerformRequiredConfigurationChecks.py'`

However, I would receive an error `[Errno 2] No such file or directory`

The fault seems to in the python directory, it was created by the OMS agent in lower case:

`.../Scripts/python3/PerformRequiredConfigurationChecks.py`

At least this is how the OMS agent installed its dependencies on my system:

> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.4 LTS
> Release:        20.04
> Codename:       focal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4884229-ee82-3f6e-856d-bfe6b87556d3
* Version Independent ID: cde2310e-17a5-2c1c-ca70-b5f27a8d7d75
* Content: [How to reinstall Operations Management Suite (OMS) Agent for Linux - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/reinstall-oms-agent-linux)
* Content Source: [support/azure/general/reinstall-oms-agent-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/reinstall-oms-agent-linux.md)
* Service: **automation**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@DevMan01, Thanks for the feedback. I got the same result in an Ubuntu 20.04 VM. It should be "python3. Will test it in other Linux distributions. If this is a common scenario, we will update the article.

**Comment by genlin** [comment]
@DevMan01, The article is updated. Meantime I will process to close this issue. Feel free to let me know if there is any additional question or comment.
