### ISSUE TITLE
Why transfer the Node tcpdump file to local via POD?

### ISSUE THREAD

**Issue by yinoa** [MicrosoftDocs/SupportArticles-docs#595]
[Enter feedback here]
Why transfer the Node tcpdump file to local via POD?

Also the cp command output is a failed one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Version Independent ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Content: [Capture a TCP dump from a Linux node in an AKS cluster - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks)
* Content Source: [support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md)
* Service: **container-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Handling this one offline.
