### ISSUE TITLE
Storage sense can be enabled or disabled in Windows 11 too

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/SupportArticles-docs#596]
Github doc link
**https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/shell-experience/temp-folder-with-logon-session-id-deleted.md**

so i want to Windows 11 edition too
![Screenshot 2022-06-05 180915](https://user-images.githubusercontent.com/3296790/172050904-e57774be-cbe2-404f-97fc-78ffbbebab88.jpg)

@Deland-Han. please look into issue

**Comment by Deland-Han** [comment]
Hi @RAJU2529, could you be more specific on your question? This article is about the Desktop Experience feature of Windows Server, so it does not apply to Windows 11.

**Comment by Deland-Han** [comment]
@RAJU2529 Hi, Storage Sense is used to manage disk space. Please see [Manage drive space with Storage Sense](https://support.microsoft.com/en-us/windows/manage-drive-space-with-storage-sense-654f6ada-7bfc-45e5-966b-e24aded96ad5).

**Comment by Deland-Han** [comment]
Hi, if there is no further question on this article, I would like to close this issue. Thanks.

**Comment by RAJU2529** [comment]
Thanks sir. I am closing from side
