### ISSUE TITLE
Azure AD Joined VM troubleshooting required

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/SupportArticles-docs#598]
This needs updating for Azure AD joined VMs as we're having this issue with Azure Virtual Desktop when trying to log in with Azure AD credentials

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377e7e7f-c07e-3c69-06b2-49af12f83cc3
* Version Independent ID: 71b277ef-9f51-c926-f5cf-f41fce49b845
* Content: [Troubleshoot authentication errors when you use RDP to connect to Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-connect-rdp-azure-vm)
* Content Source: [support/azure/virtual-machines/cannot-connect-rdp-azure-vm.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/cannot-connect-rdp-azure-vm.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@OffColour, Thanks for your comments. We will consider adding the topic about AAD joined VMs. If you still have issue with RDP, I suggest you contact [Azure support](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to resolve the issue quickly.
