### ISSUE TITLE
Page is missing Azure PowerShell client appId

### ISSUE THREAD

**Issue by dcaro** [MicrosoftDocs/SupportArticles-docs#599]
The table on this page is missing the client appId for Azure PowerShell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e802fb-c215-598b-cf7d-b2536d3d6cfb
* Version Independent ID: 927037ea-324a-8ae5-c64e-1683d67d00b7
* Content: [Verify first-party Microsoft applications in sign-in reports - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in)
* Content Source: [support/azure/active-directory/verify-first-party-apps-sign-in.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/verify-first-party-apps-sign-in.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@dcaro, Thanks for the comments. The article doesn't list all the first-party Microsoft applications. It just lists some of them as examples. 

To verify if a sign-in application is first party Microsoft application, we can visit the [AAD Enterprise Applications blade] (https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/AllApps/menuId/) in the Azure portal, and set **Application Type** filter to  **Microsoft Applications**.

**Comment by dcaro** [comment]
Thanks, since Azure PowerShell is a popular app, it may make sense to add it.

**Comment by genlin** [comment]
@dcaro, Agreed with you. I will add the app id for Azure PowerShell.
