### ISSUE TITLE
wsus maintenance guide invalid link to reindex T-SQL script

### ISSUE THREAD

**Issue by Nascentes** [MicrosoftDocs/SupportArticles-docs#6]
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/mem/configmgr/wsus-maintenance-guide.md

Link to Reindex script under Step 3 is no longer valid. I would suggest a replacement, but I can't actually find it.

**Comment by helenclu** [comment]
@Nascentes , thank you for your feedback! The link to script has been replaced with [https://docs.microsoft.com/troubleshoot/mem/configmgr/reindex-the-wsus-database](https://docs.microsoft.com/troubleshoot/mem/configmgr/reindex-the-wsus-database).
