### ISSUE TITLE
Instructions to disable WPAD does not fully disable WPAD

### ISSUE THREAD

**Issue by mrecek** [MicrosoftDocs/SupportArticles-docs#601]
The section labeled "How to disable WPAD" does not fully disable WPAD. I followed the instructions on a Windows 10 machine. However, I still see DNS queries from the computer searching through the machine's domain suffix search list (like "wpad.company.com").

My IT organization has been attempting to fully disable WPAD for some time now, but we still see these DNS queries no matter what we try (note: we've tried literarily everything you can find on the Internet, not just this official Microsoft article, to stop these WPAD queries from occurring).

**Comment by Deland-Han** [comment]
Hi @mrecek, are you referring to the article [How to disable HTTP proxy features](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/disable-http-proxy-auth-features)?

**Comment by theITcloudAdmn** [comment]
Hi @Deland-Han, exactly that's the article. I'm experiencing the same like @mrecek: I have set the registry key as described in the article (HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp\DisableWpad DWORD value 1) but however still see DNS queries to wpad.
![grafik](https://user-images.githubusercontent.com/111881779/186165727-5b0a57f0-9074-40c0-bf42-da9cb3842ef6.png)

The only thing that seems to stop those queries is to edit the hosts file (c:\windows\system32\drivers\etc\hosts) like this:
![grafik](https://user-images.githubusercontent.com/111881779/186166041-60f8097b-db53-4f96-8c4d-06edbce5d1b2.png)

**Comment by Deland-Han** [comment]
Hi @theITcloudAdmn, this article applies to `Windows Server 2022, all editions, Windows 11, all editions`. So, it is expected that it does not work on Windows 10.

As it mentioned:

> Starting in Windows Server 2022 and Windows 11, ....

**Comment by theITcloudAdmn** [comment]
Hi @Deland-Han, yes but the relevant section "How to disable WPAD" (https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/disable-http-proxy-auth-features#how-to-disable-wpad) applies to `Windows Server 2019 and Windows 10, version 1809`
![grafik](https://user-images.githubusercontent.com/111881779/186351483-b46d3319-42af-4691-b84d-cc9176bb84a5.png)

I'm working with the latest version of Windows 10 (21H2).

**Comment by Deland-Han** [comment]
Hi @theITcloudAdmn, thank you for sharing the information.

I have had a talk with our engineers. This registry key setting should work in Windows 10. However, some applications or Windows components could also cause WPAD queries. Just for test purpose, you can also try to turn off the **Automatically detect settings** option under **Settings** > **Network & internet** > **Proxy**.

As this GitHub issue is to collect feedbacks for Docs article, if you need further assistance, I'd suggest you contact our [support](https://support.microsoft.com/contactus) for help.

**Comment by Deland-Han** [comment]
Hi, I would close this issue if you do not have further comments with the article.
