### ISSUE TITLE
ADFS and IIS - IIS Not Used Since 2012

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/SupportArticles-docs#606]
[Enter feedback here]
ADFS does not use IIS anymore. So, the page should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cade2-3121-73ed-9504-856bd88551e1
* Version Independent ID: a5b16a13-0aac-ec1c-a640-5562ee344413
* Content: [A federated user is prompted unexpectedly to enter their work or school account credentials - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/federated-user-prompt-enter-credentials)
* Content Source: [support/azure/active-directory/federated-user-prompt-enter-credentials.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/federated-user-prompt-enter-credentials.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@matziq, Thanks for the feedback. We will review and update the article.
