### ISSUE TITLE
Folder not correct

### ISSUE THREAD

**Issue by v-asymes** [MicrosoftDocs/SupportArticles-docs#613]
Vmware to Azure folder seem to be incorrect compared to other URL
From the Document: 
Exclude the installation path of the Azure Site Recovery agent, which is C:\Program Files(x86)\Azure Site Recovery by default.
Exclude the installation path of the Recovery Services agent, which is C:\Program Files\Microsoft Azure Recovery Services Agent by default.

Compare to url below:
https://docs.microsoft.com/en-us/azure/site-recovery/vmware-azure-set-up-source#if-antivirus-software-is-active-on-configuration-server

document says : C:\Program Files (x86)\Azure Site Recovery
missing Microsoft
 should be C:\Program Files (x86)\**Microsoft** Azure Site Recovery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66969db6-705c-7c0d-0e02-0f971b1eed1a
* Version Independent ID: fe1bbc8e-4755-9bef-5584-1170d27ae1f6
* Content: [Recommended antivirus exclusions for Azure Recovery Services - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/site-recovery/asr-recommended-antivirus-exclusions)
* Content Source: [support/azure/site-recovery/asr-recommended-antivirus-exclusions.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/site-recovery/asr-recommended-antivirus-exclusions.md)
* Service: **site-recovery**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@v-asymes Thanks for the feedback. I will fix the issue in the article.

**Comment by v-pgaddala** [comment]
Info is live.

**Comment by v-pgaddala** [comment]
#please-close
