### ISSUE TITLE
May also see an ignorable volmgr event 2 "Failed to read KSR data - disk x sector xxx operation 0 status c0000225."

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/SupportArticles-docs#614]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0fddc6-bed4-d20a-125f-591784549432
* Version Independent ID: 7e0fddc6-bed4-d20a-125f-591784549432
* Content: [Kernel Soft Reboot error c0000034 - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/azure-stack-hci-kernel-soft-reboot-error-c0000034)
* Content Source: [support/azure/general/azure-stack-hci-kernel-soft-reboot-error-c0000034.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/azure-stack-hci-kernel-soft-reboot-error-c0000034.md)
* Service: **azure-stack**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@stephc-msft, thanks for the feedback. I will email you offline for discussing this issue.
