### ISSUE TITLE
Cause 3 - Firewall Isn't Running

### ISSUE THREAD

**Issue by stryqx** [MicrosoftDocs/SupportArticles-docs#617]
Hit a fun third cause for blocked inbound traffic this last week - Windows Defender Firewall doesn't start up after administrative language settings are changed for the Welcome Screen and System Accounts and the VM is rebooted.
Unfortunately none of the built-in troubleshooters to the VM or the Azure troubleshooters pick up on the fact that the Firewall isn't running. Installing the VMaccess extension as part of resetting RDP configuration died horribly as it assumes the Firewall is running and dies trying to update the firewall rules. Thankfully in this scenario outbound traffic still works and I had my RMM agent installed so I was able to remotely diagnose the problem without being sidetracked by the useless output of the Microsoft-supplied troubleshooters.
The quickest most effective solution to this problem was to run Windows Update, re-apply the latest CU and reboot. After this reboot Windows Defender Firewall started correctly. From memory this is a known side effect of language changes, yet nothing seems to check this as a possible cause.

**Comment by genlin** [comment]
@stryqx  Thanks for sharing the solution.
