### ISSUE TITLE
cpu-usage-exceeds-100: 50% of 50% are a quarter, not a half

### ISSUE THREAD

**Issue by datto-cschulze** [MicrosoftDocs/SupportArticles-docs#620]
> A processor that's running 50% of the time and clocked down to 50% frequency performs only half the work of a processor that's running 100% of the time at 100% frequency.
If a processors runs half of the time and in addition is only running at half speed, it would only do a quarter of the work it could do, if it were running all the time at full speed. At least my dusty math skills tell me that 🙂

https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-client/performance/cpu-usage-exceeds-100.md
https://docs.microsoft.com/en-us/troubleshoot/windows-client/performance/cpu-usage-exceeds-100

**Comment by Deland-Han** [comment]
Hi @datto-cschulze,

I think it should be a typo. The first `50%` should be `100%`. I will correct it. Thanks for the feedback.
