### ISSUE TITLE
Steps to tcpdump from AKS Linux node are unclear

### ISSUE THREAD

**Issue by mateuszdrab** [MicrosoftDocs/SupportArticles-docs#621]
Hi team

The steps in this article don't seem to make much sense.

The process described about setting up ssh keys to the node, connecting via ssh, running tcpdump and suddenly out of nowhere talks about pulling the file from the 'debug' pod. A debug pod is another technique to access the nodes, which requires a command not mentioned in the instructions and is an alternative to SSH. 

This article needs to be updated to have two main sections:
- Capturing from the node by connecting though SSH
- Capturing from the node by using a debug pod

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Version Independent ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Content: [Capture a TCP dump from a Linux node in an AKS cluster - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks)
* Content Source: [support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md)
* Service: **container-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
@mateuszdrab We removed the text about using SSH to connect to the node, so hopefully the instructions are less confusing for you now.
