### ISSUE TITLE
Update page for azkms.core.windows.net endpoint.

### ISSUE THREAD

**Issue by pebarrer** [MicrosoftDocs/SupportArticles-docs#625]
Azure KMS now has two endpoints are documented here: 

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-activation-problems#understanding-azure-kms-endpoints-for-windows-product-activation-of-azure-virtual-machines

Please update this page to reflect the new endpoint azkms.core.windows.net.

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@pebarrer, thanks for the feedback. I will submit a PR to update the article.
