### ISSUE TITLE
DPM - Cannot Comminucate With Agent 

### ISSUE THREAD

**Issue by jbooze1996** [MicrosoftDocs/SupportArticles-docs#627]
Hello, I am having the following issue with our Data Protention Manager backup center:

Occurred since:	7/6/2022 2:04:03 AM
Description: Since Wednesday, July 06, 2022 2:04:03 AM, synchronization jobs for C:\ on BACKUP1.WMMHC.loc have failed. The total number of failed jobs = 1. The last job failed for the following reason: (ID 3115)
DPM failed to communicate with the protection agent on BACKUP1.WMMHC.loc because access is denied. (ID 42 Details: Access is denied (0x80070005))
	
This is one of the errors we are getting. This is just an example, as we have other servers we are trying to backup that are throwing up the same error. I beleive this is the main one as the agents on the servers we back cannot be accessed for some reason. If someone can help as to the next step to understand and resolve this, it would be greaty appreciated. Let me know what further information we need.  Thanks you!

**Comment by helenclu** [comment]
@jbooze1996 , I'd recommend that you contact Microsoft Support and submit a service request for this issue.
