### ISSUE TITLE
Add a restart to the uninstall procedure

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#628]
Hello team.  I would recommend adding an OS restart to the uninstall/reinstall procedure between steps 6 and 7 below.  The reason is that sometimes the services get into a strange state after running the delete commands where they are disabled and marked for deletion, but still present in services.msc.  If you don't restart and then install the new .msi right away, they're still in that strange state.  But if you restart between steps 6 and 7, they get cleaned up and then you can proceed with the install successfully.  Thanks.  

6.  Move any folders that are named Packages or GuestAgent into the OLD folder.

Should add a restart here.  

7.  Download and install the latest version of the agent installation package from [here](https://go.microsoft.com/fwlink/?linkid=394789&clcid=0x409). You must have Administrator rights to complete the installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95825442-ec08-fcdd-76bd-cc0694b6b913
* Version Independent ID: 11a97acc-d077-3bac-9411-8199bd98b255
* Content: [Troubleshooting Azure Windows VM Agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent?source=docs)
* Content Source: [support/azure/virtual-machines/windows-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/windows-azure-guest-agent.md)
* Service: **virtual-machines**
* GitHub Login: @dkdiksha
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver, Thanks for the feedback. I will the restart step into the article.
