### ISSUE TITLE
azkms.core.windows.net

### ISSUE THREAD

**Issue by mveeuwen** [MicrosoftDocs/SupportArticles-docs#629]
I noticed that new servers are deployed with azkms.core.windows.net:1688. 

The following article is updated with azkms on juli 1st
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-activation-problems#understanding-azure-kms-endpoints-for-windows-product-activation-of-azure-virtual-machines 

Please add the new azkms here too.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@pebarrer, Thanks for the feedback. This issue is same as the [issue 625](https://github.com/MicrosoftDocs/SupportArticles-docs/issues/625). I will close this one. Feel free to let me know if there is a problem.
