### ISSUE TITLE
Remove Linebreak before IgnoreFailures in code sample

### ISSUE THREAD

**Issue by b5lurker** [MicrosoftDocs/SupportArticles-docs#633]
Code sample for XMLA command to delete a database does not work with the linebreak as it is shown/copied from the code sample. Need to remove that linebreak and then the command works as shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26211e2-9250-fbdf-e6f4-b41ffc1ae74e
* Version Independent ID: 92a7b620-d5fd-58ad-631f-82b0ada3c117
* Content: [Delete a corrupted Azure Analysis Services database - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/delete-corrupted-azure-analysis-services-database)
* Content Source: [support/azure/general/delete-corrupted-azure-analysis-services-database.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/delete-corrupted-azure-analysis-services-database.md)
* Service: **azure**
* GitHub Login: @ramakoni1
* Microsoft Alias: **ramakoni**

**Comment by genlin** [comment]
@b5lurker, Thanks for the feedback. I will fix the format issue.

**Comment by genlin** [comment]
@b5lurker, The article is updated. I will close this issue. Feel free to let me know if there is additional comment or problem.
