### ISSUE TITLE
Link to ADFSSecAuditParse.ps1 not working.

### ISSUE THREAD

**Issue by angsknarren** [MicrosoftDocs/SupportArticles-docs#64]
The link to ADFSSecAuditParse.ps1 is not working since the scriptcenter is closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b71a84-d7c7-8994-880b-6c7aaf58b1aa
* Version Independent ID: 99d9e5e0-dff2-4710-5c40-6aa05b621a5a
* Content: [Troubleshoot account lockout in AD FS on Windows Server - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/account-lockout-adfs-window-server)
* Content Source: [support/azure/active-directory/account-lockout-adfs-window-server.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/account-lockout-adfs-window-server.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@angsknarren, I jsut found the script files. The codes have been pasted into the article:

[ADFSSecAuditParse.ps1 ](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/account-lockout-adfs-window-server#adfs-security-audit-events-parser)

I will process to close this issue. Feel free to let me know if there is any additional comment.

**Comment by genlin** [comment]
@angsknarren, I jsut found the script files, and pasted the code into the article:

[](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/account-lockout-adfs-window-server#adfs-security-audit-events-parser)
