### ISSUE TITLE
azkms.core.windows.net is not a static IP and will not consistently allow customers to configure force tunneling for activation as described in the docs

### ISSUE THREAD

**Issue by cameron-doherty** [MicrosoftDocs/SupportArticles-docs#640]
The URL to IP mapping for Azure Global azkms.core.windows.net is incorrect and the returned IP is dependent upon your geographical location. See DIG output below:

```
;; ANSWER SECTION:
azkms.core.windows.net. 0       IN      CNAME   cps-accqwtr64onoo-tm.trafficmanager.net.
cps-accqwtr64onoo-tm.trafficmanager.net. 0 IN CNAME cps-kms.westus.cloudapp.azure.com.
cps-kms.westus.cloudapp.azure.com. 0 IN A       40.83.235.53 
```

If this URL is fronted by traffic manager for global load balancing it would not be possible to reliably force tunnel traffic using this configuration as the IP addresses would change.  If its acceptable for customers to use the final record of `cps-kms.<region>.cloudapp.azure.com` then the documentation should reflect that or at least NOTE the nuanced difference to ensure their Windows Activation process is uninterrupted when using forced tunneling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by mimckitt** [comment]
Thanks for the feedback. I am checking with our engineering team now. 

#assign: @mimckitt

**Comment by danielli90** [comment]
@cameron-doherty is correct. azkms.core.windows.net is supported by a Traffic Manager which hosts only two IP addresses published in the documentation. Therefore the documentation recommends customers to create custom route for both IP addresses. @cameron-doherty , does that address your concern?
