### ISSUE TITLE
Incorrect IP addresses within document for azkms.core.windows.net

### ISSUE THREAD

**Issue by acmcomputers** [MicrosoftDocs/SupportArticles-docs#642]
[Enter feedback here]

When reviewing the document and table within the article, the IP address for azkms.core.windows.net states that it is: 20.118.99.244
(this IP has been written in two places)

When reviewing the powershell code that applies the required routes, the IP is listed as: 20.118.99.224/32

When performing a DNS lookup, it shows the code is correct with an IP address of 20.118.99.224 but the documented IP within the table and article is INCORRECT.

Please update and advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by AmandaAZ** [comment]
@acmcomputers Thanks for your feedback. We will review and update this article.

**Comment by genlin** [comment]
@acmcomputers， We have update the IP address in the article. Thank you!
