### ISSUE TITLE
Attaching the Disk to Repair as part of VM Creation can result in unexpected boot behaviour

### ISSUE THREAD

**Issue by stryqx** [MicrosoftDocs/SupportArticles-docs#643]
In the section "Create a repair VM with the new disk attached as a data disk" (https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-recovery-disks-portal-windows#create-a-repair-vm-with-the-new-disk-attached-as-a-data-disk):
- attaching the disk to repair as a data disk as part of VM creation can result in VM provisioning failure with a provisioning timeout error.
- this occurs as the data disk is being used as the boot disk, rather than as the data disk to perform the offline operations on
- starting the VM will take a long time, and a resultant connection to the VM will be as though you've connected to the VM you're trying to fix.
The reliable process is to:
- create the Repair VM
- start and connect to the Repair VM, ensuring the Repair VM is operating correctly
- attach the disk to repair as a data disk
- connect to the Repair VM, ensuring the data disk is not being used as the boot disk - verifiable by ensuring the Repair VM hostname is the same as the computer name in the VM Properties

**Comment by AmandaAZ** [comment]
@stryqx Thanks for your contribution. We will review your suggestions and make the necessary updates.

**Comment by AmandaAZ** [comment]
@stryqx The article is republished with the necessary changes. Thanks for your contribution!
