### ISSUE TITLE
Adding troubleshooting guidance for VMs from DevTest Labs

### ISSUE THREAD

**Issue by miguelsolorio** [MicrosoftDocs/SupportArticles-docs#645]
I was having trouble connecting to my DevTest Lab VM on Linux and found this supporting article but there was no mention of how to troubleshoot for a DevTest Lab VM, which does not show the full options of the VM like a regular resource https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/connect-linux-vm-sshconnection

<img width="332" alt="CleanShot 2022-07-14 at 08 49 39@2x" src="https://user-images.githubusercontent.com/35271042/179023906-d9045e22-e4da-450a-8e83-26a9b181d88d.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1f172d-5ace-c96c-bd08-cdcb49ab30e6
* Version Independent ID: 947423a3-3a61-399f-c0b2-df58aaf7a70a
* Content: [Can't connect a Linux VM using SSH connection - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/connect-linux-vm-sshconnection)
* Content Source: [support/azure/virtual-machines/connect-linux-vm-sshconnection.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/connect-linux-vm-sshconnection.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by AmandaAZ** [comment]
@misolori To troubleshoot the connection issue with a DevTest Lab VM, you can contact the Azure experts on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). You also contact [Azure support](https://portal.azure.com/) to resolve the issue quickly: Go to the Azure support and select Help + support.
