### ISSUE TITLE
Rescue VM file system layout?

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#647]
Hello, team.  I just wanted to get some additional clarification on the Rescue VM File System Layout that we should be using when mount an LVM OS disk for repair.  

The article says that "Usually a rescue VM of the same or similar Operating system version is recommended." - Does this mean I should also choose a rescue VM with LVM on the OS disk?  In the article, the screenshot for when lsblk was run seems to indicate that a rescue VM was selected that does not have LVM on the OS disk.  or should we avoid a rescue VM with LVM as that could create additional problems if the disk layouts are identical as they would be if the same Marketplace image was uses?   

When I created a Rescue VM that does not have an LVM configuration, I had to install LVM tools using "sudo yum install lvm2" or else I couldn't successfully run the commands below.

vgscan --mknodes
vgchange -ay
lvscan

Perhaps we should include a chart like the one below that shows the different commands for installing lvm on the different distros? 

https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/configure-lvm?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json#install-the-lvm-utilities

![image](https://user-images.githubusercontent.com/39092497/179277107-db6e9732-01de-424e-8d30-252760e7985f.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f00a1d-522f-8974-fa22-7f637b991d8f
* Version Independent ID: dbf7659f-b6fa-f6ec-705e-b9de05d1d467
* Content: [Recover Linux VMs using chroot where LVM (Logical Volume Manager) is used - Azure VMs - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/chroot-logical-volume-manager)
* Content Source: [support/azure/virtual-machines/chroot-logical-volume-manager.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/chroot-logical-volume-manager.md)
* Service: **virtual-machines**
* GitHub Login: @vilibert
* Microsoft Alias: **vilibert**

**Comment by mbiver** [comment]
Perhaps just adding a comment similar to ...  "Don’t use LVM Rescue VM to repair another LVM image, Use a rescue VM with Raw image instead and make sure is the same OS Distro."

**Comment by genlin** [comment]
@mbiver  We launched a new feedback experience in learn.microsoft.com. As a result, the issue feature in GitHub will be closed. We appreciate your feedback and suggestions, and we encourage you to propose any changes in the new feedback experience or  submitting a pull request.

**Comment by genlin** [comment]
@Kyle Jones
