### ISSUE TITLE
Add link to LVM Rescue VM Article?

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#648]
Hello, team.  Something minor here, but could help some inexperienced Linux users (myself included).  In the Repair the VM offline section of this document...

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors#repair-the-vm-offline

Perhaps we could mention something about if the OS disk is setup with LVM file system navigate to the link below for mounting an LVM disk offline to a Rescue VM?  

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/chroot-logical-volume-manager

Just a thought, thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576725c0-f50a-d686-2213-7da506bc63c2
* Version Independent ID: aa284cac-7e07-c916-58fa-ac329b838803
* Content: [Troubleshoot Linux VM starting issues due to fstab errors - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors)
* Content Source: [support/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver Thanks for the suggestion. I will consider to add more information for this topic.

**Comment by AmandaAZ** [comment]
@mbiver The information is added to [the article](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-virtual-machine-cannot-start-fstab-errors#use-manual-method). Thanks for your contribution.
