### ISSUE TITLE
Hex and Dec values are not clear

### ISSUE THREAD

**Issue by chardog** [MicrosoftDocs/SupportArticles-docs#65]
This page: https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-client/system-management-components/0x80041323-running-scheduled-tasks.md  mentions the mins, defaults, and maxes for the registry keys in decimal value.

It instructs you to type in "1000" as a decimal in the value boxes.  If you look at the articles it links to at the bottom, they talk about the defaults as "64" which is a hex value, which is 100 in decimal.  https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd363733(v=ws.10) and https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd363705(v=ws.10)

These pages should all explicitly state if you are talking HEX or DEC.

**Comment by Deland-Han** [comment]
Thank you for the feedback  @chardog. I have added "Decimal" to these values in the article.
