### ISSUE TITLE
Update the example to include the use of the ALAR v1 (the bash scripts not the rust scripts)

### ISSUE THREAD

**Issue by imabedalghafer** [MicrosoftDocs/SupportArticles-docs#650]
Can you please add another example, where we can use the version 1 of alar not version 2, as with new vm-repair release there is a new option to use other distros (like RHEL, and SLES) where those the script to prepare the rust environment is not ready on them.

An example to use version 1 is:
az vm repair run -g myRG -n myVM --run-id linux-alar-fki --parameters initrd --run-on-repair

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a16efa-1d65-daa2-3add-12e0314ae900
* Version Independent ID: 440a1711-03a8-f50c-1aba-049168ebffa7
* Content: [Repair a Linux VM automatically with the help of ALAR - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-linux-vm-using-alar)
* Content Source: [support/azure/virtual-machines/repair-linux-vm-using-ALAR.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-linux-vm-using-ALAR.md)
* Service: **virtual-machines**
* GitHub Login: @malachma
* Microsoft Alias: **malachma**

**Comment by malachma** [comment]
v1 isn't maintained anymore. The use of other distros is also not supported.
