### ISSUE TITLE
Redirection from Microsoft Support should match Docs's conventions

### ISSUE THREAD

**Issue by Lemmingh** [MicrosoftDocs/SupportArticles-docs#658]
Let's take **KB 4494446** as an example. Here is a one-time inspection script:

```powershell
#Requires -Version 7

$RequestUri = 'https://support.microsoft.com/en-us/help/4494446'

$Handler = [System.Net.Http.HttpClientHandler]::new()
$Handler.AllowAutoRedirect = $false
$Client = [System.Net.Http.HttpClient]::new($Handler)
$Client.DefaultRequestHeaders.ConnectionClose = $true

$Response = $Client.GetAsync(
    $RequestUri,
    [System.Net.Http.HttpCompletionOption]::ResponseHeadersRead
).Result

'HTTP/1.1 {0:D} {1}' -f $Response.StatusCode, $($Response.ReasonPhrase ?? $Response.StatusCode)
$Response.Headers.ToString()
```

```http
HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network
```

Evidently, we are redirected to:

```uri
https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network
```

However, its canonical location on Microsoft Docs is all **lower** case:

```uri
https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network
```

Given that [the path component of a URI is case-sensitive](<https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.1>), they are recognized as different resources by browsers, causing trouble in browsing history, bookmarks, etc.

I believe some corrections should be made to `support.microsoft.com`. I don't know how to contact the relevant team, so post the request here. Thank you.

**Comment by ChristySu** [comment]
Thanks for raising this. We shared this with the relevant team who will investigate and make the necessary updates.

**Comment by ChristySu** [comment]
#please-close
