### ISSUE TITLE
/v option on bcdedit

### ISSUE THREAD

**Issue by anmocanu** [MicrosoftDocs/SupportArticles-docs#659]
Hi team, 

as I've had a case with this issue recently, the resolution mentioned here: 
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-error-0xc0000225#error-2-repair-the-boot-configuration-data 
didn't work on my side because command from step 6: 
"bcdedit /store < Boot partition >:\boot\bcd /enum" renders the Windows Boot Loader Identifier as {default} and this is misleading.  

Can we please update it to be like this "bcdedit /store < Boot partition >:\boot\bcd /enum /v"

On CSS side I have also updated our DevOps Wikis to reflect this change, but we also need this for the public documents available.

Thank you!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a247c8d8-c802-a907-a356-6c1d0fcd8223
* Version Independent ID: cd6177af-6421-8a70-e8fe-3c2244c0a6a1
* Content: [Windows boot error 0xc0000225 on an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-error-0xc0000225?source=docs)
* Content Source: [support/azure/virtual-machines/boot-error-0xc0000225.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/boot-error-0xc0000225.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@anmocanu, Thanks for the feedback. I will update the article.
