### ISSUE TITLE
Domain name change for serial console

### ISSUE THREAD

**Issue by glimoli** [MicrosoftDocs/SupportArticles-docs#660]
Hi team, on the cell that explains what to do when the client-side error is "Web socket is closed or could not be opened.", it is pointed out to enable "*.console.azure.com" on the customer firewall however, lately we are finding there was a domain name change on this and now the entry that needs to be added on the firewall is "*.serialconsole.azure.com".

Can this be updated? Also, can you notify all the customers about this? we are having support volume getting raised due to this.

Thanks.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7579df88-20c0-3b86-dcd3-50c4a3ff8da7
* Version Independent ID: 6fc4aa33-9ca4-e3c6-6e62-393142880647
* Content: [Azure Serial Console errors - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-errors)
* Content Source: [support/azure/virtual-machines/serial-console-errors.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-errors.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@glimoli, I will update the article as soon as possible.
