### ISSUE TITLE
Known Issue Rollback article conflicts with ADMX policy documentation

### ISSUE THREAD

**Issue by dmichine** [MicrosoftDocs/SupportArticles-docs#663]
Known issue rollback article indicates that you can deploy the policy via an Intune ADMX backed policy.

https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/use-group-policy-to-deploy-known-issue-rollback#2-create-a-custom-configuration-profile-in-microsoft-endpoint-manager

However KIR registry keys in the ADMX backed policies are located under HKLM:\System (SYSTEM\CurrentControlSet\Policies\Microsoft\FeatureManagement\Overrides)

As per the following article ingested policies are not allowed to write to locations under HKLM:\System https://docs.microsoft.com/en-us/windows/client-management/mdm/win32-and-centennial-app-policy-configuration

Deploying ADMX file to machines running 21H2 (19044.1926) results in the following error.
![image](https://user-images.githubusercontent.com/19422332/181390620-913a60c4-ffe8-443f-9783-ea7f45b1667f.png)

Can the Known Issue Rollback deployment article be updated please?

**Comment by Deland-Han** [comment]
Thank you for your feedback. We are investigating this issue, and I will reply later.

**Comment by Deland-Han** [comment]
@dmichine This solution only works after the July 26, 2022 CU is installed. I will add a note to the article. Thank you for the feedback.
