### ISSUE TITLE
mggraph filter changed

### ISSUE THREAD

**Issue by debaxtermsft** [MicrosoftDocs/SupportArticles-docs#668]
$signInsNonInteractive = Get-MgAuditLogSignIn -Filter ($clauses[0,1,3] -Join " and ") -All
Get-MgAuditLogSignIn : Invalid filter clause
At line:1 char:1
+ $signInsNonInteractive = Get-MgAuditLogSignIn -Filter ($clauses[0,1,3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 100, Sk...ndProperty =  }:<>f__AnonymousType2`8) [Get-MgAuditLogSignIn_List], RestException`1
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List
    
 $signInsInteractive = Get-MgAuditLogSignIn -Filter ($clauses[0,3] -Join " and ") -All
Get-MgAuditLogSignIn : Invalid filter clause
At line:1 char:1
+ $signInsInteractive = Get-MgAuditLogSignIn -Filter ($clauses[0,3] -Jo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 100, Sk...ndProperty =  }:<>f__AnonymousType2`8) [Get-MgAuditLogSignIn_List], RestException`1
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List
    
$signInsWorkloadIdentities = Get-MgAuditLogSignIn -Filter ($clauses[0,2,3] -Join " and ") -All
Get-MgAuditLogSignIn : Invalid filter clause
At line:1 char:1
+ $signInsWorkloadIdentities = Get-MgAuditLogSignIn -Filter ($clauses[0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 100, Sk...ndProperty =  }:<>f__AnonymousType2`8) [Get-MgAuditLogSignIn_List], RestException`1
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List
    
The Get-MgAuditLogSignIn no longer allows the filters for :
    "signInEventTypes/any(t: t eq 'nonInteractiveUser')",
    "signInEventTypes/any(t: t eq 'servicePrincipal')",
    "(authenticationProcessingDetails/any($procDetailFunction))"
    
    createdDateTime works just fine, the others do not.
    
    Also AuthenticationProcessingDetails was removed as a member??
    
    AdditionalProperties             Property              System.Collections.Generic.IDictionary[string,System.Object] AdditionalProperties {get;}
AppDisplayName                   Property              string AppDisplayName {get;set;}
AppId                            Property              string AppId {get;set;}
AppliedConditionalAccessPolicies Property              Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAppliedConditionalAccessPolicy[] AppliedConditionalAccessPolicies {get;set;}
Clear                            Method                void Clear(), void IAssociativeArray[Object].Clear()
ClientAppUsed                    Property              string ClientAppUsed {get;set;}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=powershell)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Handling this one offline.
