### ISSUE TITLE
Duplicate Page

### ISSUE THREAD

**Issue by ewierenga** [MicrosoftDocs/SupportArticles-docs#669]
There is a duplicate page in the Azure Active Directory troubleshooting documentation (https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/welcome-azure-ad)

Under Sign-In and Multi-factor Authentication, there is a page called "Troubleshoot MFA issues" and "Troubleshooting MFA issues" right next to each other. They both lead to the URL https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/troubleshoot-azure-mfa-issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7f8fe5-7372-8cda-b6c2-2a9d63708125
* Version Independent ID: ed3a856c-66e9-05f2-d707-cde9ef0c3a3e
* Content: [Troubleshoot Azure Multi-Factor Authentication issues - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/troubleshoot-azure-mfa-issue)
* Content Source: [support/azure/active-directory/troubleshoot-azure-mfa-issue.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/troubleshoot-azure-mfa-issue.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ewierenga, Thanks for the feedback. I will fix the issue.
