### ISSUE TITLE
Document that the curl invocation can only be executed as root

### ISSUE THREAD

**Issue by tillc24** [MicrosoftDocs/SupportArticles-docs#670]
We encountered a condition where our VM was unable to reach the wireserver IP address and used the curl tests from this page.  Unfortunately not until working with Microsoft Support did we identify that the curl function MUST be invoked as "root".  curl tests using non-root accounts will fail.   As such that documentation should be updated so that it minimally includes the footnote to try this connectivity test using the root account (or using sudo).

This one piece of information would have saved us considerable time troubleshooting this condition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a93bbc-42bb-f430-a346-71a0c94180e4
* Version Independent ID: b1c648c1-aa0b-bbb4-ac27-5f3c1ebd9221
* Content: [Troubleshoot the Azure Linux Agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-azure-guest-agent#advanced-troubleshooting)
* Content Source: [support/azure/virtual-machines/linux-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-azure-guest-agent.md)
* Service: **virtual-machines**
* GitHub Login: @axelg
* Microsoft Alias: **axelg**

**Comment by genlin** [comment]
@tillc24, Thanks for the valuable feedback. I will add a note about the root account.
