### ISSUE TITLE
Doc dns-server-cache-snooping-attacks has non-working URL

### ISSUE THREAD

**Issue by ToddMaxey** [MicrosoftDocs/SupportArticles-docs#671]
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/networking/dns-server-cache-snooping-attacks.md#symptoms

The URL has changed to https://simpledns.plus/kb/152/what-is-dns-cache-snooping-and-how-do-i-prevent-it

**Comment by Deland-Han** [comment]
Thanks. @ToddMaxey. I have updated the link.
