### ISSUE TITLE
Mapped network drive may fail to reconnect: Typo and known bug in Workaround 2

### ISSUE THREAD

**Issue by Eddga** [MicrosoftDocs/SupportArticles-docs#678]
I have have found two issues in the documentation about [Mapped network drive may fail to reconnect in Windows 10, version 1809 - Workaround 2: Create a scheduled task](https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/mapped-network-drive-fail-reconnect#workaround-2-create-a-scheduled-task).

1. There is a typo at step 8 where it says what to put into the arguments field. It says `-window_s_style hidden ...` but should be `-windowstyle hidden ...`
2. There should be a !Note at the beginning of Workaround 2 warning the user that the windowstyle parameter is currently bugged and using `-windowstyle hidden` will still leave you with a powershell console window flashing up for a short period whenever the task is run. See [Powershell -WindowStyle Hidden still shows a window briefly](https://github.com/PowerShell/PowerShell/issues/3028#top)
 for details.

Kind Regards
Eddga

**Comment by Deland-Han** [comment]
@Eddga. Thank you for the feedback. I have modified the article.
