### ISSUE TITLE
Script for cloud shell

### ISSUE THREAD

**Issue by rumenavramov** [MicrosoftDocs/SupportArticles-docs#68]
It would be very convenient if the script for https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-bitlocker-boot-error#key-encryption-key-scenario could be executed in cloud shell. Right now it tries to load some stuff from Program Files, but you can probably update it or create an alternative version that runs in Cloud Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72043177-4ad8-7261-ba13-3d7b14c76a14
* Version Independent ID: a9ee0e02-325d-256e-4f20-18df23962002
* Content: [Troubleshooting BitLocker boot errors on an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-bitlocker-boot-error)
* Content Source: [support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by rjmccallumbigl** [comment]
Hey @rumenavramov, az vm repair can automatically unlock a disk encrypted with single pass encryption: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands

**Comment by genlin** [comment]
@rumenavramov Thank you for your feedback. We will investigate if it is possible to run the script to cloud shell.

**Comment by genlin** [comment]
@rumenavramov We can running the script in Cloud shell by uploading the ADAL Assemblies. But we still need to attach the OSdisk into a recovery VM, then use the unlock key to unlock the VM. So I think running the script directly in the recovery VM would be more effective. Thanks for your suggestion.
