### ISSUE TITLE
bad path in command

### ISSUE THREAD

**Issue by Arne-RFA** [MicrosoftDocs/SupportArticles-docs#680]
[Enter feedback here]

md C:\Temp
gpresult /h C:\Temp\GPreport.htm
start GPreport.htm

The above will not work, the below is a simple fix

md C:\Temp
gpresult /h C:\Temp\GPreport.htm
start C:\Temp\GPreport.htm
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad476cdc-6ee4-3472-a61d-716848959b4c
* Version Independent ID: ad476cdc-6ee4-3472-a61d-716848959b4c
* Content: [SSPR_0029 - Your organization hasn't properly set up the on-premises configuration for password reset - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/password-writeback-error-code-sspr-0029)
* Content Source: [support/azure/active-directory/password-writeback-error-code-sspr-0029.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/password-writeback-error-code-sspr-0029.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Hi @Arne-RFA, thanks for the report. We'll have this fix incorporated into the article soon.

**Comment by DennisLee-DennisLee** [comment]
@Arne-RFA I've made the fix in <https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/password-writeback-error-code-sspr-0029>. Thanks for the suggestion!
