### ISSUE TITLE
Boot Diagnostics/Serial Console vs Custom Storage Account Firewall

### ISSUE THREAD

**Issue by ems75** [MicrosoftDocs/SupportArticles-docs#682]
This page mentions that "Serial Console is now compatible with managed boot diagnostics storage accounts and **custom storage account firewalls**". However, this [page ](https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#boot-diagnostics-storage-account) mentions that "User managed storage accounts associated with boot diagnostics require the storage account and the associated virtual machines reside in the same region and subscription and **accessible from all networks.**"

As user managed account = custom storage account, those two articles contradict each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4dfc75-25a4-ae83-8d6a-00f267bf85b9
* Version Independent ID: faa41c37-7b66-671b-09ca-3fb076f701e3
* Content: [Azure Serial Console - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-overview)
* Content Source: [support/azure/virtual-machines/serial-console-overview.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-overview.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ems75, Serial console supports the firewall in the custom storage account. To use the firewall, we must add your client/browser IP and [Serial console services IPs]( https://docs.microsoft.com/troubleshoot/azure/virtual-machines/serial-console-linux#use-serial-console-with-custom-boot-diagnostics-storage-account-firewall-enabled)to the firewall allow list.

I will update the article to reflect the latest updates.

**Comment by jumaqsoo** [comment]
https://docs.microsoft.com/troubleshoot/azure/virtual-machines/serial-console-linux#use-serial-console-with-custom-boot-diagnostics-storage-account-firewall-enabled
This link doesnt contain IP's for Africa Region,

**Comment by genlin** [comment]
@jumaqsoo Thanks for the comment. We are still working on boot diagnostic firewall support for the SouthAfrica geography, including storage accounts in South Africa North. When this compatibility is available, we will update the documentation.
