### ISSUE TITLE
debian image need to use stable tag

### ISSUE THREAD

**Issue by MarcAntoineNiggemann** [MicrosoftDocs/SupportArticles-docs#684]
Hi,

It is proposed to start a debian pod to debug networking issue, but without specifying the tag of the debian image, it would search for a latest tag, which does not exists anymore.
Should specify stable tag :
# Start a test pod in the cluster:
kubectl run -it --rm aks-ssh --image=debian:stable

Regards,
Marc-Antoine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f8e43c-0c81-1507-6b08-a2451e75d90d
* Version Independent ID: c7f8e43c-0c81-1507-6b08-a2451e75d90d
* Content: [Fix connection issues to an app that's hosted on an AKS cluster - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/connection-issues-application-hosted-aks-cluster)
* Content Source: [support/azure/azure-kubernetes/connection-issues-application-hosted-aks-cluster.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/connection-issues-application-hosted-aks-cluster.md)
* Service: **container-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
@MarcAntoineNiggemann Thanks for the feedback. We will address this issue soon.

**Comment by DennisLee-DennisLee** [comment]
@MarcAntoineNiggemann The article has been updated to include your suggestion. Thanks again.
