### ISSUE TITLE
Add backup reminder in workaround

### ISSUE THREAD

**Issue by rsantosms** [MicrosoftDocs/SupportArticles-docs#685]
Hello!

An addition I think it's worthwhile to add to the workaround procedure - A reminder to create a backup before starting.

Cheers!

BR's
Ruben S

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@rsantosms, Agreed. I will add a backup reminder to the article.  Thanks for the feedback.

**Comment by genlin** [comment]
Fix https://github.com/MicrosoftDocs/SupportArticles-docs/issues/685

**Comment by rsantosms** [comment]
Thanks!
