### ISSUE TITLE
missing path

### ISSUE THREAD

**Issue by Martin-Simonsen** [MicrosoftDocs/SupportArticles-docs#687]
Shouldn't the path be reg query "HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters\LicenseServers" /v SpecifiedLicenseServers
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9d389b-d79b-6f2c-054a-11f0ceddf155
* Version Independent ID: fe09cade-19f3-db1a-aa2e-8ca214fd4e55
* Content: [The Remote Desktop license server isn't available when you connect to an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-no-license-server)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-no-license-server.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-no-license-server.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@Martin-Simonsen, Thanks for the feedback. I will update the article
