### ISSUE TITLE
az aks check-acr

### ISSUE THREAD

**Issue by ps68060** [MicrosoftDocs/SupportArticles-docs#688]
az aks check-acr ....

az aks: 'check-acr' is not in the 'az aks' command group. See 'az aks --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1557572b-65d8-9644-7d0e-9331ac6f75f1
* Version Independent ID: 1557572b-65d8-9644-7d0e-9331ac6f75f1
* Content: [Can't pull images from Azure Container Registry to Kubernetes - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster)
* Content Source: [support/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster.md)
* Service: **container-service**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ps68060, Thanks for the feedback. I will fix the issue.

**Comment by genlin** [comment]
@ps68060, I will process to close this issue. Feel free to reopen it if there is any additional question.
