### ISSUE TITLE
Wrong location used for this doc

### ISSUE THREAD

**Issue by malachma** [MicrosoftDocs/SupportArticles-docs#689]
During my review I haven't recognized that the location of this do isn't in the right location.
Please move this doc out of the current one. This doc needs to be stored under a new directory like 'Linux/Setup and Config'.
An incorrect multinic setup does not lead automatically to a non-connectivity scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9525eb3-1be7-449b-2b63-10bb1ec71f63
* Version Independent ID: d9525eb3-1be7-449b-2b63-10bb1ec71f63
* Content: [Configure multiple network interfaces in Azure Linux virtual machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration)
* Content Source: [support/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@malachma, Thanks for the comment. I will update the TOC.
