### ISSUE TITLE
Script troubleshooting section could use some updating

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#69]
Hello, team.  I was going through this scenario and I think the troubleshooting section could use a little updating to help customers navigate more smoothly.  First off, a lot of users will deploy something like a Windows Server 2016 VM in azure to run these commands and mount the encrypted disk and they'll need to install the AZ module to connect to Azure.  The problem is that they'll right away get the error below when trying to run the command "Install-Module Az"

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.

To get around this, they'll need to Force TLS1.2 on the PowerShell session with the command below.

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

The next thing they'll need to do is also install the AzureAD module....perhaps these modules should be listed as prerequisites.  

another issue they might run into is that the script is looking for the files below in the Az.Accounts module

Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll

These files have been moved to the AzureAD module, though, so there is no logic that will actually load the files for them.
we would need to add a logic section to the script that would Change these lines:

$adal = "${env:ProgramFiles}\WindowsPowerShell\Modules\Az.Accounts\$(((dir ${env:ProgramFiles}\WindowsPowerShell\Modules\Az.Accounts).name) | select -last 1)\PreloadAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
$adalforms = "${env:ProgramFiles}\WindowsPowerShell\Modules\Az.Accounts\$(((dir ${env:ProgramFiles}\WindowsPowerShell\Modules\Az.Accounts).name) | select -last 1)\PreloadAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll"

To this:

$adal = "${env:ProgramFiles}\WindowsPowerShell\Modules\AzureAD\$(((dir ${env:ProgramFiles}\WindowsPowerShell\Modules\azuread).name) | select -last 1)\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
$adalforms = "${env:ProgramFiles}\WindowsPowerShell\Modules\AzureAD\$(((dir ${env:ProgramFiles}\WindowsPowerShell\Modules\azuread).name) | select -last 1)\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll"

Lastly, I thought we could give the users a little help in telling them where to find the various parameters the script requires.  Something like this:

#keyVaultName can be found in the disk encryption extension settings found from this command "Get-AzVM -ResourceGroupName $rgName -Name $vmName -DisplayHint Expand"
#Example "KeyVaultURL":"https://**mysecurevault**.vault.azure.net/",

        -keyVaultName "mysecurevault"

#kekName can be found in the disk encryption extension settings found from this command "Get-AzVM -ResourceGroupName $rgName -Name $vmName -DisplayHint Expand"
#Example KeyEncryptionKeyURL":"https://mysecurevault.vault.azure.net/keys/**myKeyEncryptionKey**/cb9e7912d3904c57965f4547e1f07f26"

        -kekName "myKeyEncryptionKey"

#the secretName can be found by running the commands below and looking at the "ID" property.  
#$vmName = "myvm"
#$KeyVault = "mysecurevault"
#Get-AzKeyVaultSecret -VaultName $KeyVault | where {($_.Tags.MachineName -eq $vmName) -and ($_.ContentType -match 'BEK')}
#example Id: https://mysecurevault.vault.azure.net:443/secrets/**5AB53F8A-33BC-4219-A37E-E503AB11A099**

        -secretName "5AB53F8A-33BC-4219-A37E-E503AB11A099"

#this is a local path to where you want to save the BEK...let them know that they'll need to create this folder before running the script or it will error out.  

        -bekFilePath "c:\bek\5AB53F8A-33BC-4219-A37E-E503AB11A099.BEK"

#adTenant can be found on the overview page of your Azure AD from the portal.  This is the "Tenant ID"

        -adTenant "e862a392-0e5f-4efd-bc3f-fae518bc31eb"

Anyway, thanks for taking a look.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72043177-4ad8-7261-ba13-3d7b14c76a14
* Version Independent ID: a9ee0e02-325d-256e-4f20-18df23962002
* Content: [Troubleshooting BitLocker boot errors on an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-bitlocker-boot-error#script-troubleshooting)
* Content Source: [support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver Thank you for your suggestions. We will investigate the issues and update the thread.

**Comment by genlin** [comment]
@mbiver The article was updated based on your suggestions.  I believe the new version will be more friendly for the users who have the bitlocker issue in the VM. Thanks for your contribution!
