### ISSUE TITLE
In place upgrades for Windows 10 in Azure...

### ISSUE THREAD

**Issue by EsDub03** [MicrosoftDocs/SupportArticles-docs#691]
Hi!

This section reads like Win 10 Enterprise/Professional can be upgraded to Multi-session version, https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade#windows-versions-supported-for-in-place-system-upgrades. But in this document, it clearly states that this is not allowed, https://docs.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#can-i-upgrade-a-windows-10-vm-to-windows-10-enterprise-multi-session

Can "Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions" be updated with a link to reflect this caveat?

Thank you in advance! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade#windows-versions-supported-for-in-place-system-upgrades)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by cowhitley** [comment]
#693

**Comment by AmandaAZ** [comment]
@cowhitley PR693 is merged, so we closed this issue. Thank you!
