### ISSUE TITLE
A note should be added to let people know that upgrades from Windows 10 Professional or Enterprise to multi-session are not currently supported.

### ISSUE THREAD

**Issue by cowhitley** [MicrosoftDocs/SupportArticles-docs#692]
A note should be added under the sentence that states Windows 10 Multi-session are supported for in-place upgrades. To prevent confusion, we should point out that upgrades from Windows 10 Professional or Enterprise to multi-session are not currently supported.

https://docs.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#can-i-upgrade-a-windows-10-vm-to-windows-10-enterprise-multi-session

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade#windows-versions-supported-for-in-place-system-upgrades)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by cowhitley** [comment]
#693

**Comment by genlin** [comment]
@cowhitley The PR is merged. Thank you!
