### ISSUE TITLE
Alternative shortcut

### ISSUE THREAD

**Issue by moisedk** [MicrosoftDocs/SupportArticles-docs#694]
[The instruction at _Azure Portal (Home)->Virtual Machines->(user's VM)>Settings>Connection->SSH (tab)_ is a great alternative shorcut, basically changing the permission level of private key to '400']

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72902f52-ed00-8106-dda7-a437271ccd48
* Version Independent ID: 11b2d8c9-4b3a-344a-b795-e979d3d4f31b
* Content: [Can’t SSH to Azure Linux VM because permissions are too open - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-ssh-permissions-too-open#online-repair)
* Content Source: [support/azure/virtual-machines/troubleshoot-ssh-permissions-too-open.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-ssh-permissions-too-open.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@moisedk Thanks for the comment. The instruction (chmod 400 <keyname>.pem) works in some scenarios. If the error is caused by /etc/ssh configuration directory, we may need to use the solution in this article.
