### ISSUE TITLE
Incorrect Service Name

### ISSUE THREAD

**Issue by MatthewBrown0** [MicrosoftDocs/SupportArticles-docs#696]
Hello - In step #8 it says "Then check whether the Guest Agent Services starts correctly."  The correct name of the service is "Windows Azure Guest Agent".

Thanks,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95825442-ec08-fcdd-76bd-cc0694b6b913
* Version Independent ID: 11a97acc-d077-3bac-9411-8199bd98b255
* Content: [Troubleshooting Azure Windows VM Agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent#step-2-check-whether-auto-update-is-working)
* Content Source: [support/azure/virtual-machines/windows-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/windows-azure-guest-agent.md)
* Service: **virtual-machines**
* GitHub Login: @dkdiksha
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@MatthewBrown0 Thanks for the feedback. I will update the service name.
