### ISSUE TITLE
Update-AzVM step in PowerShell example prompts for RG name

### ISSUE THREAD

**Issue by vktibrewal** [MicrosoftDocs/SupportArticles-docs#698]
The PowerShell example on this page is incomplete. The last step 'Update-AzVM -VM $VM' prompts for resource group name. Please update the example to include the RG name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea4398a-8b98-eb03-7e2a-c7e11117a602
* Version Independent ID: 1ea4398a-8b98-eb03-7e2a-c7e11117a602
* Content: [Virtual machine stuck in failed state - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/vm-stuck-in-failed-state?tabs=portal)
* Content Source: [support/azure/virtual-machines/vm-stuck-in-failed-state.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/vm-stuck-in-failed-state.md)
* Service: **virtual-machines**
* GitHub Login: @mimckitt
* Microsoft Alias: **mimckitt**

**Comment by mimckitt** [comment]
#assign: @mimckitt
