### ISSUE TITLE
Update for Konnectivity?

### ISSUE THREAD

**Issue by lukemaslany-next** [MicrosoftDocs/SupportArticles-docs#699]
If I understand correctly, aks-link is being replaced by konnectivity.  Might it be worth updating this article to reflect this change, as I suspect the same error would be encountered if there is an issue with the konnectivity-agent pods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b2de19-c6a7-5ed3-f0ec-115a1abbcd28
* Version Independent ID: 03b2de19-c6a7-5ed3-f0ec-115a1abbcd28
* Content: [Error from server: error dialing backend: dial tcp - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/error-from-server-error-dialing-backend-dial-tcp)
* Content Source: [support/azure/azure-kubernetes/error-from-server-error-dialing-backend-dial-tcp.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/error-from-server-error-dialing-backend-dial-tcp.md)
* Service: **container-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for the feedback, @lukemaslany-next. I've updated the article. We'll let you know when the changes go live.

**Comment by DennisLee-DennisLee** [comment]
The article update is now live.
