### ISSUE TITLE
I have a clean powershell solution for: Windows PowerShell cmdlet Grant-DfsnAccess doesn't change inheritance on DFS links

### ISSUE THREAD

**Issue by Joachim-Otahal** [MicrosoftDocs/SupportArticles-docs#704]
Your Documents at
https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/grant-dfsnaccess-not-change-inheritance
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-client/system-management-components/grant-dfsnaccess-not-change-inheritance.md

States that it is not possible, neither with powershell nor with dfsutil, to "Set explicit view permissions" on DFS-links, and we should use the GUI instead.
This is not true. Due to the need to do this on a massive scale with several thousand across various sites and roots I developed a way to set exactly that option in PowerShell.

Are you interested?

**Comment by Joachim-Otahal** [comment]
Update on this: First releasable script is done: https://github.com/Joachim-Otahal/DFS-N-Tools

**Comment by Deland-Han** [comment]
Hi @Joachim-Otahal, thank you for the feedback. We are discussing on this, and I will reply later.

**Comment by Deland-Han** [comment]
Hi @Joachim-Otahal, I had a discussion with our engineer. Actually, you do not have to manually set the option in the UI. The `dfsutil` command should do the job. Please see the workaround section of the article.

We'd appreciate you for sharing the script. As the `dfsutil` command still works in this scenario, it is still the recommend way. Thanks.

**Comment by Joachim-Otahal** [comment]
DFSUTIL failed in my scenario, possibly due to strict RBAC implementation. I am DFS admin, else the powershell version would not work, but DFSUTIL did fail in the scenario where I needed it.
Though you must admit: Pointing to DFSUTIL just 'cause the Grant-DfsnAccess cmdlet is half-assed written is an ugly solution.

**Comment by Deland-Han** [comment]
Yes. This is a confirmed problem with `Grant-DfsnAccess`.

If it is fixed or there are any changes to this cmdlet, we will update this article. Thanks for your feedback.
