### ISSUE TITLE
KB974524 ("Windows Installer reconfigured all applications") suggests non-standard WMI class

### ISSUE THREAD

**Issue by sewillia-msft** [MicrosoftDocs/SupportArticles-docs#712]
[KB 974524](https://docs.microsoft.com/en-US/troubleshoot/windows-server/admin-development/windows-installer-reconfigured-all-applications?source=docs) suggests discontinuing use of the `Win32_Product` WMI class (due to query side-effects) in favor of `Win32Reg_AddRemovePrograms`.

However, this class is [only present on computers with an SMS/SCCM client installed](https://www.admin-magazine.com/Archive/2019/51/Software-inventory-with-PowerShell). Querying this class on a machine not under SCCM management will throw an Invalid Class error.

This document should be updated to include one or more of the following:
* A warning that `Win32Reg_AddRemovePrograms` (and related classes) requires an SCCM client to be installed
* Alternative WMI-based methods for querying the registry ([`StdRegProv`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/regprov/stdregprov) class methods, for instance) in the event an SCCM client is not installed

#### Document Details
⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._

* ID: 2b1fe51b-6ccd-c186-fc69-f0dd2ed93a8d
* Version Independent ID: 2a4db90e-7c69-68b2-5421-541b0ec3e829
* Content: [Event log message indicates that the Windows Installer reconfigured all installed applications](https://docs.microsoft.com/en-US/troubleshoot/windows-server/admin-development/windows-installer-reconfigured-all-applications?source=docs)
* Content Source: [support/windows-server/admin-development/windows-installer-reconfigured-all-applications.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/admin-development/windows-installer-reconfigured-all-applications.md)
* Product: **windows-server**
* GitHub Login: @Deland-Han 
* Microsoft Alias: **delhan**

**Comment by Deland-Han** [comment]
Hi @sewillia-msft. Thank you for the suggestion. I will update the article.

**Comment by Deland-Han** [comment]
Hi, this article was updated as you requested. Thanks.
