### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by ejschoen** [MicrosoftDocs/SupportArticles-docs#713]
Instructions for resetting an Admin password don't appear to work, at least not with VMs that have been around a while.  

This is literally following the instructions on this page:

```PS
PS /home/eric> Set-AzVMAccessExtension -ResourceGroupName $RgName -Location $Location -VMName $VmName -Credential (get-credential) -typeHandlerVersion "2.0" -Name VMAccessAgent

PowerShell credential request
Enter your credentials.
User: USER-NAME-ELIDED
Password for user USER-NAME-ELIDED: ****************

Set-AzVMAccessExtension: No version found in the artifact repository that satisfies the requested version '2.0' for VM extension with publisher 'Microsoft.Compute' and type 'VMAccessAgent'.
ErrorCode: ArtifactVersionNotFound
ErrorMessage: No version found in the artifact repository that satisfies the requested version '2.0' for VM extension with publisher 'Microsoft.Compute' and type 'VMAccessAgent'.
ErrorTarget: 
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 7b5013ad-a8e3-47cf-b71a-da30fc95b797
```

I noticed from Get-AzVM status that my VM appears to be running VMAccessAgent 2.4.9, if I understand correctly what GetAzVM -Status is telling me.  So I tried using version 2.4 instead of 2.0.  This gets me a different error:

```PS
PS /home/eric> Set-AzVMAccessExtension -ResourceGroupName $RgName -Location $Location -VMName $VmName -Credential (get-credential) -typeHandlerVersion "2.4" -Name VMAccessAgent

PowerShell credential request
Enter your credentials.
User: USER-NAME-ELIDED
Password for user USER-NAME-ELIDED: ****************

Set-AzVMAccessExtension: Cannot update handlerVersion or autoUpgradeMinorVersion for VM extension 'VMAccessAgent'. Change is in conflict with other extensions under handler 'Microsoft.Compute.VMAccessAgent', with typeHandler version '2.0' and autoUpgradeMinorVersion 'True'.
ErrorCode: OperationNotAllowed
ErrorMessage: Cannot update handlerVersion or autoUpgradeMinorVersion for VM extension 'VMAccessAgent'. Change is in conflict with other extensions under handler 'Microsoft.Compute.VMAccessAgent', with typeHandler version '2.0' and autoUpgradeMinorVersion 'True'.
ErrorTarget: 
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 60067444-c38e-4563-b9dd-3befa2d780e3
```

This happens using Powershell installed via homebrew with the latest Az module, and it happens using Azure cloud shell Powershell.  The troubleshooting instructions for this are not helpful.

(Note: ultimately, I think it appears--and I might be wrong--that the password reset extension is incompatible with servers that are also domain controllers.  I ended up creating a custom script extension for the VM and provided it a powershell script that reset my password, and then deleted the script from my storage account container and deleted the extension.  This method is pretty far from obvious, but I found it on a web page.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcca963-7ced-fe06-6b20-51984aa31ea1
* Version Independent ID: c2c4516a-5f37-4dc3-71a9-f93abfb0465a
* Content: [Reset Remote Desktop Services or its administrator password in a Windows VM - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-rdp?WT.mc_id=Portal-Microsoft_Azure_Support#reset-by-using-the-azure-portal)
* Content Source: [support/azure/virtual-machines/reset-rdp.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/reset-rdp.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ejschoen Thanks for the comments, Yes, the steps in this article don't apply to the domain controller.

**Comment by genlin** [comment]
@ejschoen I think so. This piece of information (DC is not supported) can easily be ignored. Will consider to create a new "reset password" article for DC, or add the steps into the existing article . Thanks again for helping to improve the document.

**Comment by AmandaAZ** [comment]
@ejschoen We added a note ("The steps in this article don't apply to Windows domain controllers.") at the top of this document. Thanks for helping to improve the document.
