### ISSUE TITLE
Screenshots of portal out of date

### ISSUE THREAD

**Issue by CoffeCold** [MicrosoftDocs/SupportArticles-docs#715]
docu:
![image](https://user-images.githubusercontent.com/32043266/191195974-41972f44-32bb-44bb-8331-f4abe823f464.png)
portal:
![image](https://user-images.githubusercontent.com/32043266/191196297-dbb2b5cf-ede0-47ca-9fc4-dadba2ed7d2e.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7923662-a286-c380-a214-02c84f089162
* Version Independent ID: 71221dd9-77bf-7994-4890-b92254e2a463
* Content: [Redeploy Windows virtual machines in Azure - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/redeploy-to-new-node-windows)
* Content Source: [support/azure/virtual-machines/redeploy-to-new-node-windows.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/redeploy-to-new-node-windows.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@CoffeCold, Thanks for the feedback. I will update the screenshot.
