### ISSUE TITLE
Log off all Terminal Server Session Users - No Powershell samples

### ISSUE THREAD

**Issue by JeroenHems** [MicrosoftDocs/SupportArticles-docs#721]
Doc Title: [Log off all Terminal Server Session Users from a command prompt](https://learn.microsoft.com/en-us/troubleshoot/windows-server/remote/log-off-terminal-server-session-users-command-prompt)

Issue
This article does not contain any Powershell samples to perform this, or logging of all disconnected sessions from RDS servers. This does not fly in 2022 :) 

Suggestion: Change title to Log off Remote Desktop Session Users and include both Powershell and Command Prompt samples. Maybe optionally add instructions to manually log off an individual session through Server Manager.

The Powershell code below is what I use in both my RDS server farms:

To log off all user sessions, execute the following Powershell code on the Connection Broker:
```
$sessions = Get-RDUserSession

foreach($session in $sessions)
{
    Invoke-RDUserLogoff -HostServer $session.HostServer -UnifiedSessionID $session.UnifiedSessionId -Force
}
```

To log off only disconnected user sessions, execute the following Powershell code on the Connection Broker:
```
$sessions = Get-RDUserSession |  ? {$_.SessionState -eq "STATE_DISCONNECTED"}

foreach($session in $sessions)
{
    Invoke-RDUserLogoff -HostServer $session.HostServer -UnifiedSessionID $session.UnifiedSessionId -Force
}
```

**Comment by JeroenHems** [comment]
One liner would be:
```
Get-RDUserSession | `
    ? {$_.SessionState -eq "STATE_DISCONNECTED"} | `
    Foreach-Object { Invoke-RDUserLogoff -HostServer $_.HostServer -UnifiedSessionID $_.UnifiedSessionID -Force}
```

**Comment by Deland-Han** [comment]
The PowerShell commands look good to me. I will add them to the article. Thank you for your contribution!
