### ISSUE TITLE
Page Needs Updating.

### ISSUE THREAD

**Issue by RVAHaver01** [MicrosoftDocs/SupportArticles-docs#723]
This page needs to be updated since the product has gone GA and there are many differences.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67fa2432-67f8-688a-e58a-752b2cb0c2d2
* Version Independent ID: fe34017d-5f11-702f-a15c-9334294650da
* Content: [Performance diagnostics for Azure virtual machines - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/performance-diagnostics?source=docs)
* Content Source: [support/azure/virtual-machines/performance-diagnostics.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/performance-diagnostics.md)
* Service: **virtual-machines**
* GitHub Login: @anandhms
* Microsoft Alias: **anandh**

**Comment by genlin** [comment]
@RVAHaver01， Thanks for the feedback. We will update the article.

**Comment by genlin** [comment]
Close the issue since the article was updated.
