### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by SourajitSamadder** [MicrosoftDocs/SupportArticles-docs#725]
This section in the document is pointing to an incorrect page.
'If you are using a site-to-site VPN and forced tunneling, see [Use Azure custom routes to enable KMS activation with forced tunneling](![wrong link](https://user-images.githubusercontent.com/29010543/191825656-4181d0aa-34c9-42da-8607-d693321cbdb5.png)).'

It should point to this page: https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation?source=recommendations
It is pointing to this page: https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-forced-tunneling

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c788541f-43c1-ac1d-9765-72e1e7a54099
* Version Independent ID: 5a4188fe-1e90-0d97-49d7-c90b233e8205
* Content: [Troubleshoot Windows virtual machine activation problems in Azure - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-activation-problems)
* Content Source: [support/azure/virtual-machines/troubleshoot-activation-problems.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-activation-problems.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@SourajitSamadder, Thanks for the feedback. I will fix the problem.
