### ISSUE TITLE
Missing new lines in powershell

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/SupportArticles-docs#73]
Looks like the new lines have disappeared from the powershell script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d157ba-7e6e-9e8f-9273-5f3255bf58ba
* Version Independent ID: 05c64f74-9bd6-84d4-c9d1-52ac67bd8d3e
* Content: [RDP not working for classic cloud service resource - Cloud Services](https://docs.microsoft.com/en-us/troubleshoot/azure/cloud-services/rdp-not-working-cloud-service)
* Content Source: [support/azure/cloud-services/rdp-not-working-cloud-service.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/cloud-services/rdp-not-working-cloud-service.md)
* Service: **cloud-services**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@yowl  Thanks for the feedback. I will fix the issue in the article.

**Comment by genlin** [comment]
#please-close
