### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by david-topham-precisely** [MicrosoftDocs/SupportArticles-docs#730]
The link in 'Before You Troubleshoot -> Connect to the VM Remotely' ('How to use remote tools....') is broken - it returns a 404 placeholder. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 377e7e7f-c07e-3c69-06b2-49af12f83cc3
* Version Independent ID: 71b277ef-9f51-c926-f5cf-f41fce49b845
* Content: [Troubleshoot authentication errors when you use RDP to connect to Azure VM - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-connect-rdp-azure-vm)
* Content Source: [support/azure/virtual-machines/cannot-connect-rdp-azure-vm.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/cannot-connect-rdp-azure-vm.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@david-topham-precisely, Thanks for the feedback. I will fix the issue.
