### ISSUE TITLE
Need to correct yml section

### ISSUE THREAD

**Issue by josue609** [MicrosoftDocs/SupportArticles-docs#732]
The section (3) that explains disabling cloud-init.  The entry in the yml file:
```
network:
config: disabled
```

should read:
```
network:
  config: disabled
```
  
  There needs to be a slight indentation, or else it will not work and cloud-init continues to manage the network configuration and wipes out the entries in the netplan yml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9525eb3-1be7-449b-2b63-10bb1ec71f63
* Version Independent ID: d9525eb3-1be7-449b-2b63-10bb1ec71f63
* Content: [Configure multiple network interfaces in Azure Linux virtual machines - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration)
* Content Source: [support/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/linux-vm-multiple-virtual-network-interfaces-configuration.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@josue609, Thanks for the feedback. I will fix the format issue.

**Comment by genlin** [comment]
Close the issue since the problem has been fixed.
