### ISSUE TITLE
CLI commands link returns 404

### ISSUE THREAD

**Issue by briansaxbergMSFT** [MicrosoftDocs/SupportArticles-docs#734]
[Enter feedback here]

https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/kernel-related-boot-issues#method-2-offline-repair
Use CLI commands link returns 404.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87923903-be07-d5a3-f555-4ef2a0a7173e
* Version Independent ID: c7191d9e-61dc-12cd-b16f-c7b2ca0df289
* Content: [How to recover Azure Linux VM from kernel-related boot issues - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/kernel-related-boot-issues)
* Content Source: [support/azure/virtual-machines/kernel-related-boot-issues.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/kernel-related-boot-issues.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by AmandaAZ** [comment]
@briansaxbergMSFT If you mean that a 404 error is returned when you click the "use CLI commands" link (see the following screenshot), maybe there are some network issues from your side. It works fine from my side. It's redirecting to [this page](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-recovery-disks-linux). You can check your network or restart your compute, and then try the link again.
![屏幕截图 2022-10-08 085324](https://user-images.githubusercontent.com/46809752/194679444-64fcb53d-badd-4482-aa67-ed4e7c1d3552.jpg)

**Comment by briansaxbergMSFT** [comment]
@AmandaAZ Thank you for confirming.  I swear when I clicked on it it was a 404.
