### ISSUE TITLE
Typeo with IIS_IUSRS

### ISSUE THREAD

**Issue by zacav** [MicrosoftDocs/SupportArticles-docs#735]
The line:
Select **Add User or Group**…, enter **IIS_IURS** in the **Enter the object names to select box**, and then select **OK**

Needs to be updated to:
Select **Add User or Group**…, enter **IIS_IUSRS** in the **Enter the object names to select box**, and then select **OK**

IIS_IURS is missing an S.

**Comment by HaiyingYu** [comment]
@zacav Thanks for pointing out this issue. Will fix the typo in the article.
