### ISSUE TITLE
Is this the way I do it? (microsoft-trusted-root-store-removal-of-us-federal-common)

### ISSUE THREAD

**Issue by oklokl** [MicrosoftDocs/SupportArticles-docs#743]
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/windows-server/windows-security/microsoft-trusted-root-store-removal-of-us-federal-common-policy.md

I did it according to the manual.
I'm not sure if this is the first time I've tried it.
```
echo register registration 
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate" /v "RootDirUrl" /t REG_SZ /d "http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en" /f
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate" /v "SyncFromDirUrl" /t REG_SZ /d "http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en" /f
echo and reboot..

md c:\roots\
certutil -generateSSTFromWU c:\roots\trustedcerts.sst
certutil -syncwithwu c:\roots
echo The second download gave me an error.

certutil -verifyctl -v c:\roots\disallowedcertstl.cab c:\roots\disallowedcert.sst
certutil -verifyctl -v c:\roots\disallowedcertstl.cab c:\roots\disallowedcert.sst > c:\roots\disallowedcert.txt
certutil -dump -gmt -v c:\roots\trustedcerts.sst > c:\roots\trustedcerts.txt
echo http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab
echo http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab
echo If download does not work in [cmd], open the web and download with a direct link

echo Untrusted list registration (block list registration)
certutil -addstore -f disallowed C:\roots\disallowedcert.sst

echo Trusted list registration
certutil -addstore -f root C:\roots\trustedcerts.sst

Winkey + R
netplwiz
certmgr.msc 
certlm.msc
```
It doesn't work according to the manual.
So I fixed it.

Please let me know if there are any mistakes.
I am a computer beginner.
:)

![4](https://user-images.githubusercontent.com/1571600/194731549-1cf0bec6-4271-4fae-b6fd-7bce568b0620.png)
```
c:\rootsdisallowedstl.cab
c:\roots\disallowedstl.cab
```
I couldn't find this file.
I think windows is blocking it. So, I downloaded it myself. (Microsoft Windows [Version 10.0.19045.1826] win10)

http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab
So the command has changed.

And let me make one suggestion.
It would be nice to have a command or register option to prevent installation of expired certificates.
Certificates that have expired are automatically installed.
I am troubled by such unknown certificates.

and error
![45663](https://user-images.githubusercontent.com/1571600/194755845-9df7b389-e8ad-46f0-9e2b-00df23f23650.png)
Intermittent connection is not possible.
My windows 10 update is no problem
```
certutil -generateSSTFromWU c:\roots\trustedcerts.sst
certutil -syncwithwu c:\roots
```
I tried to download several times for installation and it was blocked haha.. About 5 times?.
I think I'm overly sensitive to downloads. http://ctldl.windowsupdate.com

**Comment by Deland-Han** [comment]
Hi @oklokl, thank you for your feedbacks. 

`c:\rootsdisallowedstl.cab` should be `c:\roots\disallowedstl.cab`. I have corrected this typo in the article. 

The GitHub issue is for our articles related questions & issues. As the command and result depend on the environment settings, my help on your technical questions and feedbacks about Windows is limited.

So, I recommend you contact our support for further help:

https://support.microsoft.com/contactus  
https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/bd-p/WindowsServer
