### ISSUE TITLE
TEMP profile created when using Serial Console for first logon

### ISSUE THREAD

**Issue by juanandmsft** [MicrosoftDocs/SupportArticles-docs#744]
[Enter feedback here]
I am experiencing the following issue with Serial Console in Windows VMs:
* If first logon for a given account is performed through Windows Serial Console, the account gets bound to a temp profile.
* To fix it, you need to log on as an alternate account over RDP/Bastion, delete the profile for the broken account, and logon normally through RDP/Bastion at least once so profile is properly created.
* After that, Serial Console will load profile properly.

Is this a known issue? If so, should be in the article until fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ece99e50-9796-cbc9-23a7-421fa042e1ec
* Version Independent ID: dfc773bc-f682-c90d-f988-784cecf70a47
* Content: [Azure Serial Console for Windows - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-windows)
* Content Source: [support/azure/virtual-machines/serial-console-windows.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-windows.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@juanandmsft, Thanks for the feedback. I will forward this issue to the product team.
