### ISSUE TITLE
Key based access required to Storage Account

### ISSUE THREAD

**Issue by fbodmer** [MicrosoftDocs/SupportArticles-docs#748]
It might be helpful to mention that custom boot diagnostics storage accounts need to allow key based access. If the setting 'Allow storage account key access' is set to 'Disabled', the serial console won't work - and display the error message about missing firewall configuration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 027253ab-b1d6-6707-a608-ff71c5c7f712
* Version Independent ID: 377cb416-6cad-436a-df96-68a7513c7acc
* Content: [Azure Serial Console for Linux - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-linux#use-serial-console-with-custom-boot-diagnostics-storage-account-firewall-enabled)
* Content Source: [support/azure/virtual-machines/serial-console-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-linux.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@fbodmer, Thanks for the feedback. I will investigate the issue and update the article.

**Comment by genlin** [comment]
@fbodmer, As you said, disabling the 'Allow storage account key access' setting will cause Serial Console to not work. We have crate a work item for fixing this issue. Thanks again for helping to improve the product.
