### ISSUE TITLE
Separate Linux SWAP article under Linux VM setup and configuration section

### ISSUE THREAD

**Issue by mabicca** [MicrosoftDocs/SupportArticles-docs#749]
Hi there,

We have this page where we talk about swap issues
[SWAP file not recreated after Linux VM restart](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart)

However, we don't really have a section that talks about setting up swap in Linux the right and supported way on Azure which is to use the ephemeral (resource) disk. In the past, the WAAgent would take care of that by simply editing its configuration file under /etc/waagent.conf, however this has not been working mostly because all Endorsed Linux distributions use cloud-init for provisioning, so I do believe we need a document that covers all of that since it's creating lots of confusion out there.

**This draft could be a good beginning for that article.**

To configure swap on Linux VMs on Azure , you will need to setup cloud-init to automatically create it using the ephemeral (resource) disk on images, which is usually mounted under /mnt.

This resource disk is local to the VM and it is the fastest device, creating swap partitions on osDisks or Datadisks is not recommended due to the latency that it might cause if the swap is ever utilized, it is also important to remember that swap or cache files are the only things that we recommend using the resource disk, because when a VM is stopped, moved to a different container/host, all data on that drive will be lost, another reason why it's ideal for temporary caches and swap files.

There are a few ways to set it up, ideally you can use custom data upon deploying a VM and configure that, more details here:
[Use cloud-init to configure a SWAP partition on a Linux VM](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/cloudinit-configure-swapfile)

### SWAP under the default resource disk patch [/mnt]

1) Create a new file **swap.sh** under **/var/lib/cloud/scripts/per-boot** with the following contents:

```
#!/bin/sh
size=`df -h --output=target, avail | grep -i ^\/mnt | awk '{print $2}' | cut -b1,2`
swapsize=`echo "scale=0; ($size*0.3)/1" | bc`
echo $swapsize
dd if=/dev/zero of=/mnt/swapfile bs=1073741824 count=$swapsize
chmod 0600 /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/resource/swapfile
swapon -a;
````
**NOTE:** The script above will be executed on every boot and it will allocate 30% of the available space in the resource disk , you can tweak or fix that value if needed by simply changing the script above to fit your needs.

2) Make sure the file is executable
````
chmod +x /var/lib/cloud/scripts/pert-boot/swap.sh
````
3) Stop and start the VM,  please note that this is necessary just the first time, after that , reboots will also work.

### SWAP under a custom path [example: /azure/resource]

1) Create a file called **99-resource-disk.cfg** under **/etc/cloud/cloud.cfg.d/**

````
#cloud-config
disk_setup:
ephemeral0:
table_type: mbr
layout: [66, 33]
overwrite: True
fs_setup:
- device: ephemeral0
filesystem: ext4
mounts:
- ["ephemeral0", "/azure/resource", "auto", "defaults,nofail", "0", "0"]
`````
2) Proceed with the same steps to create the script, but you should notice the different path, instead of /mnt, we are using as an example /azure/resource as well as the df calculation for 30% of available space is looking for the same:

````
#!/bin/sh
size=`df -h --output=target, avail | grep -i azure\/resource | awk '{print $2}' | cut -b1,2`
swapsize=`echo "scale=0; ($size*0.3)/1" | bc`
echo $swapsize
dd if=/dev/zero of=/azure/resource/swapfile bs=1073741824 count=$swapsize
#fallocate --length $swapsizeGib /mnt/swapfile
chmod 0600 /azure/resource/swapfile
mkswap /azure/resource/swapfile
swapon /azure/resource/swapfile
swapon -a;
````

3) Make sure the file is executable
````
chmod +x /var/lib/cloud/scripts/pert-boot/swap.sh
````
3) Stop and start the VM,  please note that this is necessary just the first time, after that , reboots will also work.

### NOTES
1) The steps to use the waagent.conf file will not work if the provisioning agent is cloud-init, which is true for most images on Azure now, if you are aware that your image is not using cloud-init and you have waagent installed, you should still be able to use it.
2) As mentioned before, you can customize the size of the swap and location, these are simple examples to get it up and running fast.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01ee0e4f-fb6a-2a3f-b30e-e2bf4c0b383c
* Version Independent ID: 6f0185df-55bd-c07b-8380-93b9e9428638
* Content: [Swap file is not re-created after a Linux VM restarts - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart)
* Content Source: [support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md)
* Service: **virtual-machines**
* Sub-service: **vm-cannot-start-stop**
* GitHub Login: @srijang
* Microsoft Alias: **srijangupta**

**Comment by genlin** [comment]
@mabicca, Thanks for the detail info. I will email you for reviewing the new version when it's ready.

**Comment by mabicca** [comment]
I think we might also need to include the section about disabling the waagent.conf creation of SWAP at the top of this document that I sent, let me know if you want and I can edit it again, but basically this:

Disable resource disk formatting and swap configuration within waagent configuration because this task is now handled by Cloud-Init. Set the parameters as follows:

Copy
# Format if unformatted. If 'n', resource disk will not be mounted.
ResourceDisk.Format=n

# Create and use swapfile on resource disk.
ResourceDisk.EnableSwap=n

#Mount point for the resource disk
ResourceDisk.MountPoint=/mnt

#Size of the swapfile.
ResourceDisk.SwapSizeMB=0

Restart the Azure Linux Agent.
See [How to update the Azure Linux Agent on a VM](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/update-linux-agent) for information about the restart commands for different Linux distributions.

**Comment by genlin** [comment]
Working with Marco offline for this request.  Close the issue.
