### ISSUE TITLE
AD DLL missing from latest version of Az.Accounts

### ISSUE THREAD

**Issue by chakra146** [MicrosoftDocs/SupportArticles-docs#75]
The latest version of Az.Accounts doesn't have **Microsoft.IdentityModel.Clients.ActiveDirectory.dll** and **Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll**.

We need to get rid of these adal libraries for getting the authorization token.

**Example: 2.2.4 doesn't have them.**

**However, older ones 1.9.4 has those dll files.**

Error while running current script with KEK encryption:

At line:29 char:79
+ ... ccounts\$(((dir ${env:userprofile}\Documents\WindowsPowerShell\Module ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\m10564...les\Az.Accounts:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
dir : Cannot find path 'C:\Users\m1056436\Documents\WindowsPowerShell\Modules\Az.Accounts' because it does not exist.
At line:30 char:85
+ ... ccounts\$(((dir ${env:userprofile}\Documents\WindowsPowerShell\Module ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\m10564...les\Az.Accounts:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 
'file:///C:\Users\m1056436\Documents\WindowsPowerShell\Modules\Az.Accounts\PreloadAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' or one of 
its dependencies. The system cannot find the file specified." 

++++++++++++++++++

Invoke-RestMethod : {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}
At line:76 char:11
+ $result = Invoke-RestMethod -Method POST -Uri $unwrapKeyRequestUrl -H ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
You cannot call a method on a null-valued expression.

++++++++++++++++++

**Also, even this "https://gist.github.com/vermashi/7f3544a911cf0ed75d6b32b562b77237#file-retreiveencryptionsecretviaurl-ps1" fails.**

 $authResult = $authContext.AcquireToken($resourceAppIdURI, $clientId, $redirectUri, "Auto")
 
 The AquireToken method is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72043177-4ad8-7261-ba13-3d7b14c76a14
* Version Independent ID: a9ee0e02-325d-256e-4f20-18df23962002
* Content: [Troubleshooting BitLocker boot errors on an Azure VM - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-bitlocker-boot-error)
* Content Source: [support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-bitlocker-boot-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@chakra146  Thank you for the feedback. You are right. The ADAL Assemblies used in the script are not available in the latest version of azure PowerShell. I will update the script. Thanks again for helping to improve the document.

**Comment by genlin** [comment]
@chakra146 The steps about about how to install the az.acocunt 1.9.4 were added into the article . We will provide the new script when it is available. Thanks for your suggestions!
