### ISSUE TITLE
az aks check-acr  says "Your cluster can pull images from " Still 401 and not clear from doc what to do

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/SupportArticles-docs#756]
The document says I should do az aks check-acr. But rest of the document is not clear what to do if it says "Your cluster can pull images from .. ". Should I still continue with the next steps, which is pointless. 

The amount of randomness in the Microsoft created products is high. Just cannot guarantee something works and just clueless when things does not work. It is so complex how things are made by Microsoft that there could be 1000 reasons why something will not work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1557572b-65d8-9644-7d0e-9331ac6f75f1
* Version Independent ID: 1557572b-65d8-9644-7d0e-9331ac6f75f1
* Content: [Can't pull images from Azure Container Registry to Kubernetes - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster)
* Content Source: [support/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster.md)
* Service: **azure-kubernetes-service**
* Sub-service: **troubleshoot-cant-pull-images-from-acr-to-cluster**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@sijucm, Thanks for the feedback. If the error message you receive is not listed in this article, [ please contact our support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview?DMC=troubleshoot)
