### ISSUE TITLE
Unable to use it without PIP, old vnet/subnet when customer have restriction to create a new RG and new VNET

### ISSUE THREAD

**Issue by prafulbusa** [MicrosoftDocs/SupportArticles-docs#766]
Lots of time customer have limited permission to perform troubleshooting due to multiple restriction put on subscription. 
Such policy doesn't allow user to create a new Resource group, new VNET/subnet, or PIP. 
So, is there a way we can use old existing RG, existing VNET, etc? Can you share CLI command for public users, please. 
Thank you in advance for this CLI process that enables to handle easy rescue VM creation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57c86f8d-4f70-e909-6b8f-321cb018532e
* Version Independent ID: 32044cf7-cf37-b4e9-0ebf-47df90de7cda
* Content: [Repair a Windows VM by using the Azure Virtual Machine repair commands - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands)
* Content Source: [support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-windows-vm-using-azure-virtual-machine-repair-commands.md)
* Service: **virtual-machines**
* Sub-service: **vm-backup-restore**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@prafulbusa, The script only creates the recovery VM in a new resource group. To use the existing RG, customer need to load the disk manually: https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/unlock-encrypted-disk-offline

**Comment by genlin** [comment]
@@prafulbusa, I will process to close this PR. Feel free to open it if there is any additional comment or question.
