### ISSUE TITLE
Request: Create a table for "Increase the bandwidth usage for replicating into Azure"

### ISSUE THREAD

**Issue by kyjones03** [MicrosoftDocs/SupportArticles-docs#769]
If possible, please create a table showing the integer values related to Reg Key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Azure Backup\Replication  | Value Name: UploadThreadsPerVM" and how it relates to bandwidth. It shows the max value of 32 but unsure of the scaling. If this testing has been done internally, it would be very helpful to have this info available for architects to plan Azure Migration deployments. 

Example: Integer value 1 = N mb/s and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52b64cf0-aed2-5245-f765-940ec42354d2
* Version Independent ID: 75a3e15f-2c49-8917-f451-8d91422e8a8a
* Content: [How to manage on-premises to Azure protection network bandwidth usage - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/site-recovery/manage-protection-network-bandwidth-usage)
* Content Source: [support/azure/site-recovery/manage-protection-network-bandwidth-usage.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/site-recovery/manage-protection-network-bandwidth-usage.md)
* Service: **site-recovery**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@MubDubs, Thanks for the comment. We will investigate and update the thread.
