### ISSUE TITLE
My vm os is centos7, why always creating windows repairing vm, and "az repair run " always failed. What a low bug.

### ISSUE THREAD

**Issue by woodymoo** [MicrosoftDocs/SupportArticles-docs#770]
[Enter feedback here]
 az vm repair create -g mycdhdev -n mycdh-dn1 --distro 'rhel7' --repair-username xxx --repair-password "xxxxxx"  --verbose

Does repair vm requires public ip? (y/n): n
Fetching compatible Windows OS images from gallery...
Checking if source VM size is available...
Source VM size 'Standard_D8s_v3' is available. Using it to create repair VM.

Creating resource group for repair VM and its resources...
Source VM uses unmanaged disks. Creating repair VM with unmanaged disks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4a16efa-1d65-daa2-3add-12e0314ae900
* Version Independent ID: 440a1711-03a8-f50c-1aba-049168ebffa7
* Content: [Repair a Linux VM automatically with the help of ALAR - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/repair-linux-vm-using-alar?source=recommendations)
* Content Source: [support/azure/virtual-machines/repair-linux-vm-using-ALAR.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/repair-linux-vm-using-ALAR.md)

Running script on repair VM: repair-dnscdh-_
ERROR: (Conflict) Run command OS type 'Linux' does not match the target OS Windows.
Code: Conflict
Message: Run command OS type 'Linux' does not match the target OS Windows.

Repair run failed.

* Service: **virtual-machines**
* Sub-service: **vm-backup-restore**
* GitHub Login: @malachma
* Microsoft Alias: **malachma**

**Comment by malachma** [comment]
I created a new issue for the vm repair extension where this issue needs to be address on
--> https://github.com/Azure/azure-cli-extensions/issues/5510
