### ISSUE TITLE
OMG...

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/SupportArticles-docs#777]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* Sub-service: **vm-common-errors-issues**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by alex--thomas** [comment]
We have hundreds of these VMs...

**Comment by genlin** [comment]
@alex--thomas, If you have any question or help about VM upgrade, you can [create a support request](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview?DMC=troubleshoot), or ask [Azure community support](https://learn.microsoft.com/en-us/answers/products/azure?product=all).
