### ISSUE TITLE
add windows server 2022 info

### ISSUE THREAD

**Issue by HugoSabino** [MicrosoftDocs/SupportArticles-docs#778]
Hi Team,

I would like to suggest adding Windows Server 2022 to the unsupported server systems. 
I tried searching if Windows server 2022 was supported and could not find any info.
Nonetheless, if windows 2022 in place upgrade is supported, should be added to this doc as well.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://learn.microsoft.com/en-US/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* Sub-service: **vm-common-errors-issues**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@HugoSabino, Thanks for the comment. I will investigate and then update this thread.

**Comment by genlin** [comment]
@HugoSabino, Windows Server 2022 VM supports in-pace upgrade. I will also add this info into the article. Thanks.
