### ISSUE TITLE
Change to Windows activation IP addresses "planned for October 3rd, 2022" needs update

### ISSUE THREAD

**Issue by toddjames** [MicrosoftDocs/SupportArticles-docs#779]
In this documentation, there's a note that:

> To mitigate an issue related to Network Security Group, azkms.core.windows.net points to kms.core.windows.net for now. After the issue is resolved (planned for October 3rd, 2022) azkms.core.windows.net will point to two new IP addresses: 20.118.99.224 and 40.83.235.53.

Is there an update that could be provided for this in the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* Sub-service: **vm-windows-activation**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@toddjames, I will investigate and update this thread.

**Comment by genlin** [comment]
@toddjame, Our engineers are focusing on some more critical issues. SO the fix for this issue is postponed. I will provide more information in the article when it is available.

**Comment by mimckitt** [comment]
@toddjames We are continuing to work on the rollout. We expect it to be complete by end of December. I will check with engineering to see if we want to update the doc in the meantime. 

#please-close

**Comment by toddjames** [comment]
@genlin @mimckitt  Any update on this? The docs still reference "planned for October 3rd, 2022".
