### ISSUE TITLE
Script prompts for logins and saves three zero-byte csv files

### ISSUE THREAD

**Issue by picklesrein** [MicrosoftDocs/SupportArticles-docs#786]
Any way to increase the verbosity of the script? I'm sure my environment has legacy logins, yet the results of running the script is:
> Welcome To Microsoft Graph!

and an empty-set:
![image](https://user-images.githubusercontent.com/30266050/202271926-675a3184-ad32-429c-b838-7ffd3838690f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?WT.mc_id=Portal-Microsoft_AAD_IAM&tabs=powershell)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for your input, @picklesrein. We're evaluating your request and will respond with an update later.

**Comment by DennisLee-DennisLee** [comment]
Hi @picklesrein, the script was intended to detect successful legacy TLS authentications. Since we're now past the deprecation date, we will not be making modifications. However, please feel free to adjust this script to your use case(s) as necessary.
