### ISSUE TITLE
Azure dependency for Communication Compliance in Singapore

### ISSUE THREAD

**Issue by infninfn** [MicrosoftDocs/SupportArticles-docs#790]
Hello there - do we have a specific timeline for countries/regions where Azure dependency availability is coming soon? Specifically for Singapore?

**Comment by genlin** [comment]
@infninfn , Are you referring "Dependency tracking in Application Insights"? For the product related question, please submit it at  https://feedback.azure.com/d365community/forum/3887dc70-2025-ec11-b6e6-000d3a4f09d0

**Comment by genlin** [comment]
@infninfn I will close this article. Feel free to reopen it if there is any problem or question.
