### ISSUE TITLE
Response body size seems to be limited to 1MB

### ISSUE THREAD

**Issue by jiseli** [MicrosoftDocs/SupportArticles-docs#792]
When configuring an *Azure Application Insights Standard Availability Test*, it seems that the response body size is read up to 1 000 000 bytes and **then the connection is dropped**. This leads to raise a **ClientConnectionFailure** exception on the server side when the response body is actually larger than that (even it's a success status code). By the way, when using the *Content match* success criteria, it fails if the string is after that 1 000 000 bytes limit.

This should be clearly stated in the documentation to avoid misleading errors.

<img width="352" alt="response-body-size" src="https://user-images.githubusercontent.com/1581022/203820222-3171ab3d-6a7a-494b-8497-cd6e072d2d3a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4eab7b7a-bcb9-39de-81f6-ec8ef8b38e09
* Version Independent ID: 4eab7b7a-bcb9-39de-81f6-ec8ef8b38e09
* Content: [Diagnose common problems that cause your ping tests to fail in Application Insights availability monitoring - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-monitor/app-insights/diagnose-ping-test-failure)
* Content Source: [support/azure/azure-monitor/app-insights/diagnose-ping-test-failure.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-monitor/app-insights/diagnose-ping-test-failure.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @kelleyguiney22
* Microsoft Alias: **v-kegui**

**Comment by DennisLee-DennisLee** [comment]
Thanks for reporting this issue, @jiseli. We are investigating the issue and will provide a response shortly.

**Comment by DennisLee-DennisLee** [comment]
+@CourtGoodson
