### ISSUE TITLE
"Wait a few minutes"

### ISSUE THREAD

**Issue by MarcSchluperAtIntel** [MicrosoftDocs/SupportArticles-docs#795]
Please elaborate.

Three minutes?
Twenty minutes?
What is "a few minutes"?

Why not send an email when the change has taken effect? Or display something on the webpage?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5510e54-7d87-4fa7-e756-269c525cdf22
* Version Independent ID: e5510e54-7d87-4fa7-e756-269c525cdf22
* Content: [Error AADSTS50011 the redirect URI not match the redirect URIs configured for the application - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-redirect-uri-mismatch)
* Content Source: [support/azure/active-directory/error-code-AADSTS50011-redirect-uri-mismatch.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS50011-redirect-uri-mismatch.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @aricrowe57
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@MarcSchluperAtInte, Thanks for the comments. Usually, the change will take effect within 3~5 minutes.  I agree with you that  the current description is confusing.  I will update the article.

**Comment by genlin** [comment]
@MarcSchluperAtIntel I will process to close this PR. Feel free to let me know if there is any additional comment or feedback.
