### ISSUE TITLE
Error message when you run the "w32tm /resync" command to synchronize Windows Server 2003 or Windows SBS to an external time source: "The computer did not resync because no time data was available"

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/SupportArticles-docs#796]
You need to add a space here between the /config and /manualpeerlist

If you run the w32tm /config /syncfromflags:manual command or the w32tm **/config/manualpeerlist:peerlist** command to determine whether Windows is configured correctly, the commands complete successfully.

**Comment by Deland-Han** [comment]
I have fixed the typo. Thank you for the feedback.
