### ISSUE TITLE
ProvisionVMAgent Parameter appears to be wrong in guide

### ISSUE THREAD

**Issue by tommylux** [MicrosoftDocs/SupportArticles-docs#799]
_In the output, locate the ProvisionVMAgent property, and check whether the value is set to True. If it is, this means that the agent is installed on the VM._

Is the property called **ProvisioningState**? as I cannot see a ProvisionVMAgent property using -DisaplyHint expand

Thanks
Tom

https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent#step-1-check-whether-the-azure-vm-agent-service-is-installed

![image](https://user-images.githubusercontent.com/19841675/204856742-15b30dcd-4b74-45c3-9c44-9a36e2a46246.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95825442-ec08-fcdd-76bd-cc0694b6b913
* Version Independent ID: 11a97acc-d077-3bac-9411-8199bd98b255
* Content: [Troubleshooting Azure Windows VM Agent - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows-azure-guest-agent)
* Content Source: [support/azure/virtual-machines/windows-azure-guest-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/windows-azure-guest-agent.md)
* Service: **virtual-machines**
* Sub-service: **vm-extensions-not-operating**
* GitHub Login: @dkdiksha
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@tommylux, The VM agent status is nested in the OSprofile. Try this command:

` get-azvm -name VMname| Select -ExpandProperty OSProfile | Select -ExpandProperty Windowsconfiguration | Select ProvisionVMAgent `

**Comment by genlin** [comment]
@tommylux  I will process to close this issue. Feel free to let me know if there is any additional question or comment.

**Comment by tommylux** [comment]
Thanks
