### ISSUE TITLE
AAD OAuth2 still responsive to TLS 1.0/1.1

### ISSUE THREAD

**Issue by oscarmh** [MicrosoftDocs/SupportArticles-docs#800]
Team is there any way to FORCE AAD OAuth2 to not give any answer on TLS 1.0/1.1 requests ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4324e7b2-0388-f022-4884-b07678601eeb
* Version Independent ID: e0080267-a6c5-a904-92ad-72e332c35b07
* Content: [Enable TLS 1.2 support as Azure AD TLS 1.0/1.1 is deprecated - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=azure-monitor)
* Content Source: [support/azure/active-directory/enable-support-tls-environment.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/enable-support-tls-environment.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for your input, @oscarmh. We're evaluating your request and will provide a response shortly.

**Comment by DennisLee-DennisLee** [comment]
> Team is there any way to FORCE AAD OAuth2 to not give any answer on TLS 1.0/1.1 requests ?
@oscarmh Not currently, but we're planning to add this capability in the future.
