### ISSUE TITLE
Had this issue but used specific date 2021-10-01, latest did not work 

### ISSUE THREAD

**Issue by samyi001** [MicrosoftDocs/SupportArticles-docs#802]
[Enter feedback here]
Updated file to use latest version "2021-10-01" instead of "latest" in script step 3 of Cause 5: No attested data supplied (422). 
Not sure if latest is a working variable or the documentation is suggesting to enter a date instead. 

![image](https://user-images.githubusercontent.com/99344308/205384117-ff568875-d014-4131-8fac-b0148ffdde8b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073e6622-6171-8410-0dcd-947255bfd971
* Version Independent ID: 073e6622-6171-8410-0dcd-947255bfd971
* Content: [Troubleshoot connectivity and registration for SUSE SLES VMs - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/suse-public-cloud-connectivity-registration-issues)
* Content Source: [support/azure/virtual-machines/suse-public-cloud-connectivity-registration-issues.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/suse-public-cloud-connectivity-registration-issues.md)
* Service: **virtual-machines**
* Sub-service: **vm-cannot-connect**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **hokamath**

**Comment by DennisLee-DennisLee** [comment]
Thanks for the report, @samyi001. We'll look into this issue and let you know if a change to the article is needed.

**Comment by DennisLee-DennisLee** [comment]
Hi @samyi001, the "**--api latest**" option is valid. If that option isn't working for you, it means there's a package that isn't updated to the required version.

**Comment by samyi001** [comment]
Ok. Thank you for the update!
