### ISSUE TITLE
Windows Server 2019 has different Group Policy paths

### ISSUE THREAD

**Issue by t-miller** [MicrosoftDocs/SupportArticles-docs#804]
When trying to configure the time limit for logoff of RemoteApp sessions in my Windows Server 2019 VDI, I noticed that the paths outlined in [the docs](https://learn.microsoft.com/en-us/troubleshoot/windows-server/remote/remoteapp-sessions-disconnected) didn't match my instance.

Per the image outlined below, my path is `<Computer|User> Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Session Time Limits`
![image](https://user-images.githubusercontent.com/19845698/206562234-3a9cad91-15e1-42bc-81bc-d016c69eb09f.png)

I drafted PR #803 but I'm not sure how the paths differ - is it only these two paths or are there other paths that should be included?

**Comment by Deland-Han** [comment]
@t-miller This article applies to Windows Server 2012 R2, so we cannot just add Windows Server 2019 information to it. I am investigating it and will modify this article.
