### ISSUE TITLE
AKS-ACR Connectivity Issue

### ISSUE THREAD

**Issue by thebinaryhack** [MicrosoftDocs/SupportArticles-docs#809]
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster.md

In this document for the Cause 1: 401 Unauthorized Error, the documentation is not correct.

The issue I faced: 
I assigned ACRPull role to the the System assigned Managed identities of the AKS cluster. However, when I tried to pull the images from my ACR, I received an error: `failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized`

We identified that when we have a system pool and an user/agent pool, the AKS cluster has 2 identities, 1 for system Assigned and one User assigned. The system assigned Identities do not need to be given any permissions. Since the containers are deployed on the agent pool, then only the User Assigned Managed identities of Agent/User Pool have to be assigned the ACRPull role.

![AKS Service principals (these Do Not Work for ACR Pull Role)](https://user-images.githubusercontent.com/64826379/207404095-91c4e04f-db41-475e-8c7a-36501b8a5b41.png)

These identities have to be assigned the ACR Pull role in AKS:
<img width="548" alt="User Assigned Managed Idnentities for Agent Pools" src="https://user-images.githubusercontent.com/64826379/207404971-c2edc92d-4295-48e7-976e-151fd95123d1.png">

**Comment by genlin** [comment]
@thebinaryhack Thanks for sharing the information. I will investigate it and update the article if the current step is not correct.
