### ISSUE TITLE
Help in Remote Desktop

### ISSUE THREAD

**Issue by GoKuDead** [MicrosoftDocs/SupportArticles-docs#81]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa9f4d1f-94a7-2b7a-50f6-585fce5a322b
* Version Independent ID: c2a771cd-399e-c940-bc6e-422f0546ec7c
* Content: [An internal error occurs when you make an RDP connection to Azure Virtual Machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-internal-error)
* Content Source: [support/azure/virtual-machines/troubleshoot-rdp-internal-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/troubleshoot-rdp-internal-error.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@GoKuDead  If you have a issue with RDP connection, please contact [Azure support](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
