### ISSUE TITLE
microsot > microsoft

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/SupportArticles-docs#816]
Article [Latest updates and version history for SQL Server](https://learn.microsoft.com/en-us/troubleshoot/sql/releases/download-and-install-latest-updates) has a link to aka.ms/sqlserverbuilds where in sheet 2017 of the Excel file there is a typo in link **KB 5010786** which now leads to https://support.microsot.com/help/5010786.
**microsot** > microsoft
[Click to download this new Excel file now](https://download.microsoft.com/download/d/6/5/d6583d78-9956-45c1-901d-eff8b5270896/SQL%20Server%20Builds%20V4.xlsx)
  
![image](https://user-images.githubusercontent.com/40343254/209132086-964f5248-aed7-42f6-bcb2-8ef2bba88da1.png)
![image](https://user-images.githubusercontent.com/40343254/209125563-019878b2-fce6-4702-b73b-e85feeec216a.png)

**Comment by HaiyingYu** [comment]
@ingebeumer Thanks for pointing out this issue. I will share this to the owner of the Excel file.

**Comment by HaiyingYu** [comment]
The issue has been fixed.
