### ISSUE TITLE
How to acces.

### ISSUE THREAD

**Issue by Masterkenshin** [MicrosoftDocs/SupportArticles-docs#823]
https://github.com/binance-chain/javascript-sdk/blob/master/docs/api-docs/README.md

**Comment by HaiyingYu** [comment]
@Masterkenshin Could you provide more information about your question? Which article and which section/sentence do you want to refer to?

**Comment by HaiyingYu** [comment]
@Masterkenshin I'm going to close the issue. Feel free to create a new one or reopen this one once you have more information to provide.
