### ISSUE TITLE
Adding rows and columns programmatically in .NET MAUI Grid Types does not work

### ISSUE THREAD

**Issue by shady49** [MicrosoftDocs/SupportArticles-docs#826]
Pre-.NET MAUI allowed for adding rows and columns within c# code. The latest release of, .NET MAUI Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.3 causes an error: 
Error	CS1501	No overload for method 'Add' takes 3 arguments	CollecttionViewExample (net7.0-windows10.0.19041.0)	. 

It works fine in Mobile App (Xamarin Forms).

Here is a snippet of code that fails in .NET MAUI:
<Grid x:Name="GridCol"></Grid>

c# code
private void Button_Clicked(object sender, EventArgs e)
    {
        GridCol.RowDefinitions.Add(new RowDefinition());
        GridCol.RowDefinitions.Add(new RowDefinition());
        GridCol.RowDefinitions.Add(new RowDefinition());
        GridCol.ColumnDefinitions.Add(new ColumnDefinition());
        GridCol.ColumnDefinitions.Add(new ColumnDefinition());

        for (int rowIndex = 0; rowIndex < 3; rowIndex++)
        {
            for (int columnIndex = 0; columnIndex < 2; columnIndex++)
            {

                var label = new Label
                {
                    Text = "Hello",
                    VerticalOptions = LayoutOptions.Center,
                    HorizontalOptions = LayoutOptions.Center
                };
                GridCol.Children.Add(label, columnIndex, rowIndex);
            }
        }
    }

**Comment by HaiyingYu** [comment]
Hi @shady49 , it seems that you have issues when using .NET, so I will close this issue now. You can contact Microsoft support engineers by creating a support ticket or asking your questions in forums, such as [.NET community support](https://learn.microsoft.com/answers/products/dotnet). And if you want to share your feedback to our articles, feel free to reopen this or create a new one.
