### ISSUE TITLE
Providing DHCP zones for on-premise usage from Azure.

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/SupportArticles-docs#838]
Am I correct in reading this as the DHCP server role is not supported on Azure VMs even if it's only providing on-prem DHCP ranges via a DHCP relay forwarding requests to it's Azure hosted NIC?

If so, what is the supported mechanism for removing on-prem DHCP servers while still maintaining integration with DNS zones stored in Active Directory servers running in Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b703446-c838-fd33-09fe-1df826399931
* Version Independent ID: ff85d0c9-ecb0-987b-7b4c-fa252a93c55b
* Content: [Microsoft server software support for Microsoft Azure Virtual Machines - Virtual Machines](https://learn.microsoft.com/en-US/troubleshoot/azure/virtual-machines/server-software-support)
* Content Source: [support/azure/virtual-machines/server-software-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/server-software-support.md)
* Service: **virtual-machines**
* Sub-service: **vm-support-statements**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ChrisParrBIE, Thanks for submitting the issue. For technical issues/questions, please [contact our support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview?DMC=troubleshoot), or ask [Azure community support](https://learn.microsoft.com/en-us/answers/products/azure?product=all).

**Comment by ChrisParrBIE** [comment]
Hi @genlin ,

I was mostly after clarity in the documentation as https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets states "A possible scenario is configuring DHCP relay from devices on-premises to an Azure VM running a DHCP server. Customer is responsible for configuring on-premise devices (for example, router configuration) to create this DHCP relay traffic to the VM's IP in Azure." which combined with the statement in https://learn.microsoft.com/en-US/troubleshoot/azure/virtual-machines/server-software-support that DHCP isn't a supported role if the IP listening for DHCP requests is an Azure one, that seems to be saying that you're fine running DHCP in Azure, but only if you don't use Windows server do to it. This doesn't really feel like the intended meaning!

**Comment by genlin** [comment]
@ChrisParrBIE, I think we have to keep the DHCP server on local network for on-premises devices.
