### ISSUE TITLE
Please replace references to ACS/Azure Container Service with AKS/Azure Kubernetes Service

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [MicrosoftDocs/SupportArticles-docs#84]
The document references ACS which was replaced with AKS, and the references need to be updated.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6298d3e6-ded9-614d-b4fb-03148e8ce57f
* Version Independent ID: 8d7923ac-0b69-14ae-2e11-4de49a419992
* Content: [Support policy for containers and related services on Azure - Azure](https://docs.microsoft.com/en-us/troubleshoot/azure/general/support-policy-containers#feedback)
* Content Source: [support/azure/general/support-policy-containers.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/support-policy-containers.md)
* Service: **container-service**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@AdamSharif-MSFT Thanks for the feedback I will update the article.

**Comment by genlin** [comment]
@AdamSharif-MSFT The article was updated. Thanks for the feedback.
