### ISSUE TITLE
SPO first party account

### ISSUE THREAD

**Issue by MKoeppl-Microsoft** [MicrosoftDocs/SupportArticles-docs#851]
please add the following account to the list of known 1st party Microsoft accounts which are known to interact with Azure AD in certain scenarios. 

Name of the account :  spo_service@support.onmicrosoft.com 
Service : SharePoint Online
Description: 

Please follow up with the respective team who owns this account for a proper desciption. 

Thanks,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33be97f8-2846-f5d1-a196-7019d44327b2
* Version Independent ID: 5f0bb5e3-dbc5-f004-fe9d-8a814bfd654c
* Content: [Unknown Actors in Audit Reports - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/unknown-actors-in-audit-reports)
* Content Source: [support/azure/active-directory/unknown-actors-in-audit-reports.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/unknown-actors-in-audit-reports.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@MKoeppl-Microsoft, I will investigate and update this thread.

**Comment by genlin** [comment]
@MKoeppl-Microsoft, The article is updated with the following info. I will process to close the issue.

- spo_service@support.onmicrosoft.com
- SharePoint Online
- SThis account is used to create Azure Access Control Service (ACS) principles, which are required for the installation of the SharePoint app (add-in).
