### ISSUE TITLE
Step 2 item 11 restart 'kube-proxy' method does not work on AKS windows node

### ISSUE THREAD

**Issue by boliu83** [MicrosoftDocs/SupportArticles-docs#857]
`kubectl delete pods -n kube-system -l component=kube-proxy` 

The command provided in the article doesn't work on AKS windows node because on windows node Kube-proxy runs a Windows service of the host OS not a pod.

Can you provide the recommended method for restarting kube-proxy on AKS Windows node? 

In the past I have used the below command to restart Kubeproxy service on Win nodes but not sure if there is a better way for it.  
```
az vmss run-command invoke -g <node_resource_group> -n <vmss_name> --command-id RunPowerShellScript --instance-id <instance_id> --scripts "Restart-Service -Force Kubeproxy"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b51152dc-bfae-2a77-5718-0bda09a85dc9
* Version Independent ID: b51152dc-bfae-2a77-5718-0bda09a85dc9
* Content: [Troubleshoot connections to pods and services within an AKS cluster - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/troubleshoot-connection-pods-services-same-cluster)
* Content Source: [support/azure/azure-kubernetes/troubleshoot-connection-pods-services-same-cluster.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/troubleshoot-connection-pods-services-same-cluster.md)
* Service: **azure-kubernetes-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for the feedback. We're investigating the issue now.
