### ISSUE TITLE
two slight edits

### ISSUE THREAD

**Issue by davidsandbrand** [MicrosoftDocs/SupportArticles-docs#858]
Slease specify in the documentation that "<Identifier> is the identifier of Windows Boot Loader you found in the previous step" - **including the curly braces**.

Also, in point #2, identifiers include "<Boot partition>", which is not used anywhere.  This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06c40958-cfb0-0f12-b48e-e3de0029870e
* Version Independent ID: 079c8fe4-345b-4560-61c3-3f04a273fe53
* Content: [Windows boot error 0xc0000034 on an Azure VM - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/boot-error-0xc0000034)
* Content Source: [support/azure/virtual-machines/boot-error-0xc0000034.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/boot-error-0xc0000034.md)
* Service: **virtual-machines**
* Sub-service: **vm-cannot-start-stop**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@davidsandbrand， Thanks for the feedback. `<Identifier>` is a placeholder that means user needs to replace with the value with correct identifier ID. I think we add an example to avoid confusion:

- <Identifier> is the identifier of Windows Boot Loader you found in the previous step. For example: {9f25ee7a-e7b7-11db-94b5-f7e662935912}
- 
I will update the article.

**Comment by genlin** [comment]
@davidsandbrand，The article is updated. I will process to close this issue. Feel free to reopen it if there is any additional comment.
