### ISSUE TITLE
troubleshoot-aip-issues.md most links are broken at the bottom

### ISSUE THREAD

**Issue by Cloudwien** [MicrosoftDocs/SupportArticles-docs#864]

**Comment by genlin** [comment]
@Cloudwien, You can check the article in https://learn.microsoft.com/en-us/troubleshoot/azure/general/troubleshoot-aip-issues. Let me know if there are broken links in this page.

**Comment by genlin** [comment]
@Cloudwien, As I haven't heard back from you for a couple of weeks, I will process to close this issue. Feel free to reopen it if the problem still exists.
