### ISSUE TITLE
Don't see 2016 or 2019 in the supported or unsupported list

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#873]
Hello, team.  This article appears a little confusing.  I see Windows server 2016 in the "original versions" section, but don't see it mentioned in either the supported or unsupported section.  Is in place upgrading Windows Server 2016 supported in Azure?  Also, I don't see Windows Server 2019 anywhere.  Is that supported in Azure.  Thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5853ce95-f163-0739-0a57-50aab1719bdd
* Version Independent ID: b1536434-3675-a736-22e8-28e5fea49f06
* Content: [Steps for in-place system upgrades for supported Windows 10 Azure VMs and workarounds for unsupported versions - Virtual Machines](https://learn.microsoft.com/en-US/troubleshoot/azure/virtual-machines/in-place-system-upgrade)
* Content Source: [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/in-place-system-upgrade.md)
* Service: **virtual-machines**
* Sub-service: **vm-common-errors-issues**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver, As far as I know, the in-place upgrade is not supported in Windows Server 2019 yet. We have removed the Windows  Server 2016 from the original product list. Thanks for the comments.

**Comment by mbiverdev** [comment]
It looks like we've got more information about the Server upgrades here...

In-place upgrade for VMs running Windows Server in Azure
https://learn.microsoft.com/en-us/azure/virtual-machines/windows-in-place-upgrade

**Comment by mbiver** [comment]
It looks like we've got more information about the Server upgrades here...

In-place upgrade for VMs running Windows Server in Azure
Currently, upgrading to Windows Server 2019 and Windows Server 2022 is supported.

https://learn.microsoft.com/en-us/azure/virtual-machines/windows-in-place-upgrade

**Comment by genlin** [comment]
@mbiver, Just checked the article you shared. Yes, it is supported now. The article was updated two week ago. I will update this troubleshooting article. Thanks for the feedbacks!
