### ISSUE TITLE
linux16 line does not always start with "linux16".  Sometimes it starts with just "linux"

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#877]
Was working with RHEL 8.2 LVM Gen 1 and Gen 2 and RHEL 8.2 RAW Gen 1 and when going through the section "Enter single-user mode without root account enabled in RHEL" it says that the kernel line starts with "linux16".  I found this is not the case with the images mentioned above.  With these images, in Azure, the line just starts with "linux"  See screenshot below.  Wondering if we want to clarify that it can be both?

![image](https://user-images.githubusercontent.com/39092497/213778199-043aeda5-2e34-4c54-af76-766fc4be4e0e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef37b5e1-f76f-6dce-8730-ff46d99fb985
* Version Independent ID: 4e15573e-f0f2-abe0-d919-8eb1ba96905f
* Content: [Azure Serial Console for GRUB and single-user mode - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-grub-single-user-mode#manually-enter-single-user-mode-in-rhel)
* Content Source: [support/azure/virtual-machines/serial-console-grub-single-user-mode.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/serial-console-grub-single-user-mode.md)
* Service: **virtual-machines**
* Sub-service: **vm-troubleshooting-tools**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver, I will update the article to cover this scenario. Thanks for the feedback.
