### ISSUE TITLE
Additional steps to find "/rescue/boot/" and "/rescue/boot/efi" devices

### ISSUE THREAD

**Issue by mbiver** [MicrosoftDocs/SupportArticles-docs#885]
Hello, team.  I was reviewing this article and think we might want to adjust this section "RHEL/Centos 7.x & 8.X with LVM" "https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/chroot-environment-linux#rhelcentos-7x--8x-with-lvm"
 
I think subsection "e" should be broken up to help users who are not that familiar with Linux.  I think the section should start with

mkdir /rescue
mount /dev/mapper/rootvg-rootlv /rescue
mount /dev/mapper/rootvg-varlv /rescue/var
mount /dev/mapper/rootvg-homelv /rescue/home
mount /dev/mapper/rootvg-usrlv /rescue/usr
mount /dev/mapper/rootvg-tmplv /rescue/tmp
mount /dev/mapper/rootvg-optlv /rescue/opt

but then another section should be added that lets the user know that "/rescue/boot/" and "/rescue/boot/efi" are not always on /dev/sdc2 or /dev/sdc1.  We should let the user know that they should navigate to the /rescue/etc/fstab file to find out which partitions were the "/boot" and "/boot/efi" from the broken OS disk.  The users can then run the command "blkid" and compare the UUID's from the "/rescue/etc/fstab" file with the output of the blkid command to find out exactly which devices the "/rescue/boot/" and "/rescue/boot/efi" mountpoints should be mounted to in the repair VM.  For example, you'll notice in the screen shot below for this 8.2 RHEL Gen 1 VM in Azure, the commands would actually be 

mount /dev/sdc1 /rescue/boot/
mount /dev/sdc15 /rescue/boot/efi

Screenshot before OS was broken, clearly showing the /boot and /boot/efi on /dev/sda1 and /dev/sda15

![image](https://user-images.githubusercontent.com/39092497/214441785-1d757103-f303-4aba-a165-bcb8b4bcad3b.png)

Screenshot of the broken OS disk mounted as data disk to repair VM now showing /dev/sdc1 and /dev/sdc15

![image](https://user-images.githubusercontent.com/39092497/214442369-fc860570-474a-4b96-ab8c-c563513b3c60.png)

the customer could then finish with the commands below and enter the chroot environment.  

mount -t proc /proc /rescue/proc
mount -t sysfs /sys /rescue/sys
mount -o bind /dev /rescue/dev
mount -o bind /dev/pts /rescue/dev/pts
mount -o bind /run /rescue/run
chroot /rescue

Anyway, just thought it would help users who are not as familiar with Linux.  Thanks.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2214e4-40a3-06a3-f3d5-e306cdcd599b
* Version Independent ID: 85ae75c8-4b4e-0ddb-8654-6af59f1623fb
* Content: [How to troubleshoot the chroot environment in a Linux Rescue VM - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/chroot-environment-linux)
* Content Source: [support/azure/virtual-machines/chroot-environment-linux.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/chroot-environment-linux.md)
* Service: **virtual-machines**
* Sub-service: **vm-backup-restore**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@mbiver, Thanks for sharing the information. I will contact you offline to update this article.
