### ISSUE TITLE
please update document

### ISSUE THREAD

**Issue by porrascarlos802018** [MicrosoftDocs/SupportArticles-docs#892]
[Enter feedback here]

As one of the first steps, please add a check to ensure the node  on which coredns is running, is used to check the DNS resolution. 

ssh to the node 
nslookup <fqdn> 

If the DNS was recently changed , ensure all nodes were rebooted / reimaged so the new DNS gets applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27598902-4d81-1d88-c674-683ea6da1aaa
* Version Independent ID: 27598902-4d81-1d88-c674-683ea6da1aaa
* Content: [Troubleshoot DNS resolution failures from inside the pod - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/troubleshoot-dns-failure-from-pod-but-not-from-worker-node)
* Content Source: [support/azure/azure-kubernetes/troubleshoot-dns-failure-from-pod-but-not-from-worker-node.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/troubleshoot-dns-failure-from-pod-but-not-from-worker-node.md)
* Service: **azure-kubernetes-service**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Handling this offline.
