### ISSUE TITLE
tcpdump command writes to "/capture.cap" but the copy command tries to copy from "/host/capture.cap".

### ISSUE THREAD

**Issue by dmsammons** [MicrosoftDocs/SupportArticles-docs#895]
`tcpdump` command writes to "/capture.cap" but the copy command tries to copy from "/host/capture.cap".

Here is a link to the call of `tcpdump`: https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md?plain=1#L69

And here is a link to the copy command: https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md?plain=1#L99

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Version Independent ID: 44ea4d31-2301-3b93-f04a-a60b3ebf1661
* Content: [Capture a TCP dump from a Linux node in an AKS cluster - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks)
* Content Source: [support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/azure-kubernetes/capture-tcp-dump-linux-node-aks.md)
* Service: **azure-kubernetes-service**
* Sub-service: **data-collection-guide**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
Thanks for your input, @dmsammons. We'll investigate and get back to you shortly.

**Comment by DennisLee-DennisLee** [comment]
@dmsammons The command string has been fixed in the article. Thanks for your help!
