### ISSUE TITLE
Labeling incorrect

### ISSUE THREAD

**Issue by olsookie** [MicrosoftDocs/SupportArticles-docs#90]
Left hand column states the subject of this article should be:
Verification code isn't received in MFA

When you select this article, the page is labeled:
Can't sync SystemMailbox or DiscoveryMailboxSearch accounts using Azure Active Directory Sync tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8dcba0-fadb-5689-3b5b-18095e154ec8
* Version Independent ID: e2df1bbb-0ae4-d4ca-5aa4-5f78523c0745
* Content: [You can't sync the SystemMailbox or DiscoveryMailboxSearch accounts by using the Azure Active Directory Sync tool - Active Directory](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/unable-sync-system-discovery-mailbox)
* Content Source: [support/azure/active-directory/unable-sync-system-discovery-mailbox.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/unable-sync-system-discovery-mailbox.md)
* Service: **active-directory**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@olsookie, Thanks for the feedback. I will fix the typo in the Table of Contents.
