### ISSUE TITLE
Add comment regarding mapping countries/region?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/SupportArticles-docs#907]
In the section ”What does my organization have to do?”, maybe we need to add a bullet describing that if you use Conditional Access based on countries/regions you might need to re-consider since what is mentioned here: https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/location-condition#countries-and-regions

”Sign-ins from IPv6 addresses cannot be mapped to countries or regions, and are considered unknown areas. Only IPv4 addresses can be mapped to countries or regions.”

I guess this would mean that if you today block all countries except for XYX, this might block all IPv6 traffic once IPv6 traffic is turned on in Azure AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b9aec2-b15b-4310-bc87-c8cbacea6047
* Version Independent ID: b2b9aec2-b15b-4310-bc87-c8cbacea6047
* Content: [IPv6 Support in Azure AD - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/azure-ad-ipv6-support)
* Content Source: [support/azure/active-directory/azure-ad-ipv6-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/azure-ad-ipv6-support.md)
* Service: **active-directory**
* Sub-service: **aad-general**
* GitHub Login: @DennisLee-DennisLee
* Microsoft Alias: **v-dele**

**Comment by DennisLee-DennisLee** [comment]
HI @JonesMikael, your feedback will be incorporated to the https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/location-condition#countries section soon. Thanks again.
