### ISSUE TITLE
Offline Method procedure references non-existent path

### ISSUE THREAD

**Issue by j-lawrence-b1** [MicrosoftDocs/SupportArticles-docs#918]
[Enter feedback here]

Offline Method, Step 7 references a non-existent file:
7. Copy the kernelopts value from the grubenv file.
Example
[root@repairvm ~] # cat /boot/efi/EFI/redhat/grubenv   # /boot/efi/EFI/redhat/grubenv doesn't exist on RHEL 8.6

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74cffbf6-f480-345a-71b0-023de0a00900
* Version Independent ID: afd850d8-37e2-9105-3abd-6ca36cf5075d
* Content: [Failed to start Switch Root error in an Azure Linux VM - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/resolve-failed-start-switch-root-azure-linux-vm)
* Content Source: [support/azure/virtual-machines/resolve-failed-start-switch-root-azure-linux-vm.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/resolve-failed-start-switch-root-azure-linux-vm.md)
* Service: **virtual-machines**
* Sub-service: **vm-cannot-start-stop**
* GitHub Login: @genlin
* Microsoft Alias: **tibasham**

**Comment by genlin** [comment]
@grubenv, Thanks for the feedback. In the RHEL 8.5 or newer versions,  the `grubenv` config file is located at `\boot\grub2\gubenv`. I will update the article with this information.
