### ISSUE TITLE
Typo in command snippet

### ISSUE THREAD

**Issue by xversial** [MicrosoftDocs/SupportArticles-docs#92]
### Blame
a5c4e648abe338dccaa937b559c3227fd0feec44
### File
[/support/windows-server/identity/domain-controller-not-start-c00002e2-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/6f73bfef04945b139f722baea49776e68afad10c/support/windows-server/identity/domain-controller-not-start-c00002e2-error.md#L58)
[/support/windows-server/identity/domain-controller-not-start-c00002e2-error.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/6f73bfef04945b139f722baea49776e68afad10c/support/windows-server/identity/domain-controller-not-start-c00002e2-error.md#L74)
### Got
`dism.exe /online /enable-feature /featurename: DirectoryServices-DomainController`
### Expected
`dism.exe /online /enable-feature /featurename:DirectoryServices-DomainController`

**Comment by Deland-Han** [comment]
Thank you. @xversial. I have fixed the typos.
