### ISSUE TITLE
Various languages are mixed in the titles of JP version.

### ISSUE THREAD

**Issue by makokui** [MicrosoftDocs/SupportArticles-docs#924]
Please confirm this document.
https://learn.microsoft.com/ja-jp/troubleshoot/azure/app-service/web-apps-deployment-faqs

As you can see here, Russian, French? are included in some of the titles. Please modify the tile.
![image](https://user-images.githubusercontent.com/19471946/216893005-b7ae7041-a8d6-442a-b8ed-64f50e293b5d.png)

**Comment by genlin** [comment]
@makokui, Thanks for the feedback. We will fix the issue.

**Comment by genlin** [comment]
Closed the issue since the problem was fixed.
