### ISSUE TITLE
configure-ipv6-in-windows.md - Missing indication of Windows 11 compatibility.

### ISSUE THREAD

**Issue by NapAlot** [MicrosoftDocs/SupportArticles-docs#927]
There should be indication if Windows 11 is also affected by the settings here: configure-ipv6-in-windows.md - https://learn.microsoft.com/en-US/troubleshoot/windows-server/networking/configure-ipv6-in-windows

It indicates Windows 10 - all versions. is the expectation that Windows 11 is not listed so it's not supported?

**Comment by Deland-Han** [comment]
Hi @NapAlot. Thank you for your comments. We will investigate it.

**Comment by Deland-Han** [comment]
We decide to remove the "Applies to:" line as it caused confusion. Thanks again for the feedback. :)
