### ISSUE TITLE
High range Ports have a wrong discription or is in conflict with other KB article 

### ISSUE THREAD

**Issue by OpusMagnumGer** [MicrosoftDocs/SupportArticles-docs#932]
High range Ports have a wrong discription or is in conflict with this: https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang   WinSrv2012 and higher is using 49152-65535

**Comment by Deland-Han** [comment]
Hi @OpusMagnumGer, could you be more specific on which article conflict with https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang?

**Comment by OpusMagnumGer** [comment]
Hi,
https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang#introduction  

To comply with Internet Assigned Numbers Authority (IANA) recommendations, Microsoft has increased the dynamic client port range for outgoing connections in Windows Vista and Windows Server 2008. The new default start port is 49152, and the new default end port is 65535. 

https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#distributed-transaction-coordinator 

*2 does not say Windows Server 2008 and higher. 

Mayb it is a good idear to switch 

At the moment:
Randomly allocated high TCP ports¹ | TCP | 
-> random port number between 1024 - 5000 
->random port number between 49152 - 65535²


Maybe better:
Randomly allocated high TCP ports¹ | TCP | 
->random port number between 49152 - 65535
-> random port number between 1024 - 5000 ²

² Windows Version below Windows Vista and Windows Server 2008.

kind regards

**Comment by Deland-Han** [comment]
Hi @OpusMagnumGer, thank you for your suggestions. I think it's a good idea. I have updated the article.
