### ISSUE TITLE
Azure dependencies availability

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/SupportArticles-docs#937]
[Hello! I've just starting looking into Insider Risk Management and stumbled across the note section that one can only use Insider Risk Management with Azure dependencies availability. I can see Sweden listed as "coming soon" but I can use Insider Risk Managment in the Compliance portal in my test tenants so are you referring to any specific feature of Insider Risk Management or is the country list simply not up to date?

Best,

/Christian]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fda955d1-623b-67be-5c00-172818118a7b
* Version Independent ID: f2ffd9ff-d9d9-ef9e-15fa-44b249b7f7d5
* Content: [Azure dependency availability by country/region - Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/general/dependency-availability-by-country)
* Content Source: [support/azure/general/dependency-availability-by-country.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/general/dependency-availability-by-country.md)
* Service: **azure-common-issues-support**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@ChristianJBergstrom  I think the article is not up to date. I will confirm with our product team.

**Comment by genlin** [comment]
Closed this issue since the article is updated with the latest available country/region list.
