### ISSUE TITLE
explicity tell the name of the script that needs to be created create_swapfile.sh, now it's not clear

### ISSUE THREAD

**Issue by oliviomoura** [MicrosoftDocs/SupportArticles-docs#942]
Where it says:

Add the following script to /var/lib/cloud/scripts/per-boot.

change it to:

Create the following script /var/lib/cloud/scripts/per-boot/create_swapfile.sh

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01ee0e4f-fb6a-2a3f-b30e-e2bf4c0b383c
* Version Independent ID: 6f0185df-55bd-c07b-8380-93b9e9428638
* Content: [Swap file is not re-created after a Linux VM restarts - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart)
* Content Source: [support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md)
* Service: **virtual-machines**
* Sub-service: **vm-cannot-start-stop**
* GitHub Login: @srijang
* Microsoft Alias: **srijangupta**

**Comment by genlin** [comment]
@oliviomoura  Thanks for the feedback. We will update the article to make the step more clear.
