### ISSUE TITLE
Error on the example script prevents activation of the swap file after second reboot

### ISSUE THREAD

**Issue by carlosporter** [MicrosoftDocs/SupportArticles-docs#96]
Hello, 

I tried the instructions posted on this page on a RHEL 7.7 image with cloud-init and found out that the example script is not working ( the swap file wasn't activated after a second server reboot ).

This is the original script:

```
#!/bin/sh
if [ ! -f '/mnt/swapfile' ]; then
fallocate --length 2GiB /mnt/swapfile    --> Here, set the swapsize as necessary.
chmod 600 /mnt/swapfile
mkswap /mnt/swapfile
swapon /mnt/swapfile
swapon -a ; fi
```

The problem with it is that after creating the swap file during the first reboot, on the second the file still exists but then it's not activated.

A better way to handle this is to use a short-circuit approach to create the swap file and to try to activate it every time the script runs as in the example below:

```
cat << EOF > /var/lib/cloud/scripts/per-boot/create_swapfile.sh
#!/bin/sh

# Setup the size of the swap file in Gigabytes
SWAP_GBSIZE="2"

# Setup the path for the swap file, and make sure it's located on the resource disk
SWAP_FILE="/mnt/resource/swapfile"

# Check if the swap file doesnt exists, then creates a new swapfile
[ ! -f \$SWAP_FILE ] && {
  fallocate --length \${SWAP_GBSIZE}GiB \$SWAP_FILE
  chmod 600 \$SWAP_FILE
  mkswap \$SWAP_FILE
}

# Activate the swap file every time this script is executed by cloud-init during the server boot
swapon \$SWAP_FILE
swapon -a

EOF
```

Also, the example below has two duplicated lines ( the ResourceDisk.EnableSwap property ).

```
# vi /etc/waagent.conf 
#Mount point for the resource disk 
ResourceDisk.MountPoint=/mnt 

#Create and use swapfile on resource disk. 
ResourceDisk.EnableSwap=n 

# Create and use swapfile on resource disk. 
ResourceDisk.EnableSwap=n 

#Size of the swapfile. 
ResourceDisk.SwapSizeMB=0
```

Rather that instructing administrators to change the file manually, the same can be accomplished using a single command line:

```
sed -r -i.azbackup \
  -e "/ResourceDisk.EnableSwap=/ s|=.*$|=n|" \ 
  -e "/ResourceDisk.MountPoint=/ s|=.*$|=/mnt/resource|" \
  -e "/ResourceDisk.SwapSizeMB=/ s|=.*$|=0|" \
  /etc/waagent.conf
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01ee0e4f-fb6a-2a3f-b30e-e2bf4c0b383c
* Version Independent ID: 6f0185df-55bd-c07b-8380-93b9e9428638
* Content: [Swap file is not re-created after a Linux VM restarts - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart)
* Content Source: [support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@carlosporter Thanks for the suggestion. I will

**Comment by genlin** [comment]
@carlosporter, We have updated the script:

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart

I will process to close this issue. Feel free to let me know there is still a problem.

**Comment by genlin** [comment]
@carlosporter, We have updated the script:

https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/swap-file-not-recreated-linux-vm-restart

Let me know if there is still a problem or issue.
