### ISSUE TITLE
[Reset local Windows password for Azure VM offline] Improve step 4 and 5

### ISSUE THREAD

**Issue by riccom76** [MicrosoftDocs/SupportArticles-docs#98]
Hi!

At [step 4](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-local-password-without-agent#detailed-steps-for-the-vm-with-resource-manager-deployment) and at [STEP 5](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-local-password-without-agent#detailed-steps-for-classic-vm) of the article "**_Reset local Windows password for Azure VM offline_**" the recommendation states "Make sure hidden folders are shown".

By default, both folder and extensions are hidden and hence, creating txt files, renaming them from txt to ini/cmd might not be straight forward.

Can you please update the statement of the above steps from "Make sure hidden folders are shown" to something like "Make sure hidden folders **and extensions** are shown"

thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1977f9e4-a4de-71bf-7bca-c88e762d0eff
* Version Independent ID: b38e3607-c21e-6cb6-c2a6-7414ebc9b303
* Content: [Reset a local Windows password without Azure agent - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/reset-local-password-without-agent)
* Content Source: [support/azure/virtual-machines/reset-local-password-without-agent.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/reset-local-password-without-agent.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment]
@riccom76 Thanks for the suggestion. I will add the step into the article.
